In [ ]:
"""
Purpose: To decompose the multi-somas for splitting
using the new decomposition method



"""


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import datajoint as dj
import trimesh
from tqdm.notebook import tqdm
from pathlib import Path

from os import sys
sys.path.append("/meshAfterParty/")

import datajoint_utils as du
from importlib import reload

INFO - 2021-01-24 21:01:49,074 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-01-24 21:01:49,075 - settings - Setting database.user to celiib
INFO - 2021-01-24 21:01:49,076 - settings - Setting database.password to newceliipass
INFO - 2021-01-24 21:01:49,081 - settings - Setting stores to {'minnie65': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65', 'stage': '/mnt/dj-stor01/platinum/minnie65'}, 'meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/meshes'}, 'decimated_meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes'}, 'skeletons': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/skeletons'}}
INFO - 2021-01-24 21:01:49,081 - settings - Setting enable_python_native_blobs to True
INFO - 2021-01-24 21:01:49,092 - connection - Connect

Connecting celiib@at-database.ad.bcm.edu:3306


INFO - 2021-01-24 21:01:49,370 - settings - Setting enable_python_native_blobs to True


In [4]:
#so that it will have the adapter defined
from datajoint_utils import *

In [5]:
test_mode = True

# Debugging the contains method

In [6]:
import system_utils as su

In [7]:
import minfig
import time
import numpy as np
#want to add in a wait for the connection part
random_sleep_sec = np.random.randint(0, 200)
print(f"Sleeping {random_sleep_sec} sec before conneting")
if not test_mode:
    time.sleep(random_sleep_sec)
print("Done sleeping")

du.config_celii()
du.set_minnie65_config_segmentation(minfig)
du.print_minnie65_config_paths(minfig)

#configuring will include the adapters
minnie,schema = du.configure_minnie_vm()

INFO - 2021-01-24 21:01:49,544 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-01-24 21:01:49,544 - settings - Setting database.user to celiib
INFO - 2021-01-24 21:01:49,545 - settings - Setting database.password to newceliipass
INFO - 2021-01-24 21:01:49,547 - settings - Setting enable_python_native_blobs to True


Sleeping 84 sec before conneting
Done sleeping
Current path for external_segmentation_path = /mnt/dj-stor01/platinum/minnie65/02
Current path for external_mesh_path = /mnt/dj-stor01/platinum/minnie65/02/meshes
Current path for external_decimated_mesh_path = /mnt/dj-stor01/platinum/minnie65/02/decimated_meshes
Current path for external_skeleton_path = /mnt/dj-stor01/platinum/minnie65/02/skeletons


INFO - 2021-01-24 21:01:49,813 - settings - Setting enable_python_native_blobs to True


In [8]:
minnie.DecompositionSplit()

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    *split_index   multiplicity   n_splits     split_success  decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     max_soma_n_fac max_soma_volum n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time    
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +------------+ +----------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +------------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+
86469113518181 0              0.25           30.00     0              0         0              1              1            0              =BLOB=     351990         702839      0              0              0              0              1           18375          207            14          332            67             8405623.588454 1592600.262861 16862.775      72.158         72.158         119.648        119.648        14           1.665551621801 0.042168674698 376371.064     21             3.719733353358 0.667          3578468037.248 101376868.8981 425.7230887858 9507.819222915 170403239.8689 113.0561    
86469113526977 0              0.25           30.00     0              0         0              1              0            0              =BLOB=     28282          55501       0              0              0              0              1           14456          480            1           9              9              259616.2284227 259616.2284227 31382.993      375.898        337.387        532.281        497.674        126          0.000485331755 14.0           259616.228     9              0.000485331756 14.0           21692088970.32 130208319.5980 83554.44150048 83554.44163653 2410232107.813 16.6167     
86469113537370 0              0.25           30.00     0              0         0              1              1            0              =BLOB=     364887         726708      0              0              0              0              1           35412          722            9           130            86             5291725.383969 3199336.449533 20098.171      88.474         88.474         442.289        416.15         1115         0.000210706323 8.576923076923 2794910.662    53             0.000398939406 21.038         158187395599.6 70103672.16499 29893.34935611 56598.37280323 2984667841.501 90.4241     
86469113549088 0              0.25           30.00     0              0         0              2              1            0              =BLOB=     460171         918453      0              0              0              0              1           45412          1039           7           140            48             6115515.273582 1874212.578389 28968.65       100.393        100.393        524.753        524.753        991          0.000162046852 7.078571428571 3192593.677    63             0.000310405927 15.73          130913906281.4 63266095.76100 21406.84806184 41005.50196055 2077998512.404 318.2518    
86469113549088 0              0.25           30.00     0              0         1              2              1            0              =BLOB=     699100         1394153     0              0              0              0              1           30650          650            5           478           

# Debugging why there are missing mesh pieces

# Developing the Table

In [ ]:
"""
Pseudocode: 
1) Extract the Segment_id
2) Download the Neuron classification
3) Run the inhibitory and excitatory classifier
4) Extract out the maximum axon angle and the spining percentage
5) Write to the table

"""


In [24]:
minnie.Decomposition()

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    multiplicity   decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time    
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+
86469113421906 0              0.25           30.00     0              0         1              =BLOB=     11723          24809       0              0              0              0              1           0           0              None           0.0            nan            nan            nan            nan            nan            nan            0            0.0            0.0            0.0            0              0.0            0.0            0.0            0.0            0.0            0.0            0.0            14.8309     
86469113424267 0              0.25           30.00     0              0         1              =BLOB=     10252          20204       0              0              0              0              1           0           0              None           0.0            nan            nan            nan            nan            nan            nan            0            0.0            0.0            0.0            0              0.0            0.0            0.0            0.0            0.0            0.0            0.0            17.9755     
86469113425290 0              0.25           30.00     0              0         1              =BLOB=     10910          22764       0              0              0              0              1           0           0              None           0.0            nan            nan            nan            nan            nan            nan            0            0.0            0.0            0.0            0              0.0            0.0            0.0            0.0            0.0            0.0            0.0            16.2558     
86469113431652 0              0.25           30.00     0              0         1              =BLOB=     10031          22403       0              0              0              0              1           0           0              None           0.0            nan            nan            nan            nan            nan            nan            0            0.0            0.0            0.0            0              0.0            0.0            0.0            0.0            0.0            0.0            0.0            14.5114     
86469113438403 0              0.25           30.00     0              0         1              =BLOB=     10015          20509       0              0              0              0              1           0           0              None           0.0            nan            nan            nan            nan            nan            nan            0            0.0            0.0            0.0            0              0.0            0.0            0.0            0.0            0.0            0.0            0.0            17.8075     
86469113439159 0              0.25           30.00     0              0         1              =BLOB=     11947          25033       0              0              0              0              1     

In [9]:
key = ((minnie.DecompositionSplit() & get_exc_inh_classified_table().proj()).proj() & dict(segment_id=864691135181813250)).fetch1()
key

{'segment_id': 864691135181813250,
 'decimation_version': 0,
 'decimation_ratio': Decimal('0.25'),
 'ver': Decimal('30.00'),
 'process_version': 0,
 'index': 0,
 'split_index': 0}

In [25]:
#check to see if there is a neuron that is split:
del key["split_index"]

In [29]:
verbose = True

split_table_neuron = (minnie.DecompositionSplit & key)
if len(split_table_neuron)>0:
    
    if verbose:
        print("Pulling down neurons from DecompositionSplit")
        
    neuron_objs,split_indexes = split_table_neuron.fetch("decomposition","split_index")
else:
    
    if verbose:
        print("Pulling down neurons from Decomposition")
        
    neuron_objs = (minnie.Decomposition() & key).fetch("decomposition")
    split_indexes = [0]
    
    if len(neuron_objs) > 1:
        raise Exception("There were more than 1 neuron when pulling down from Decomposition")
    
if verbose:
    print(f"Number of Neurons found ={len(neuron_objs)}")

Pulling down neurons from DecompositionSplit
Decompressing Neuron in minimal output mode...please wait
Number of Neurons found =1


In [30]:
neuron_objs[0].description

'0_25_soma_0_split'

In [10]:
neuron_obj = (minnie.DecompositionSplit() & key).fetch1("decomposition")

Decompressing Neuron in minimal output mode...please wait


In [11]:
nviz.visualize_neuron(neuron_obj,
                     limb_branch_dict="all")


 Working on visualization type: mesh

 Working on visualization type: skeleton


In [13]:
import classification_utils as clu

In [36]:
return_value = clu.axon_classification(neuron_obj,
                                                    return_error_labels=False,
                                                    verbose=False,
                                                    plot_axons=False,
                                                    label_axon_errors=False,
                                                    return_axon_angles=True)


Working on Limb L0

Working on Limb L1

Working on Limb L10

Working on Limb L11

Working on Limb L12

Working on Limb L4

Working on Limb L5

Working on Limb L7


In [40]:
axon_limb_branch_dict = return_value[0]

In [42]:
axon_limb_branch_dict

{'L1': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 13, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 10]),
 'L11': array([0, 2, 1, 2]),
 'L4': array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.]),
 'L5': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 15, 10]),
 'L7': array([ 0,  1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26,  2])}

In [50]:
if 1 or 1:
    print("hi")
    

hi


In [47]:
nru.limb_branch_dict_to_connected_components(neuron_obj,
                                             limb_branch_dict=axon_limb_branch_dict,
            use_concept_network_directional=False)

[('L1',
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 16, 17, 18, 19,
         20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45])),
 ('L11', array([0, 1, 2])),
 ('L4',
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19])),
 ('L5', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15])),
 ('L7',
  array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26]))]

In [44]:


axon_connected_comps = []
for limb_name, axon_branches in axon_limb_branch_dict.items():
    axon_subgraph = neuron_obj[limb_name].concept_network.subgraph(axon_branches)
    conn_comp = [(limb_name,np.array(list(k))) for k in nx.connected_components(axon_subgraph)]
    axon_connected_comps += conn_comp
    
axon_connected_comps

[('L1',
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 16, 17, 18, 19,
         20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
         37, 38, 39, 40, 41, 42, 43, 44, 45])),
 ('L11', array([0, 1, 2])),
 ('L4',
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19])),
 ('L5', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15])),
 ('L7',
  array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26]))]

In [55]:
(inh_exc_class,
 spine_category,
 axon_angles,
 n_axons,
 n_apicals,
 neuron_spine_density,
 n_branches_processed
) = clu.inhibitory_excitatory_classifier(neuron_obj,
                                    return_spine_classification=True,
                                    return_axon_angles=True,
                                         return_n_axons=True,
                                     return_n_apicals=True,
                                     return_spine_statistics=True)

spine_category = no_spined
spine_category was no_spined so determined as inhibitory

Working on Limb L0

Working on Limb L1

Working on Limb L10

Working on Limb L11

Working on Limb L12

Working on Limb L4

Working on Limb L5

Working on Limb L7

 Working on visualization type: mesh


Did not pass final filters to continuing
Did not pass final filters to continuing
NO APICAL BRANCHES TO PLOT


In [58]:
x = dict(y=5,z=10)
x.get("z",4)

10

In [59]:
x["z"]

10

In [56]:
(inh_exc_class,
 spine_category,
 axon_angles,
 n_axons,
 n_apicals,
 neuron_spine_density,
 n_branches_processed
)

('inhibitory',
 'no_spined',
 {1: {1: 120.94068635131428},
  11: {0: 123.032799418899, 1: 131.2850541462866},
  4: {0: 169.1123957802184},
  5: {0: 135.49666514856264},
  7: {1: 116.91165230055458}},
 5,
 0,
 8.479056202574712e-05,
 1)

In [34]:
(du.get_exc_inh_classified_table() & key).fetch

*nucleus_id    *nucleus_versi *segment_id    cell_type      classifier     timestamp     
+------------+ +------------+ +------------+ +------------+ +------------+ +------------+
166938         3              86469113518181 inhibitory     stelios        2020-11-27 01:
 (Total: 1)

In [16]:
(inh_exc_class,
 spine_category,
 axon_angles,
 axon_flag,
 apical_flag,
 neuron_spine_density,
 n_branches_processed
)

('inhibitory',
 'no_spined',
 {1: {1: 120.94068635131428},
  11: {0: 123.032799418899, 1: 131.2850541462866},
  4: {0: 169.1123957802184},
  5: {0: 135.49666514856264},
  7: {1: 116.91165230055458}},
 True,
 False,
 8.479056202574712e-05,
 1)

In [32]:
all_axon_angles = []
for limb_idx,limb_data in axon_angles.items():
    for candidate_idx,cand_angle in limb_data.items():
        all_axon_angles.append(cand_angle)
        
all_axon_angles

[120.94068635131428,
 123.032799418899,
 131.2850541462866,
 169.1123957802184,
 135.49666514856264,
 116.91165230055458]

# Defining the Table

In [ ]:
import neuron_utils as nru
import neuron
import trimesh_utils as tu
import numpy as np

In [ ]:
import meshlab
meshlab.set_meshlab_port(current_port=None)

In [20]:
classified_table = (minnie.BaylorManualCellType() &
                        'nucleus_version=3' & 
                        "(cell_type = 'excitatory') or  (cell_type = 'inhibitory')")
classified_table.describe()

-> minnie.NucleusID
---
cell_type            : enum('excitatory','inhibitory','other','unknown') # morphology (valid options: 'excitatory', 'inhibitory', 'other', 'unknown')
classifier           : varchar(256)                 # name of human classifier
timestamp=CURRENT_TIMESTAMP : timestamp                    



"-> minnie.NucleusID\n---\ncell_type            : enum('excitatory','inhibitory','other','unknown') # morphology (valid options: 'excitatory', 'inhibitory', 'other', 'unknown')\nclassifier           : varchar(256)                 # name of human classifier\ntimestamp=CURRENT_TIMESTAMP : timestamp                    \n"

In [23]:
#minnie.DecompositionSplit.describe()

In [ ]:
import numpy as np
import time
import proofreading_utils as pru

max_n_somas=8
cell_type_version = 0

verbose = True

@schema
class CellTypes(dj.Computed):
    definition="""
    -> minnie.Decomposition()
    split_index          : tinyint unsigned             # the index of the neuron object that resulted AFTER THE SPLITTING ALGORITHM
    cell_type_version    : tinyint unsigned             # the version of code used for this cell typing classification
    ---
    cell_type: enum('excitatory','inhibitory','other','unknown') # morphology (valid options: 'excitatory', 'inhibitory', 'other', 'unknown')
    cell_type_predicted: enum('excitatory','inhibitory','other','unknown') # morphology predicted by classifier
    spine_category: enum('no_spined','sparsely_spined','densely_spined')
    axon_angle_minimum=NULL:double #the anlge of an identified axon
    n_axons: tinyint unsigned             # Number of axon candidates identified
    n_apicals: tinyint unsigned             # Number of apicals identified
    spine_density:double              # the number of spines divided by skeletal length for branches analyzed in classification
    n_branches_processed: int unsigned                 # the number branches used for the spine density analysis
    run_time=NULL : double                   # the amount of time to run (seconds)

    
    """
                             
    
    classified_table = du.get_exc_inh_classified_table()
    
    key_source = (minnie.Decomposition & 
                (minnie.NeuronSplitSuggestions.proj()) & 
                (classified_table.proj()))
    
    

    def make(self,key):
        """
        Pseudocode for process:

        """
        
        whole_pass_time = time.time()
        
        
        
        # 1) Get the segment id from the key
        segment_id = key["segment_id"]
        print(f"\n\n\n---- Working on Neuron {key['segment_id']} ----")
        
        
        # 2) Get the decomposed neuron object from Decomposition table and the split suggestions
        neuron_obj = (minnie.Decomposition & key).fetch1("decomposition")
        
        # 3) Retrieve the multi soma suggestions
        split_results = (minnie.NeuronSplitSuggestions & key).fetch1("split_results")
        
        # 4) Get the number of splits required for this neuron
        n_paths_cut = pru.get_n_paths_cut(split_results)

        if verbose:
            print(f"n_paths_cut = {n_paths_cut}")
            
            
        # 5) Split the neuron into a list of neuron objects
        neuron_list = pru.split_neuron(neuron_obj,
                        limb_results=split_results,
                                            )
        
        if verbose:
            print(f"Number of neurons: {len(neuron_list)}")
        
        neuron_entries = []
        for neuron_idx in range(len(neuron_list)):
            
            """
            # 6) For each neuron object in the list:
            # - get the number of errored limbs (to indicate the success type)
            # - Compute the information on the largest soma faces and volume
            # - Save the neuron object to the external
            # - Add the new write key to a list to commit 
            """
            n = neuron_list[neuron_idx]
            #for n in neuron_list:
            #     nviz.visualize_neuron(n,
            #                          limb_branch_dict="all")

            # - get the number of errored limbs (to indicate the success type)
            if n.n_error_limbs == 0:
                split_success = 0
            elif n.multi_soma_touching_limbs == 0:
                split_successs = 1
            elif n.same_soma_multi_touching_limbs == 0:
                split_success = 2
            else:
                split_success = 3

            if verbose:
                print(f"split_success = {split_success}")

            # - Compute the information on the largest soma faces and volume
            soma_volumes = [n[k].volume/1000000000 for k in n.get_soma_node_names()] 
            soma_n_faces = [len(n[k].mesh.faces) for k in n.get_soma_node_names()] 

            largest_n_faces = np.max(soma_n_faces)
            largest_volume = np.max(soma_volumes)

            if verbose:
                print(f"largest_n_faces = {largest_n_faces}")
                print(f"largest_volume = {largest_volume}")


            #6) Save the file in a certain location
            if True:
                save_time = time.time()
                ret_file_path = n.save_compressed_neuron(output_folder=str(du.get_decomposition_path()),
                                                  return_file_path=True,
                                                 export_mesh=False,
                                                 suppress_output=True)

                ret_file_path_str = str(ret_file_path.absolute()) + ".pbz2"
                print(f"Save time = {time.time() - save_time}")
            else:
                ret_file_path_str = "dummy_holder"



            #7) Pass stats and file location to insert
            new_key = dict(key,
                           split_index = neuron_idx,
                           multiplicity=len(neuron_list),

                           n_splits = n_paths_cut,
                           split_success = split_success,

                           max_soma_n_faces = largest_n_faces,
                           max_soma_volume = largest_volume,


                           decomposition=ret_file_path_str,
                           n_vertices=len(n.mesh.vertices),
                           n_faces=len(n.mesh.faces),
                           run_time=np.round(time.time() - whole_pass_time,4)
                          )

            stats_dict = n.neuron_stats()
            new_key.update(stats_dict)


            neuron_entries.append(new_key)

        
        self.insert(neuron_entries, allow_direct_insert=True, skip_duplicates=True)

        print(f"\n\n ------ Total time for {segment_id} = {time.time() - whole_pass_time} ------")
    

# Running the Populate

In [ ]:
curr_table = (minnie.schema.jobs & "table_name='__decomposition_split'")
(curr_table)#.delete()# & "status='error'")
#curr_table.delete()
#(curr_table & "error_message = 'ValueError: need at least one array to concatenate'").delete()

In [ ]:
import time
pru = reload(pru)

start_time = time.time()
if not test_mode:
    time.sleep(random.randint(0, 800))
print('Populate Started')
if not test_mode:
    DecompositionSplit.populate(reserve_jobs=True, suppress_errors=True)
else:
    DecompositionSplit.populate(reserve_jobs=True, suppress_errors=True)
print('Populate Done')

print(f"Total time for DecompositionSplit populate = {time.time() - start_time}")