In [1]:
from os import sys
sys.path.append("/meshAfterParty/")
#sys.path.append("../../meshAfterParty/meshAfterParty")

In [2]:
from importlib import reload
import os
from pathlib import Path
os.getcwd()

import neuron_utils as nru
nru = reload(nru)
import neuron
neuron=reload(neuron)
import neuron_visualizations as nviz
import time

In [3]:
import system_utils as su

# Loading the meshparty object with adaptive correspondence

In [45]:
f = "lower"
f.replace("lo","median")

'medianwer'

In [6]:
nru = reload(nru)
neuron = reload(neuron)
adaptive_neuron = nru.decompress_neuron(filepath="/notebooks/test_neurons/preprocessed_neurons/meshparty/12345_double_soma_adaptive_correspondence_meshparty",
                     original_mesh='/notebooks/test_neurons/preprocessed_neurons/meshparty/12345_double_soma_adaptive_correspondence_meshparty')

Inside decompress neuron and decomposition_type = meshparty
Passed faces original mesh check
Passed vertices original mesh check





------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 61 len(curr_limb_divided_skeletons) = 61
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.34769248962402344
touching_pieces = [36]
Total time for mesh connectivity = 0.703364372253418
Touching piece endpoints = [[754818.09674815 945265.28459266 874984.43059141]
 [758656.5463299  950259.33381173 872013.37980394]]
inside inner loop len(curr_limb_divided_skeletons) = 61
closest_endpoint = [758656.5463299  950259.33381173 872013.37980394]
Starting_edge inside branches_to_conept = [[754818.09674815 945265.28459266 874984.43059141]
 [758656.5463299  950259.33381173 872013.37980394]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [39]
printing out current edge:
[[758656.5463299  950259.33381173 872013.37980394]
 [754818.09674815 945265.28459266 874984.43059141]]
edge_endpoints_to_process was empty so exiting loop after 61 iterations
start

Local time for concept mapping = 0.5840303897857666


------Working on limb 6 -------
inside loop len(curr_limb_divided_meshes) = 17 len(curr_limb_divided_skeletons) = 17
--- Working on soma_idx: 1----
Total time for filtering periphery meshes = 0.0642235279083252
touching_pieces = [13]
Total time for mesh connectivity = 0.1440589427947998
Touching piece endpoints = [[865899.05115931 988116.36181451 860319.94103288]
 [865951.42692904 982604.31816129 862424.97066397]]
inside inner loop len(curr_limb_divided_skeletons) = 17
closest_endpoint = [865899.05115931 988116.36181451 860319.94103288]
Starting_edge inside branches_to_conept = [[865899.05115931 988116.36181451 860319.94103288]
 [865951.42692904 982604.31816129 862424.97066397]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [10]
printing out current edge:
[[865899.05115931 988116.36181451 860319.94103288]
 [865951.42692904 982604.31816129 862424.97066397]]
edge_endpoints_to_process 

Total time for neuron instance creation = 23.901001691818237


# Picking the Neuron to use:

In [12]:
uncompressed_neuron = adaptive_neuron

# Verify Width needed for the meshparty avenue (CONCLUSION 400 LOOKS ABOUT RIGHT FOR WIDTH)

In [16]:
import neuron_searching as ns
import neuron_visualizations as nviz

functions_list = [
    ns.width,
    ns.n_faces_branch
]

returned_limb_branch_dict = ns.query_neuron(uncompressed_neuron,
               functions_list=functions_list,
                query="width < 600 and n_faces_branch>100"
               )

nviz.visualize_neuron(adaptive_neuron,
                      visualize_type=["mesh"],
                      mesh_whole_neuron=True,
                      mesh_color=[1,0,0,1],
                     limb_branch_dict=returned_limb_branch_dict,
                     )



 Working on visualization type: mesh


# Calculating the Spines

In [25]:
functions_list = ["width","n_faces_branch"]
current_query="width > 600 and n_faces_branch>100"
check_spine_query = ns.query_neuron(uncompressed_neuron,
                       functions_list=functions_list,
                       query=current_query)
nviz.visualize_neuron(uncompressed_neuron,
                     limb_branch_dict=check_spine_query,
                     mesh_whole_neuron=False)


 Working on visualization type: mesh


In [26]:
check_spine_query

{'L0': array([ 0,  2,  4,  6,  8, 10, 11, 13, 14, 15, 16, 17, 18, 19, 21, 24, 26,
        27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
        45, 46, 47, 48, 49, 52, 53, 54, 56, 58, 60]),
 'L1': array([ 0,  2,  4,  6,  8, 10, 11, 12, 13, 15, 17, 18, 19, 21, 23, 24, 27,
        28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 44]),
 'L2': array([ 0,  2,  5,  6,  7,  8,  9, 10, 11, 12, 15, 17, 18, 19, 20, 23, 25,
        26, 35, 37]),
 'L3': array([ 0,  1,  2,  5,  6,  7,  8, 10, 11, 13, 14, 16, 18, 20, 21, 22, 24,
        25, 26, 29, 30, 32, 35, 36, 37, 38, 39, 41, 43, 45, 46]),
 'L4': array([ 0,  1,  2,  3,  5,  7, 12, 13, 21, 22, 23, 24, 25, 26, 28, 32]),
 'L5': array([0, 1, 2, 3, 4, 5, 6]),
 'L6': array([ 1,  2,  3,  4,  5,  8,  9, 10, 11, 12, 13, 15, 16]),
 'L7': array([ 0,  1,  2,  3,  4,  6,  7,  8, 10, 11, 12, 13, 16, 18]),
 'L8': array([ 0,  3,  4,  5,  9, 10]),
 'L9': array([0])}

In [30]:
neuron = reload(neuron)
uncompressed_neuron = neuron.Neuron(uncompressed_neuron)
uncompressed_neuron.calculate_spines(
    query="width > 600 and n_faces_branch>100"

)

Recieved another instance of Neuron class in init -- so just copying data
smoothness_threshold = 0.08
Working on limb L0 branch 36
Working on limb L0 branch 24
Working on limb L0 branch 38
Working on limb L0 branch 17
Working on limb L0 branch 39
Working on limb L0 branch 40
Working on limb L0 branch 16
Working on limb L0 branch 43
Working on limb L0 branch 44
Working on limb L0 branch 60
Working on limb L0 branch 13
Working on limb L0 branch 14
Working on limb L0 branch 45
Working on limb L0 branch 46
Working on limb L0 branch 10
Working on limb L0 branch 11
Working on limb L0 branch 34
Working on limb L0 branch 52
Working on limb L0 branch 49
Working on limb L0 branch 8
Working on limb L0 branch 54
Working on limb L0 branch 21
Working on limb L0 branch 47
Working on limb L0 branch 6
Working on limb L0 branch 56
Working on limb L0 branch 15
Working on limb L0 branch 42
Working on limb L0 branch 48
Working on limb L0 branch 4
Working on limb L0 branch 35
Working on limb L0 branch 41
Wo

In [31]:
nviz.plot_spines(uncompressed_neuron)


 Working on visualization type: mesh


# Calculating the Different Widths

In [33]:
ex_branch = uncompressed_neuron.concept_network.nodes["L1"]["data"].concept_network.nodes[0]["data"]
ex_branch.width_array

{'no_spine_average_mesh_center': array([292.41943139, 158.43277856, 215.49804448, 261.88139752,
        182.62813773, 186.9468557 , 381.62211965, 298.8295471 ,
         84.84772502, 162.3338237 , 324.20948806, 337.82119951,
        227.81443606, 319.19330664, 257.95435532, 117.79815705,
        332.16650029, 293.79460771, 213.96291566, 313.90864018,
        261.50133898, 189.88846563, 426.20675526, 396.929145  ,
        168.62080206, 178.15386097, 229.21565593, 216.46757194,
        200.90968662, 158.75086946, 205.89005194, 351.40213282,
        522.26248988, 246.52411606, 200.11370726, 349.66973758,
        231.85891815, 202.34537968, 296.50625597, 229.66600692,
        203.07597991, 125.73034374, 250.95014065, 328.94615055,
        335.09556159, 277.86871291, 480.61685415, 448.52378842,
        264.35598938, 368.40458557, 504.91299747, 256.85013971,
        187.65899495, 185.57731505, 285.33515573, 276.32649085,
        162.22308996, 279.65597528, 242.3298203 , 276.92109677,
        

In [38]:
import skeleton_utils as sk

In [43]:
error_branch.width

3419.3429890393018

In [40]:
error_branch = uncompressed_neuron.concept_network.nodes["L3"]["data"].concept_network.nodes[22]["data"]
sk.calculate_skeleton_distance(error_branch.skeleton),error_branch.mesh.faces.shape
sk.graph_skeleton_and_mesh(other_meshes=[error_branch.mesh],
                          other_skeletons=[error_branch.skeleton])

In [41]:
nviz.visualize_neuron(uncompressed_neuron,
                     visualize_type=["mesh","skeleton"],
                     limb_branch_dict=dict(L3=[22]),
                     mesh_color="red",
                     mesh_color_alpha=1,
                     mesh_whole_neuron=True,
                     )


 Working on visualization type: mesh

 Working on visualization type: skeleton


In [35]:
import compartment_utils as cu
cu = reload(cu)
uncompressed_neuron.calculate_width_without_spines(
                                      skeleton_segment_size = 1000,
                                       width_segment_size=None,
                                      width_name = "no_spine_average_mesh_center")

Working on limb L0 branch 36
Working on limb L0 branch 24
Working on limb L0 branch 38
Working on limb L0 branch 17
Working on limb L0 branch 22
Working on limb L0 branch 39
Working on limb L0 branch 40
Working on limb L0 branch 12
Working on limb L0 branch 16
Working on limb L0 branch 43
Working on limb L0 branch 44
Working on limb L0 branch 59
Working on limb L0 branch 60
Working on limb L0 branch 13
Working on limb L0 branch 14
Working on limb L0 branch 45
Working on limb L0 branch 46
Working on limb L0 branch 10
Working on limb L0 branch 11
Working on limb L0 branch 34
Working on limb L0 branch 52
Working on limb L0 branch 49
Working on limb L0 branch 50
Working on limb L0 branch 8
Working on limb L0 branch 9
Working on limb L0 branch 54
Working on limb L0 branch 55
Working on limb L0 branch 21
Working on limb L0 branch 47
Working on limb L0 branch 6
Working on limb L0 branch 7
Working on limb L0 branch 51
Working on limb L0 branch 56
Working on limb L0 branch 15
Working on limb L0

Exception: unique_removed_faces = [41]

In [ ]:
ex_branch.width_array

# Testing out the Distance to Soma function

In [ ]:
import networkx_utils as xu
xu.get_neighbors(curr_limb.concept_network,27)
#curr_limb.current_starting_node

In [ ]:
curr_branch_idx = 24
nviz.visualize_neuron(uncompressed_neuron,
                     limb_branch_dict=dict(L1=[curr_branch_idx]),
                     visualize_type=["mesh"],
                      mesh_color="red",
                     mesh_whole_neuron=True)

In [ ]:
curr_limb = uncompressed_neuron.concept_network.nodes["L1"]["data"]

In [ ]:
nru.branch_skeletal_distance_from_soma(curr_limb = curr_limb,
                                      branch_idx = curr_branch_idx,
                                      somas=[0,1],
                                      dict_return = True,
                                      print_flag=True)

# Testing the Query on Distance from Soma

In [ ]:
distance_from_soma_threshold = 30000
close_limb_branch_dict = ns.query_neuron(uncompressed_neuron,
                                        functions_list=[ns.skeletal_distance_from_soma],
                                        query=f"skeletal_distance_from_soma<{distance_from_soma_threshold}",
                                        function_kwargs=dict(somas=[0])


                                        )

In [ ]:
color_dictionary = nviz.visualize_neuron(uncompressed_neuron,
                     limb_branch_dict=close_limb_branch_dict,
                     mesh_color="random",
                                         mesh_color_alpha=1,
                     mesh_whole_neuron=True,
                     return_color_dict=True)

In [ ]:
import matplotlib_utils as mu
mu.plot_color_dict(color_dictionary)

# Using the queries to find the mesh parts

In [ ]:
import neuron_visualizations as nviz
import neuron_searching as ns

In [ ]:
current_functions_list = [
    "spines_per_skeletal_length",
    "no_spine_average_mesh_center",
    "n_spines",
    "n_faces_branch",
    
]

import width_utils as wu
wu = reload(wu)


with su.suppress_stdout_stderr():
    #The base level of segments we are going to check for axons
    limb_branch_dict = ns.query_neuron(uncompressed_neuron,
                                       query="n_spines < 4 and no_spine_average_mesh_center < 400",
                   functions_list=current_functions_list)
    #print(F"limb_branch_dict BEFORE = {limb_branch_dict}")

    #How to give a limb_branch_dict as an argument
    current_functions_list = ["axon_segment"]
    limb_branch_dict_upstream_filter = ns.query_neuron(uncompressed_neuron,
                                       query="axon_segment==True",
                                       function_kwargs=dict(limb_branch_dict =limb_branch_dict,
                                                            downstream_face_threshold=3000,
                                                            width_match_threshold=50,
                                                           print_flag=False),
                                       functions_list=current_functions_list)

In [ ]:
color_dictionary = nviz.visualize_neuron(uncompressed_neuron,
                     limb_branch_dict="all",
                     mesh_color="random",
                                         mesh_color_alpha=1,
                     mesh_whole_neuron=True,
                     return_color_dict=True)

In [ ]:
nviz = reload(nviz)
xu = reload(xu)
limb_idx = "L1"
nviz.plot_limb_concept_network_2D(neuron_obj=uncompressed_neuron,
                                 limb_name=limb_idx,
                                 node_colors=color_dictionary)

In [ ]:
str(type(uncompressed_neuron)) == str(neuron.Neuron)

In [ ]:
returned_color_dict = nviz.visualize_neuron(uncompressed_neuron,
                      visualize_type=["mesh"],
                     limb_branch_dict=dict(L0=["all"]),
                      mesh_color_alpha=1,
                      return_color_dict=True
                     mesh_whole_neuron=False)

In [ ]:
nviz = reload(nviz)
with su.suppress_stdout_stderr():
    nviz.visualize_neuron(uncompressed_neuron,
                          visualize_type=["mesh"],
                         limb_branch_dict=limb_branch_dict_upstream_filter,
                          mesh_color="red",
                          mesh_color_alpha=1,
                         mesh_whole_neuron=True)

# Conclusions

In [ ]:
"""
There are still some false positives but this can be fixed when we do the merge analysis


"""

# How to find the axon from this point

In [ ]:
"""
Ideas: 
1) Can look at how much axon in a row without being interrupted (or only interrupted by a certain amount)
2) Look at branches that are within x distance of the soma
3) Look at the width profile of the branch
4) not a lot of spining
5) where on the soma it is
"""

# create a function that will measure the distance from the starting point (aka the soma)

In [ ]:
import neuron_searching as ns
ns = reload(ns)

current_functions_list = [
    "skeletal_distance_from_soma",
    "no_spine_average_mesh_center",
    "n_spines",
    "n_faces_branch",
    
]

function_kwargs=dict(somas=[0,1],print_flag=False)
soma_skeletal_distance_threshold = 30000
query="skeletal_distance_from_soma < @soma_skeletal_distance_threshold"
query_variables_dict = dict(limb_list=['L1'],
                           soma_skeletal_distance_threshold=soma_skeletal_distance_threshold)

# limb_branch_dict_df = ns.query_neuron(uncompressed_neuron,
#                                    query=query,
#                                       function_kwargs=function_kwargs,
#                                       query_variables_dict=query_variables_dict,
#                functions_list=current_functions_list,
#                                   return_dataframe=True)

limb_branch_dict = ns.query_neuron(uncompressed_neuron,
                                   query=query,
               functions_list=current_functions_list,
                                   query_variables_dict=query_variables_dict,
                                   function_kwargs=function_kwargs,
                                  return_dataframe=False)


In [ ]:
limb_branch_dict

In [ ]:
nviz = reload(nviz)

returned_colors = nviz.visualize_neuron(uncompressed_neuron,
                      visualize_type=["mesh"],
                     limb_branch_dict=limb_branch_dict,
                      mesh_color="red",
                      mesh_color_alpha=1,
                     #mesh_whole_neuron=True,
                     return_color_dict=True,
                    print_time=True)

In [ ]:
mu = reload(mu)
mu.plot_color_dict(returned_colors,print_flag=False)

# The algorithm for finding the axon branch

# --- practicing getting skeletons ----

In [ ]:
neuron = reload(neuron)
uncompressed_neuron = neuron.Neuron(uncompressed_neuron)

In [ ]:
ex_limb_obj = uncompressed_neuron.concept_network.nodes["L3"]["data"]

In [ ]:
ex_limb_obj.find_branch_by_skeleton_coordinate(np.array([729486.6, 977760.4, 921825.8]))

In [ ]:
ex_limb_obj.concept_network_data_by_soma
ex_limb_obj.get_skeleton_soma_starting_node(1)

In [ ]:
interested_soma = 0
ex_limb_obj = uncompressed_neuron.concept_network.nodes["L4"]["data"]

In [ ]:
ex_limb_obj.touching_somas()
ex_limb_starting_coordinate = ex_limb_obj.get_soma_starting_coordinate(1)
ex_limb_starting_coordinate

In [ ]:
import skeleton_utils as sk
import networkx as nx
import networkx_utils as xu
ex_limb_skeleton_graph = sk.convert_skeleton_to_graph(ex_limb_obj.skeleton)
xu.get_nodes_with_attributes_dict(ex_limb_skeleton_graph,
                                  attribute_dict=dict(coordinates=ex_limb_starting_coordinate))

In [ ]:


get_skeleton_soma_starting_node(uncompressed_neuron.concept_network.nodes["L5"]["data"],
                               0,
                               print_flag = True)

In [ ]:
ex_limb_skeleton_graph.nodes[256]

In [ ]:
ex_limb_obj.skeleton[1000][1]

In [ ]:
import numpy_utils as nu
import numpy as np


limb= ex_limb_obj
target_coordinate = np.array([695784., 986044., 906273.])



find_branch_by_skeleton_coordinate(limb= ex_limb_obj,
target_coordinate = np.array([729486.6, 977760.4, 921825.8]))

In [ ]:
"""
New Tool for help with identification

Purpose: 

Given: 
a) If given limb or branch (any object)
b) want starting endpoint of that limb/branch

Gete the skeleton of x distance from the starting point
Get the vector from the starting point to the endpoints
Get the angle between that and a hardcoded vector of your choice


Get the paths from the endpoints to the starting point
For all those paths get the vector from 



Better algorithm: 
1) Take all skeletons of branches that border a soma
and stitch them together at the soma node


Would want to trace it back to the specific branch it starts on

For each limb: 
1) 

2) 



"""

# Developing colors

In [ ]:
import webcolors
import numpy as np

def closest_colour(requested_colour):
    min_colours = {}
    for key, name in webcolors.CSS3_HEX_TO_NAMES.items():
        r_c, g_c, b_c = webcolors.hex_to_rgb(key)
        rd = (r_c - requested_colour[0]) ** 2
        gd = (g_c - requested_colour[1]) ** 2
        bd = (b_c - requested_colour[2]) ** 2
        min_colours[(rd + gd + bd)] = name
    return min_colours[min(min_colours.keys())]

def get_colour_name(requested_colour):
    try:
        closest_name = actual_name = webcolors.rgb_to_name(requested_colour)
    except ValueError:
        closest_name = closest_colour(requested_colour)
        actual_name = None
    return actual_name, closest_name

def convert_rgb_to_name(rgb_value):
    rgb_value = np.array(rgb_value)
    if not nu.is_array_like(rgb_value[0]):
        rgb_value = rgb_value.reshape(1,-1)
    
    print(f"rgb_value.shape = {rgb_value.shape}")

    output_colors = []
    for k in rgb_value:
        if len(k) > 3:
            k = k[:3]
        adjusted_color_value = np.array(k)*255
        output_colors.append(get_colour_name(adjusted_color_value)[-1])
    
    if len(output_colors) == 1:
        return output_colors[0]
    elif len(output_colors) > 1:
        return output_colors
    else:
        raise Exception("len(output_colors) == 0")