In [ ]:
"""
Purpose: To test out the changes needed to make to datajoint table 
for v4 run: 

1) changing how the axon and dendrite skeleton are saved
2) Doing the complete axon preprocessing, saving that off
and then passing that to the neuron proofreading function
3) How to save off the suggested edits in form that we 
can create suggested edits fo rneuroglancer
4) Make sure webbing and bouton information in table
"""

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import datajoint as dj
import trimesh
from tqdm.notebook import tqdm
from pathlib import Path

from os import sys
sys.path.append("/meshAfterParty/")
sys.path.append("/meshAfterParty/meshAfterParty")

import datajoint_utils as du
from importlib import reload

INFO - 2021-05-09 19:20:18,564 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-05-09 19:20:18,566 - settings - Setting database.user to celiib
INFO - 2021-05-09 19:20:18,568 - settings - Setting database.password to newceliipass
INFO - 2021-05-09 19:20:18,572 - settings - Setting stores to {'minnie65': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65', 'stage': '/mnt/dj-stor01/platinum/minnie65'}, 'meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/meshes'}, 'decimated_meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes'}, 'skeletons': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/skeletons'}}
INFO - 2021-05-09 19:20:18,573 - settings - Setting enable_python_native_blobs to True
INFO - 2021-05-09 19:20:18,586 - connection - Connect

Connecting celiib@at-database.ad.bcm.edu:3306


INFO - 2021-05-09 19:20:19,007 - settings - Setting enable_python_native_blobs to True
INFO - 2021-05-09 19:20:19,011 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-05-09 19:20:19,012 - settings - Setting database.user to celiib
INFO - 2021-05-09 19:20:19,013 - settings - Setting database.password to newceliipass
INFO - 2021-05-09 19:20:19,014 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-05-09 19:20:19,014 - settings - Setting database.user to celiib
INFO - 2021-05-09 19:20:19,015 - settings - Setting database.password to newceliipass
INFO - 2021-05-09 19:20:19,018 - settings - Setting enable_python_native_blobs to True
INFO - 2021-05-09 19:20:19,443 - settings - Setting enable_python_native_blobs to True


In [3]:
#configuring will include the adapters
minnie,schema = du.configure_minnie_vm()

INFO - 2021-05-09 19:20:21,740 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-05-09 19:20:21,742 - settings - Setting database.user to celiib
INFO - 2021-05-09 19:20:21,744 - settings - Setting database.password to newceliipass
INFO - 2021-05-09 19:20:21,748 - settings - Setting enable_python_native_blobs to True
INFO - 2021-05-09 19:20:22,219 - settings - Setting enable_python_native_blobs to True


In [5]:
import neuron_visualizations as nviz
import neuron_utils as nru
import proofreading_utils as pru
import time
import system_utils as su
import axon_utils as au
import trimesh_utils as tu

In [6]:
[k for k in dir(tu) if "box" in k]

['bbox_mesh_restriction',
 'bbox_side_length_ratios',
 'bbox_volume',
 'bbox_volume_oriented',
 'bounding_box',
 'bounding_box_center',
 'bounding_box_corners',
 'bounding_box_longest_side',
 'bounding_box_oriented_side_lengths',
 'box_mesh',
 'check_coordinates_inside_bounding_box',
 'check_meshes_inside_mesh_bbox',
 'check_meshes_inside_multiple_mesh_bbox',
 'check_meshes_outside_mesh_bbox',
 'check_meshes_outside_multiple_mesh_bbox',
 'coordinates_to_bounding_box',
 'filter_meshes_by_bounding_box_longest_side']

In [9]:
neuron_split_idxs

[0]

In [80]:
neuron_obj.segment_id

864691135841099491

In [54]:
segment_id = 864691136540183458
segment_id = 864691136136605053
segment_id = 864691136464362887
segment_id = 864691135791213391
segment_id = 864691136031747259
segment_id = 864691135841099491
segment_id = 864691135538151026
neuron_objs,neuron_split_idxs = du.decomposition_with_spine_recalculation(segment_id)
neuron_obj = neuron_objs[0]

**Using table __decomposition_split for table_to_neuron_objs**
Decompressing Neuron in minimal output mode...please wait
Dont need spine recalculation
**Using table __decomposition_split for table_to_neuron_objs**
Decompressing Neuron in minimal output mode...please wait


Exception: Could Not find matching faces on decompression of mesh <trimesh.Trimesh(vertices.shape=(9988, 3), faces.shape=(19977, 3))>

In [56]:
curr_limb_mesh= su.decompress_pickle("curr_limb_mesh")
miss_mesh= su.decompress_pickle("miss_mesh")
dec_mesh= su.decompress_pickle("dec_mesh")

In [69]:
nviz.plot_objects(dec_mesh)

In [72]:
split_results = pru.multi_soma_split_suggestions(orig_neuron_obj,plot_intermediates=False)

Skipping endnode 317 because skeletal distance was 2424.451764953736 and threshold was 2500
Gettng rid of 1 nodes INSIDE SKELETON TO GRAPH CONVERSION
Skipping endnode 317 because skeletal distance was 2424.451764953736 and threshold was 2500
Skipping endnode 325 because skeletal distance was 1709.3672674317058 and threshold was 2500
Skipping endnode 317 because skeletal distance was 2331.9895915833904 and threshold was 2500
Skipping endnode 317 because skeletal distance was 2331.9895915833904 and threshold was 2500
Skipping endnode 343 because skeletal distance was 784.147736196798 and threshold was 2500
Skipping endnode 345 because skeletal distance was 2473.339459630023 and threshold was 2500
Skipping endnode 354 because skeletal distance was 1934.3006760079209 and threshold was 2500


In [81]:
orig_neuron_obj.segment_id

864691135538151026

In [82]:
verbose = True
(neuron_list,
        neuron_list_errored_limbs_area,
         neuron_list_errored_limbs_skeletal_length,
        neuron_list_n_multi_soma_errors,
        neuron_list_n_same_soma_errors) = pru.split_neuron(orig_neuron_obj,
                        limb_results=split_results,
                                       verbose=verbose,
                                        return_error_info=True
                                            )

using precomputed split suggestions
Gettng rid of 1 nodes INSIDE SKELETON TO GRAPH CONVERSION
Gettng rid of 1 nodes INSIDE SKELETON TO GRAPH CONVERSION


---Working on Splitting Limb 0 with 27 components----


----Working on seperate_graph 0----


---------Working on soma_idx = 0, soma_group_idx 0, endpt = [1002730.  735303.  598656.]---------
Starting_edge inside branches_to_conept = [[1002730.  735303.  598656.]
 [1004840.  803123.  626293.]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [17]
printing out current edge:
[[1002730.  735303.  598656.]
 [1004840.  803123.  626293.]]
edge_endpoints_to_process was empty so exiting loop after 52 iterations
starting_node in concept map (that should match the starting edge) = 30
Total time for branches to concept conversion = 1.3081436157226562

Done generating concept network 




----Working on seperate_graph 1----
There was no starting information so doing to put dummy information and rand

There was no starting information so doing to put dummy information and random starting endpoint = [1064477.42444581  916218.49885869  747064.75264708]


---------Working on soma_idx = -1, soma_group_idx -1, endpt = [1064477.42444581  916218.49885869  747064.75264708]---------
Starting_edge inside branches_to_conept = [[1064477.42444581  916218.49885869  747064.75264708]
 [1084509.0933129   913279.28831421  740265.35429863]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [0]
printing out current edge:
[[1064477.42444581  916218.49885869  747064.75264708]
 [1084509.0933129   913279.28831421  740265.35429863]]
edge_endpoints_to_process was empty so exiting loop after 9 iterations
starting_node in concept map (that should match the starting edge) = 0
Total time for branches to concept conversion = 0.21150755882263184

Done generating concept network 




----Working on seperate_graph 13----


---------Working on soma_idx = 2, soma_group_id



---Working on Splitting Limb 2 with 2 components----


----Working on seperate_graph 0----


---------Working on soma_idx = 1, soma_group_idx 0, endpt = [1125170. 1000790.  764669.]---------
Starting_edge inside branches_to_conept = [[1125170. 1000790.  764669.]
 [1146530.  995267.  777269.]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [0]
printing out current edge:
[[1125170. 1000790.  764669.]
 [1146530.  995267.  777269.]]
edge_endpoints_to_process was empty so exiting loop after 6 iterations
starting_node in concept map (that should match the starting edge) = 0
Total time for branches to concept conversion = 0.24654030799865723

Done generating concept network 




----Working on seperate_graph 1----


---------Working on soma_idx = 3, soma_group_idx 0, endpt = [1133868.94444444  986978.73333333  753337.76111111]---------
Starting_edge inside branches_to_conept = [[1133868.94444444  986978.73333333  753337.76111111]
 [1138090.4

--- 4) Finshed generating Limb objects and adding them to concept graph: 1.4914467334747314
--- 5) SKIPPING Doing the adaptive mesh correspondence on the meshparty preprocessing ---
--- 6) SKIPPING Using the computed_attribute_dict to populate neuron attributes ---
self.n_limbs = 5
7) Calculating the spines for the neuorn if do not already exist
Total time for neuron instance creation = 3.1935720443725586


------ Working on Soma 3 -------
limb_neighbors = [10, 18, 30, 36, 52]
limb_neighbors BEFORE error limbs removed = [10, 18, 30, 36, 52]
limb_neighbors AFTER error limbs removed = [10 18 30 36 52]
curr_n_multi_soma_limbs_cancelled = 0
curr_n_same_soma_limbs_cancelled = 0
n_errored_lims = 0
curr_error_limbs_cancelled_area = []
local_floating_meshes = []
Already have preprocessed data
--- 1) Finished unpacking preprocessed materials: 0.0003674030303955078
total_edges = [['S0', 'L0'], ['S0', 'L1'], ['S0', 'L2'], ['S0', 'L3'], ['S0', 'L4']]
--- 2) Finished creating neuron connectivity gr

In [83]:
len(neuron_list)

5

In [85]:
neuron_list[1].non_soma_touching_meshes

[<trimesh.Trimesh(vertices.shape=(28641, 3), faces.shape=(57731, 3))>,
 <trimesh.Trimesh(vertices.shape=(3876, 3), faces.shape=(7751, 3))>,
 <trimesh.Trimesh(vertices.shape=(1980, 3), faces.shape=(3918, 3))>,
 <trimesh.Trimesh(vertices.shape=(1155, 3), faces.shape=(2275, 3))>,
 <trimesh.Trimesh(vertices.shape=(1072, 3), faces.shape=(2133, 3))>,
 <trimesh.Trimesh(vertices.shape=(955, 3), faces.shape=(1902, 3))>,
 <trimesh.Trimesh(vertices.shape=(416, 3), faces.shape=(832, 3))>,
 <trimesh.Trimesh(vertices.shape=(315, 3), faces.shape=(630, 3))>,
 <trimesh.Trimesh(vertices.shape=(292, 3), faces.shape=(428, 3))>,
 <trimesh.Trimesh(vertices.shape=(292, 3), faces.shape=(580, 3))>,
 <trimesh.Trimesh(vertices.shape=(272, 3), faces.shape=(527, 3))>,
 <trimesh.Trimesh(vertices.shape=(270, 3), faces.shape=(468, 3))>,
 <trimesh.Trimesh(vertices.shape=(270, 3), faces.shape=(540, 3))>,
 <trimesh.Trimesh(vertices.shape=(209, 3), faces.shape=(414, 3))>,
 <trimesh.Trimesh(vertices.shape=(198, 3), faces.

In [84]:
neuron_list[0].non_soma_touching_meshes

[<trimesh.Trimesh(vertices.shape=(28641, 3), faces.shape=(57731, 3))>,
 <trimesh.Trimesh(vertices.shape=(3876, 3), faces.shape=(7751, 3))>,
 <trimesh.Trimesh(vertices.shape=(1980, 3), faces.shape=(3918, 3))>,
 <trimesh.Trimesh(vertices.shape=(1155, 3), faces.shape=(2275, 3))>,
 <trimesh.Trimesh(vertices.shape=(1072, 3), faces.shape=(2133, 3))>,
 <trimesh.Trimesh(vertices.shape=(955, 3), faces.shape=(1902, 3))>,
 <trimesh.Trimesh(vertices.shape=(416, 3), faces.shape=(832, 3))>,
 <trimesh.Trimesh(vertices.shape=(315, 3), faces.shape=(630, 3))>,
 <trimesh.Trimesh(vertices.shape=(292, 3), faces.shape=(428, 3))>,
 <trimesh.Trimesh(vertices.shape=(292, 3), faces.shape=(580, 3))>,
 <trimesh.Trimesh(vertices.shape=(272, 3), faces.shape=(527, 3))>,
 <trimesh.Trimesh(vertices.shape=(270, 3), faces.shape=(468, 3))>,
 <trimesh.Trimesh(vertices.shape=(270, 3), faces.shape=(540, 3))>,
 <trimesh.Trimesh(vertices.shape=(209, 3), faces.shape=(414, 3))>,
 <trimesh.Trimesh(vertices.shape=(198, 3), faces.

In [86]:
ret_path = neuron_list[1].save_compressed_neuron("./",
                                      export_mesh=True,
                                     return_file_path=True,
                                     )

Saving Neuorn in suppress_output mode...please wait
Saved File at location: 864691135538151026_0_25_soma_1_split


In [87]:
import neuron_utils as nru
curr_neuron_obj = nru.decompress_neuron("864691135538151026_0_25_soma_1_split",
                     "864691135538151026_0_25_soma_1_split")

Decompressing Neuron in minimal output mode...please wait


IndexError: index 1821636 is out of bounds for axis 0 with size 1512112

In [ ]:
nviz.plot_objects()

In [71]:
nviz.plot_objects(miss_mesh,
                 main_mesh_color="red",
                  show_at_end=False,
                 append_figure=True,
                  
                )

In [63]:
orig_neuron_obj_path = (minnie.Decomposition & dict(segment_id=segment_id)).fetch1("decomposition")
orig_neuron_obj = du.filepath_to_neuron_obj(orig_neuron_obj_path)

Decompressing Neuron in minimal output mode...please wait


In [64]:
nviz.visualize_neuron_lite(orig_neuron_obj)


 Working on visualization type: mesh


In [67]:
orig_neuron_obj.n_somas

5

In [36]:
axon_mesh_filtered_idx = tu.filter_meshes_by_containing_coordinates(diff_meshes,
                                              nullifying_points=limb_obj.current_touching_soma_vertices,
                                               method="distance",
                                               distance_threshold = 0,
                                              filter_away=False,
                                            return_indices=True,
                                                                   verbose=True)
axon_mesh_filtered_idx

Submesh 0 (<trimesh.Trimesh(vertices.shape=(206, 3), faces.shape=(339, 3))>) distances = [5027.69269248    0.          112.45554677 5496.32827986 5081.5892209
 5173.18979837 4551.04287938 1000.97253209 5631.74653549    0.
  360.25853217 1113.90504084 5165.81753065    0.            0.
 5140.93252728    0.            0.         5064.64320658 1020.53956317
  385.20467287 2659.04939593 1098.46855212  277.24582954  133.8759127
 5003.44788721 5112.8328987     0.         5129.04896058 5774.80256719
 4668.13787821  407.03076051 5058.67865752  878.67166223  909.95584508
 4264.17115158    0.          640.77371981 4303.13222665  576.4120141
 1185.13238079 5057.32658724  926.78085867    0.         5047.471149
    0.         5051.09655026 5570.33618824  662.46184041 5188.84914119
 5225.33120099 5102.99343131 1183.64563954 5153.09579282    0.
    0.          294.26588317  427.30569853 5038.71485698 5035.02297512
 2535.14907648 5146.66321125 4986.388609    718.5684101  3643.07946112
  790.85903295 50

[0]

In [34]:
diff_meshes

array([<trimesh.Trimesh(vertices.shape=(206, 3), faces.shape=(339, 3))>],
      dtype=object)

In [21]:
import preprocessing_vp2 as pre
pre.high_fidelity_axon_decomposition(neuron_obj)

KeyError: None

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

# BBox function

In [ ]:
"""
Purpose: To test whether a certain number of points line within a bounding box 

"""

# Need a table to store the fully axon processed neurons

In [5]:
minnie.AutoProofreadVersion.describe()

proof_version        : tinyint unsigned             # key by which to lookup the decomposition process version
---
description          : varchar(256)                 # new parts of the iteration of the decomposition process



'proof_version        : tinyint unsigned             # key by which to lookup the decomposition process version\n---\ndescription          : varchar(256)                 # new parts of the iteration of the decomposition process\n'

# Testing Populating the Axon Decomposition Table

In [19]:
verbose = True

In [78]:
curr_table = (minnie.Decomposition() & "n_limbs = 10" & "n_somas=2")
curr_table

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    multiplicity   decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time      
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+
86469113488477 0              0.25           30.00     0              0         1              =BLOB=     385614         805879      0              1              1              1              2           10          106            51             3416069.919442 1568051.599638 22918.888      186.605        186.605        506.188        456.498        1063         0.000311176300 10.02830188679 2126475.354    56             0.000499888229 18.982         207947661950.8 109383813.7833 60873.36233000 97789.82933410 3713351106.265 1702.3648     
86469113491742 0              0.25           30.00     5              0         1              =BLOB=     654706         1323616     0              1              1              1              2           10          185            96             5033741.307436 2332008.177201 16644.122      225.065        222.719        440.921        420.612        1887         0.000374870277 10.2           3783813.289    125            0.000498703254 15.096         393234081987.2 140608340.1661 78119.64460832 103925.3398497 3145872655.897 6760.2047     
86469113493998 0              0.25           30.00     0              0         1              =BLOB=     850056         1712989     0              1              1              1              2           10          352            186            9694467.839110 4280376.136482 17357.902      67.644         67.644         405.872        330.68         2543         0.000262314553 7.224431818181 4105788.211    79             0.000619369502 32.19          359654355154.7 73883426.51840 37098.92705030 87596.90872294 4552586774.110 5115.6062     
86469113494744 0              0.25           30.00     0              0         1              =BLOB=     810849         1642418     0              1              0              1              2           10          152            65             6424737.076339 2598178.480417 34119.672      378.327        311.13         692.705        646.108        3770         0.000586794440 24.80263157894 5973018.884    132            0.000631171619 28.561         650289383149.8 99074108.83834 101216.4973325 108871.1413405 4926434720.831 4219.6827     
86469113498840 0              0.25           30.00     0              0         1              =BLOB=     1070648        2153386     0              2              1              1              2           10          264            123            12010311.91283 3848738.203157 25031.814      165.305        162.207        494.164        449.113        3147         0.000262024835 11.92045454545 7919810.365    151            0.000397357999 20.841         392357752255.1 70381231.51502 32668.40654121 49541.30644202 2598395710.299 3971.4798     
86469113498841 0              0.25           30.00     0              0         1              =BLOB=     804636         1650151     0              2              1              1      

In [79]:
key = (curr_table & dict(segment_id = 864691135012573174)).proj().fetch1()
key

{'segment_id': 864691135012573174,
 'decimation_version': 0,
 'decimation_ratio': Decimal('0.25'),
 'ver': Decimal('30.00'),
 'process_version': 5,
 'index': 0}

In [80]:
verbose = True
# 1) Pull Down All of the Neurons
segment_id = key["segment_id"]

whole_pass_time = time.time()

#1) Pull Down all the Neuron Objects associated with a segment_id

neuron_objs,neuron_split_idxs = du.decomposition_with_spine_recalculation(segment_id)

if verbose:
    print(f"Number of Neurons found ={len(neuron_objs)}")
    
#For each neuron:
#for split_index,neuron_obj_pre_split in zip(neuron_split_idxs,neuron_objs):


Decompressing Neuron in minimal output mode...please wait
Dont need spine recalculation
Decompressing Neuron in minimal output mode...please wait
Dont need spine recalculation
Number of Neurons found = 2
Number of Neurons found =2


In [83]:
split_index = 1
neuron_obj = neuron_objs[split_index]

#Run the Axon Decomposition
neuron_obj_with_web = au.complete_axon_processing(neuron_obj,
                                     verbose=True)


Part 1: Axon like branchese 
{'L0': array([ 1,  4,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]), 'L4': array([0, 1, 2]), 'L5': array([ 2, 23, 31, 40, 41, 42, 43, 44, 45, 46, 47])}
Limb L0 soma angle: 85.8 
Limb L1 soma angle: 92.04 
Limb L2 soma angle: 111.81 
Limb L3 soma angle: 130.51 
Limb L4 soma angle: 126.37 
Limb L5 soma angle: 36.0 

Part 2: possible_axon_limbs = [0, 1, 2, 3, 4]

Phase 2: Working on Limb L0
nodes_to_eliminate = [5]

Phase 2: Working on Limb L1
nodes_to_eliminate = [4]

Phase 2: Working on Limb L2
nodes_to_eliminate = [0]

Phase 2: Working on Limb L3
nodes_to_eliminate = []

Phase 2: Working on Limb L4
nodes_to_eliminate = []

----Working on Limb L0-----
No endpoints were eliminated so don't need to add back any candidates

----Working on Limb L1-----
No endpoints were eliminated so don't need to add back any candidates

----Working on Limb L2-----
No endpoints were eliminated so don't need to a

100%|██████████| 1/1 [00:00<00:00,  8.19it/s]

root_curr = [1101932.   905051.1  941031.9]
Time for preparing soma vertices and root: 0.0007224082946777344
invalidation_d = 1500
smooth_neighborhood = 0
cc_vertex_thresh = 10


meshparty_segment_size = 100
Time for 1st pass MP skeletonization: 0.391834020614624
branches_touching_root = [8]
combining close nodes
combine_threshold = 1300
length of Graph = 2916
After combining close endpoints max(kept_branches_idx) = 16, len(kept_branches_idx) = 16
empty_indices % = 0.0
 conflict_indices % = 0.018318373328448434
AFTER face_lookup_resolved_test
Decomposing first pass: 1.7792327404022217
Only Using MeshParty Skeletonization and Mesh Correspondence
Another print
Divinding into MP and MAP pieces: 4.00543212890625e-05
Total time for MAP sublimb processing 9.059906005859375e-06
---- Working on MP Decomposition #0 ----
Using Quicker soma_to_piece_touching_vertices because no MAP and only one sublimb_mesh piece 
MP filtering soma verts: 0.00012922286987304688
Fixing Possible Soma Extension Branch for Sublimb 0
Total time for mesh KDTree = 0.0019714832305908203
sbv[0].reshape(-1,3) = [[1101932.   905051.1  941031.9]]
closest_sk_pt_coord BEFORE = [1101265.01652063  904696

In [163]:
neuron_obj_with_web = n_obj

In [164]:
# Just trying to filter neuron to se what it would look like
filter_list = pru.v4_exc_filters()
inh_exc_class="excitatory"
perform_axon_classification = False
plot_limb_branch_filter_with_disconnect_effect = True

filtered_neuron,filtering_info = pru.proofread_neuron_class_predetermined(neuron_obj_with_web,
        inh_exc_class=inh_exc_class,
        perform_axon_classification=False,

        plot_limb_branch_filter_with_disconnect_effect = plot_limb_branch_filter_with_disconnect_effect,


        plot_final_filtered_neuron = False,

        #arguments for the axon high fidelity:
        plot_new_axon_limb_correspondence = False,
        plot_new_limb_object = False,
        plot_final_revised_axon_branch = False,

        verbose = False,
        verbose_outline = verbose,
        filter_list = filter_list,
        high_fidelity_axon_on_excitatory = perform_axon_classification,
                                                                             )


--- Working on filter 0:
function = axon_on_dendrite_merges
function __name__ = filter_away_axon_on_dendrite_merges
function arguments = {'use_pre_existing_axon_labels': True}



--- Working on filter 1:
function = high_degree_branching
function __name__ = filter_away_high_degree_branching
function arguments = {'offset': 1500, 'comparison_distance': 2000, 'worst_case_match_threshold': 65, 'width_diff_max': None, 'width_diff_perc': 60, 'match_threshold': 45, 'angle_buffer': 15, 'max_degree_to_resolve': 6, 'match_method': 'best_match'}




 ----- Working on coordinate [491775.73454331 796768.97696681 963426.61025879]--------
coordinate [491775.73454331 796768.97696681 963426.61025879] had error branches [7 9]--------


 ----- Working on coordinate [517441.17096419 784951.98283524 881829.82393316]--------
coordinate [517441.17096419 784951.98283524 881829.82393316] had error branches [21 23 24]--------


 ----- Working on coordinate [525906.87270703 674386.73804382 840716.1500395 ]------


--- Working on filter 2:
function = axon_webbing_t_merges
function __name__ = filter_away_webbing_t_merges
function arguments = {'child_width_maximum': 75, 'parent_width_maximum': 75, 'axon_only': True, 'error_if_web_is_none': True, 'web_size_threshold': 120, 'web_size_type': 'ray_trace_median', 'web_above_threshold': True}


limb_branch_dict_to_cancel = {}

--- Working on filter 3:
function = thick_t_merge
function __name__ = filter_away_thick_t_merge
function arguments = {}


limb_branch_dict_to_cancel = {}

--- Working on filter 4:
function = double_back_and_width_change
function __name__ = filter_away_large_double_back_or_width_changes
function arguments = {'perform_double_back_errors': True, 'skip_double_back_errors_for_axon': False, 'width_jump_threshold': 250, 'running_width_jump_method': True, 'double_back_axon_like_threshold': 145, 'double_back_threshold': 120, 'allow_axon_double_back_angle_with_top': None, 'allow_axon_double_back_angle_with_top_width_min': 140, 'skeletal_len


--- Working on filter 5:
function = axon_fork_divergence
function __name__ = filter_away_small_axon_fork_divergence
function arguments = {'divergence_threshold_mean': 165}


limb_branch_dict_to_cancel = {}



 ---- Total time for applying filter: 59.70293164253235 -----


In [86]:
nviz.plot_original_vs_proofread(original = neuron_obj,
    proofread = filtered_neuron,
    original_color = "red",
    proofread_color = "blue",
    mesh_alpha = 0.3,
    plot_mesh= True,
    plot_skeleton = True)

In [89]:
filtered_neuron.description

'0_25_soma_1_split_axon_v1'

In [127]:
minnie.Decomposition() & "n_somas = 2"

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    multiplicity   decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time     
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +-----------+
86469113476514 0              0.25           30.00     0              0         1              =BLOB=     44570          90882       0              1              1              1              2           1           1              1              28585.10573216 28585.10573216 28585.106      1726.047       1726.047       1726.047       1726.047       4            0.000139933013 4.0            28585.106      1              0.000139933012 4.0            174766472.2566 13946453.78167 6113.899801322 6113.899744036 174766472.2566 89.0604      
86469113476896 0              0.25           30.00     5              0         1              =BLOB=     81637          164711      0              1              1              1              2           2           5              4              61206.67545077 40401.85629631 4713.508       108.165        108.165        1174.845       1135.231       2            3.267617437592 0.4            6413.497       2              0.000311842353 1.0            806371663.6001 403185831.8000 13174.57054580 125730.4187715 403185831.8000 58.3114      
86469113483187 0              0.25           30.00     0              0         1              =BLOB=     141431         288006      0              1              0              1              2           3           5              3              167837.6994974 105050.8663521 42893.926      114.293        114.293        1035.029       1035.029       0            0.0            0.0            19892.907      1              0.0            0.0            0.0            0.0            0.0            0.0            0.0            126.6019     
86469113487493 0              0.25           30.00     0              0         1              =BLOB=     64451          129722      0              2              2              1              2           3           7              3              69751.43119438 56515.80323426 5610.567       124.571        124.571        1568.841       1568.841       4            5.734649356301 0.571428571428 41954.196      3              9.534207257839 1.333          123117238.4626 18270225.27590 1765.085480748 2934.563171289 41039079.48754 143.5662     
86469113488477 0              0.25           30.00     0              0         1              =BLOB=     385614         805879      0              1              1              1              2           10          106            51             3416069.919442 1568051.599638 22918.888      186.605        186.605        506.188        456.498        1063         0.000311176300 10.02830188679 2126475.354    56             0.000499888229 18.982         207947661950.8 109383813.7833 60873.36233000 97789.82933410 3713351106.265 1702.3648    
86469113488478 0              0.25           30.00     0              0         1              =BLOB=     368083         762245      0              3              3              1             

In [168]:
minnie.DecompositionAxon()

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    *split_index   *axon_version  decomposit axon_length    run_time    
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +------------+ +--------+ +------------+ +----------+
86469113438403 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.26        
86469113440905 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.38        
86469113442860 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.13        
86469113448829 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.31        
86469113468456 0              0.25           30.00     5              0         0              4              =BLOB=     0.0            0.15        
86469113474398 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.61        
86469113475133 0              0.25           30.00     5              0         0              4              =BLOB=     0.0            0.46        
86469113476225 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.23        
86469113479207 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.15        
86469113480086 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.25        
86469113480649 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            2.77        
86469113481294 0              0.25           30.00     0              0         0              4              =BLOB=     0.0            0.52        
   ...
 (Total: 20569)

In [154]:
minnie.DecompositionAxon() & "axon_length>1000" & "segment_id=864691134917425418"

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    *split_index   *axon_version  decomposit axon_length    run_time    
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +------------+ +--------+ +------------+ +----------+
86469113491742 0              0.25           30.00     5              0         0              4              =BLOB=     1279.414773205 181.57      
 (Total: 1)

In [155]:
n_obj = du.decomposition_with_spine_recalculation(864691134917425418,0)

**Using table __decomposition_axon for table_to_neuron_objs**
Decompressing Neuron in minimal output mode...please wait
Dont need spine recalculation
Number of Neurons found = 1


In [157]:
orig_seg_mesh = du.fetch_segment_id_mesh(n_obj.segment_id)

In [159]:
orig_seg_mesh

<trimesh.Trimesh(vertices.shape=(203816, 3), faces.shape=(421561, 3))>

In [165]:
nviz.plot_original_vs_proofread(original = n_obj,
    proofread = filtered_neuron,
    original_color = "red",
    proofread_color = "blue",
    mesh_alpha = 0.3,
    plot_mesh= True,
    plot_skeleton = False)

original = <trimesh.Trimesh(vertices.shape=(203816, 3), faces.shape=(421561, 3))>


In [94]:
x = None
try:
    du.decomposition_with_spine_recalculation(864691136231316382,0)
except Exception as e:
    x = e.args[0]
    print(e)

**Using table __decomposition for table_to_neuron_objs**
'/mnt/dj-stor01/platinum/minnie65/02/decomposition/864691136231316382_0_25.pbz2' downloaded but did not pass checksum'


In [119]:
import datajoint_utils as du
du.datajoint_filepath_error_to_filepath(error = x)

'/mnt/dj-stor01/platinum/minnie65/02/decomposition/864691136231316382_0_25.pbz2'

In [59]:
save_time = time.time()
ret_file_path = filtered_neuron.save_compressed_neuron(
                                #output_folder=str(du.get_decomposition_path()),
                                output_folder = "./",
                                #file_name=f"{neuron_obj_with_web.segment_id}_validation_full_axon",
                                  return_file_path=True,
                                 export_mesh=False,
                                 suppress_output=False)

ret_file_path_str = str(ret_file_path.absolute()) + ".pbz2"
print(f"ret_file_path_str = {ret_file_path_str}")
print(f"Save time = {time.time() - save_time}")

Total time for soma meshes compression = 0.5879535675048828
Total time for insignificant_limbs,inside_pieces,non_soma_touching_meshes,not_processed_soma_containing_meshes compression = 2.09808349609375e-05
Total time for limb_meshes compression = 1.5303874015808105
    Starting Limb Correspondence Compression
Total time for new_limb_correspondence compression = 9.438011646270752
Total time for compression = 39.20625686645508
Saved object at /neuron_mesh_tools/Auto_Proofreading/Preprocessing_Pipeline/v4/864691135081713143_0_25_soma_0_split_axon_v1.pbz2
File size is 1.96837 MB


---Finished outputing neuron at location: /neuron_mesh_tools/Auto_Proofreading/Preprocessing_Pipeline/v4/864691135081713143_0_25_soma_0_split_axon_v1---
Saved File at location: 864691135081713143_0_25_soma_0_split_axon_v1
ret_file_path_str = /neuron_mesh_tools/Auto_Proofreading/Preprocessing_Pipeline/v4/864691135081713143_0_25_soma_0_split_axon_v1.pbz2
Save time = 40.20885133743286


In [62]:
n_dict = dict(key,
              split_index = split_index,
              axon_version = au.axon_version,
             decomposition=ret_file_path_str,
             axon_length=filtered_neuron.axon_length,
              run_time = np.round(time.time() - whole_pass_time,2)
             )

n_dict

{'segment_id': 864691135081713143,
 'decimation_version': 0,
 'decimation_ratio': Decimal('0.25'),
 'ver': Decimal('30.00'),
 'process_version': 5,
 'index': 0,
 'split_index': 0,
 'axon_version': 1,
 'decomposition': '/neuron_mesh_tools/Auto_Proofreading/Preprocessing_Pipeline/v4/864691135081713143_0_25_soma_0_split_axon_v1.pbz2',
 'axon_length': 397.14731961081964}

# Fetching an example neuron

In [69]:
du.decomposition_with_spine_recalculation?

In [68]:
table_to_neuron_objs(table,
    return_one=False,
    return_split_index=False)

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    multiplicity   decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time     
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +-----------+
86469113476514 0              0.25           30.00     0              0         1              =BLOB=     44570          90882       0              1              1              1              2           1           1              1              28585.10573216 28585.10573216 28585.106      1726.047       1726.047       1726.047       1726.047       4            0.000139933013 4.0            28585.106      1              0.000139933012 4.0            174766472.2566 13946453.78167 6113.899801322 6113.899744036 174766472.2566 89.0604      
86469113476896 0              0.25           30.00     5              0         1              =BLOB=     81637          164711      0              1              1              1              2           2           5              4              61206.67545077 40401.85629631 4713.508       108.165        108.165        1174.845       1135.231       2            3.267617437592 0.4            6413.497       2              0.000311842353 1.0            806371663.6001 403185831.8000 13174.57054580 125730.4187715 403185831.8000 58.3114      
86469113483187 0              0.25           30.00     0              0         1              =BLOB=     141431         288006      0              1              0              1              2           3           5              3              167837.6994974 105050.8663521 42893.926      114.293        114.293        1035.029       1035.029       0            0.0            0.0            19892.907      1              0.0            0.0            0.0            0.0            0.0            0.0            0.0            126.6019     
86469113487493 0              0.25           30.00     0              0         1              =BLOB=     64451          129722      0              2              2              1              2           3           7              3              69751.43119438 56515.80323426 5610.567       124.571        124.571        1568.841       1568.841       4            5.734649356301 0.571428571428 41954.196      3              9.534207257839 1.333          123117238.4626 18270225.27590 1765.085480748 2934.563171289 41039079.48754 143.5662     
86469113488477 0              0.25           30.00     0              0         1              =BLOB=     385614         805879      0              1              1              1              2           10          106            51             3416069.919442 1568051.599638 22918.888      186.605        186.605        506.188        456.498        1063         0.000311176300 10.02830188679 2126475.354    56             0.000499888229 18.982         207947661950.8 109383813.7833 60873.36233000 97789.82933410 3713351106.265 1702.3648    
86469113488478 0              0.25           30.00     0              0         1              =BLOB=     368083         762245      0              3              3              1             

In [70]:
du.table_to_neuron_objs

<function datajoint_utils.table_to_neuron_objs(table, return_one=False, return_split_index=False)>

In [72]:
curr_table = minnie.DecompositionSplit() & "segment_id = 864691134917398026"
curr_table

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    *split_index   *split_version multiplicity   n_splits     split_success  n_error_limbs_ n_same_soma_li n_multi_soma_l error_imbs_can error_imbs_can split_resu decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     max_soma_n_fac max_soma_volum n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time     
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +--------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +------------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +-----------+
86469113491739 0              0.25           30.00     0              0         0              1              2              4            0              0              0              0              0.0            0.0            =BLOB=     =BLOB=     306127         610325      0              0              0              0              1           30727          581            8           66             24             2903250.063713 988989.0932655 27202.235      284.14         250.233        428.627        407.311        1400         0.000482218193 21.21212121212 2269968.166    48             0.000616748737 29.167         305731039439.9 126978331.4812 105306.4781642 134685.1660826 6369396654.998 2102.3057    
86469113491739 0              0.25           30.00     0              0         1              1              2              4            0              0              0              0              0.0            0.0            =BLOB=     =BLOB=     364589         727008      0              0              0              0              1           40244          656            12          133            64             4527732.153995 2540786.010099 18574.088      129.661        129.661        328.214        316.796        657          0.000145105756 4.939849624060 2194997.257    58             0.000299317002 11.328         57952932580.05 49163520.60981 12799.54966614 26402.28018292 999188492.7596 3151.1663    
 (Total: 2)

AttributeError: module 'minnie' has no attribute 'DecompositionAxon'

In [ ]:
"""
Need a function that will go and get the 


"""
