In [ ]:
"""
To Make sure the Best Axon method works and also
to see if can decompose the axon any better 
(especially if can help with crosses and parts that aren't skeletonized             )

"""

In [1]:
%load_ext autoreload
%autoreload 2

In [128]:
from os import sys
sys.path.append("/meshAfterParty/")
sys.path.append("/meshAfterParty/meshAfterParty/")

In [3]:
import datajoint_utils as du
minnie,schema = du.configure_minnie_vm()

INFO - 2021-02-25 07:41:21,639 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-02-25 07:41:21,641 - settings - Setting database.user to celiib
INFO - 2021-02-25 07:41:21,642 - settings - Setting database.password to newceliipass
INFO - 2021-02-25 07:41:21,648 - settings - Setting stores to {'minnie65': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65', 'stage': '/mnt/dj-stor01/platinum/minnie65'}, 'meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/meshes'}, 'decimated_meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes'}, 'skeletons': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/skeletons'}}
INFO - 2021-02-25 07:41:21,649 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-25 07:41:21,664 - connection - Connect

Connecting celiib@at-database.ad.bcm.edu:3306


INFO - 2021-02-25 07:41:22,071 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-25 07:41:22,111 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-25 07:41:22,514 - settings - Setting enable_python_native_blobs to True


In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import networkx_utils as xu
import datajoint as dj
import neuron_visualizations as nviz
import neuron
import neuron_utils as nru
import proofreading_utils as pru
import classification_utils as clu
import system_utils as su
from importlib import reload
import trimesh_utils as tu

# Getting a more high fidelity axon skeleton

In [51]:
minnie.AutoProofreadValidationNeurons() & "axon_length>300"

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    *split_index   *proof_version multiplicity   cell_type_pred spine_category n_axons     n_apicals     axon_length    axon_area      nucleus_id     nuclei_distanc n_nuclei_in_ra n_nuclei_in_bb soma_x     soma_y     soma_z     max_soma_n_fac max_soma_volum n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p axon_angle_max spine_density_ n_branches_pro skeletal_lengt n_branches_in_ skeletal_lengt run_time    
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +------------+ +------------+ +------------+ +------------+ +---------+ +-----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +--------+ +--------+ +--------+ +------------+ +------------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+
86469113511316 0              0.25           30.00     5              0         0              2              1              excitatory     densely_spined 1           1             1521.448057552 1676.457575274 335175         917.6          1              1              198908     188769     19783      36542          685            372432         742758      0              0              0              0              1           8           94             38             4284590.860333 1521448.057552 31845.711      255.378        240.489        462.705        454.05         1335         0.000311581675 14.20212765957 3351748.869    67             0.000398299530 19.925         254408283170.8 122787553.9656 59377.49751701 75903.14582452 3797138554.789 174.7666830041 0.000511396810 0              2183268.440706 76             3078121.422989 176.6521    
86469113521263 0              0.25           30.00     5              0         0              2              1              excitatory     densely_spined 1           1             1579.307348836 1546.271016207 301095         1186.5         1              1              185376     185168     21263      42977          973            514749         1026365     0              0              0              0              1           7           123            51             5629794.719025 1579307.348836 32225.234      255.617        245.74         487.981        486.428        1912         0.000339621619 15.54471544715 4330849.568    79             0.000441483817 24.203         411985568239.0 139349499.0567 73179.50099438 95128.11788319 5215007192.899 169.6130240301 0.000510818725 0              3380591.459978 96             4360537.807526 209.6809    
86469113523310 0              0.25           30.00     5              0         0              2              1              excitatory     densely_spined 1           1             418.2671099001 389.1880666261 262773         310.89         1              1              168040     161943     21497      23189          451            142282         283709      0              0              0              0              1           4           39             16             1640418.213990 520068.6845883 27441.049      260.686        238.521        431.65

In [5]:
multi_axon_segs,multi_axon_splits = (minnie.AutoProofreadNeurons2() & "cell_type_predicted='excitatory'"
 & "n_axons>1").fetch("segment_id","split_index")

In [62]:
segment_id,split_index = 864691135426651890,0 #long axon good for proofreading
#segment_id, split_index = 864691135446640468,0 #comes off the side of dendrite
segment_id,split_index = 864691135699269154,0
segment_id,split_index = 864691135589907979,0
segment_id, split_index = 864691135735426708,0

In [63]:
validation = True

In [64]:
du.plot_proofread_neuron(segment_id,
                        split_index=split_index,
                        plot_errored_faces=True,
                        plot_synapses=True,
                        plot_nuclei=True,
                        plot_axon=True,
                        validation=True)

Synapsse Results:
Total Number of Synapses = 3713
n_valid_syn_centers_presyn = 67
n_errored_syn_centers_presyn = 193
n_valid_syn_centers_postsyn = 2830
n_errored_syn_centers_postsyn = 623
Including axon mesh


In [65]:
neuron_obj = du.decomposition_with_spine_recalculation(segment_id,
                                                      split_index=split_index)

Decompressing Neuron in minimal output mode...please wait
Pulled from Table Decomposition so setting split_index = 0
Dont need spine recalculation
Number of Neurons found = 1


In [66]:
if type(neuron_obj) == tuple:
    neuron_obj = neuron_obj[0][split_index]

In [67]:
neuron_obj.segment_id

864691135735426708

In [68]:
nviz.visualize_neuron(neuron_obj,
                     limb_branch_dict="all")


 Working on visualization type: mesh

 Working on visualization type: skeleton


In [69]:
clu.axon_classification(neuron_obj,
                        plot_candidates=True,
                       best_axon=True,
                       plot_axons=True)


Part 1: Axon like branchese 
{'L0': array([ 4,  6, 17, 23, 26, 27]), 'L1': array([ 5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]), 'L2': array([0, 1, 2]), 'L6': array([0, 3, 4, 6, 7, 8])}
Limb L0 soma angle: 16.5 
Limb L1 soma angle: 165.42 
Limb L2 soma angle: 95.54 
Limb L3 soma angle: 95.59 
Limb L4 soma angle: 136.45 
Limb L5 soma angle: 119.1 
Limb L6 soma angle: 87.88 

Part 2: possible_axon_limbs = [1, 2, 3, 4, 5, 6]

Phase 2: Working on Limb L1
nodes_to_eliminate = []

Phase 2: Working on Limb L2
nodes_to_eliminate = [5 7]

Phase 2: Working on Limb L3
nodes_to_eliminate = [4]

Phase 2: Working on Limb L4
nodes_to_eliminate = [2]

Phase 2: Working on Limb L5
nodes_to_eliminate = []

Phase 2: Working on Limb L6
nodes_to_eliminate = []

----Working on Limb L1-----
No nodes were eliminated so don't need to add back any candi

Final Candidates

Limb 1
Candidate 0 (cyan): array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

Limb 2
Candidate 0 (cadetblue): array([10, 11,  6])
Candidate 1 (gold): array([8])
Candidate 2 (brown): array([ 0,  1,  2,  3,  4,  9, 12])

Limb 3
Candidate 0 (magenta): array([0])
Candidate 1 (blue): array([1, 2, 3])

Limb 4
Candidate 0 (cadetblue): array([0, 1, 3])
Candidate 1 (olive): array([4])

Limb 5
Candidate 0 (gold): array([0, 1, 2])

Limb 6
Candidate 0 (tan): array([0, 1, 2, 3, 4, 5, 6, 7, 8])
Part 3: axon_subgraph_candidates = {1: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53]], 2: [[10, 11, 6], [8], [0, 1, 2, 3, 4, 9, 12]], 3: [[

({'L1': array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
         26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
         39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
         52., 53.])},
 {'L0': array([ 4, 17, 23, 26, 27]),
  'L2': array([0, 1, 2]),
  'L6': array([0, 3, 4, 6, 7, 8])})

# Erasing the starting branch from the axon so can test if axon is not starter

In [70]:
# axon_limb_branch_dict= neuron_obj.axon_limb_branch_dict

# axon_limb_name = neuron_obj.axon_limb_name
# curr_limb = neuron_obj[axon_limb_name]
# axon_branches = axon_limb_branch_dict[axon_limb_name]
# curr_limb.current_starting_node,neuron_obj.axon_starting_branch

# neuron_obj[axon_limb_name][neuron_obj.axon_starting_branch].labels = []

In [71]:
nviz.plot_axon(neuron_obj)


 Working on visualization type: mesh


# The whole process of replacing the axon with higher fidelity

In [85]:
new_neuron_obj = pru.refine_axon_for_high_fidelity_skeleton(neuron_obj=neuron_obj,
    plot_new_axon_limb_correspondence = True,
    plot_new_limb_object = True,
    plot_final_revised_axon_branch=True,
     verbose = True,)



Starting axon branch was the starting node so using border vertices and NOT computing upstream branch
upstream_node_to_axon_starting_branch = None
root_curr = [1348840.   541246.2  817276.4]
Time for preparing soma vertices and root: 0.001306295394897461
invalidation_d = 2000
cc_vertex_thresh = 10


  0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:06<00:00,  6.02s/it]

meshparty_segment_size = 100
Time for 1st pass MP skeletonization: 7.221849203109741
branches_touching_root = [37]
combining close nodes
combine_threshold = 1300
length of Graph = 29071
Working on path [1555. 1562. 1569. 1578. 1582. 1584. 1588. 1592. 1594. 1597. 1599. 1600.]
path_degrees = [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3]
Working on path [3428. 3431. 3435. 3438. 3441. 3444. 3446. 3449. 3451. 3452. 3455.]
path_degrees = [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3]
Working on path [3776. 3779. 3786. 3797. 3805. 3813. 3819.]
path_degrees = [3, 2, 2, 2, 2, 2, 3]
Working on path [4007. 4013. 4015. 4017. 4019. 4021. 4025. 4037.]
path_degrees = [3, 2, 2, 2, 2, 2, 2, 3]
Working on path [4841. 4845. 4848. 4851. 4854. 4856. 4862.]
path_degrees = [3, 2, 2, 2, 2, 2, 3]
Working on path [12243. 12255. 12267. 12280. 12291. 12307. 12319. 12336. 12355. 12374.
 12398. 12423. 12428.]
path_degrees = [3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3]
Working on path [13403. 13422. 13440. 13463. 13473. 13480. 13486. 13494.]



AFTER face_lookup_resolved_test



Decomposing first pass: 19.22344970703125
Only Using MeshParty Skeletonization and Mesh Correspondence
Another print
Divinding into MP and MAP pieces: 2.47955322265625e-05
Total time for MAP sublimb processing 4.291534423828125e-06
---- Working on MP Decomposition #0 ----
Using Quicker soma_to_piece_touching_vertices because no MAP and only one sublimb_mesh piece 
MP filtering soma verts: 4.172325134277344e-05
Fixing Possible Soma Extension Branch for Sublimb 0
Total time for mesh KDTree = 0.04090237617492676
sbv[0].reshape(-1,3) = [[1348840.   541246.2  817276.4]]
closest_sk_pt_coord BEFORE = [1348964.14024777  541728.93462084  817404.77605041]
current_skeleton.shape = (200, 2, 3)
node_for_stitch = 0: [1348964.14024777  541728.93462084  817404.77605041]
node_for_stitch AFTER = 0: [1348964.14024777  541728.93462084  817404.77605041]
possible_node_loc = [  0 194]
possible_node_loc AFTER = [  0 194]
curr_shortest_path = [0]
Current stitch point was a branch or endpoint
change_status for


Removed 26 skeletal branches



250708 250709
For marked faces: None
empty_indices % = 0.00035499323917370337
 conflict_indices % = 0.0



AFTER face_lookup_resolved_test



Upstream node was None so don't have to adjust
axon_limb_name= L1
Limb starting node = 45
Axon starting node = 45
axon_branches = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]
Using Axon Starting Info
Leftover Nodes After Axon Deletion = []
New Node names = []
Leftover Nodes Mapping = {}
concept_network_dict = {0: [<networkx_utils.GraphOrderedEdges object at 0x7efdeb5cf1d0>]}
New Limb Object


Working on limb L1 branch 132
Working on limb L1 branch 123
Working on limb L1 branch 134
Working on limb L1 branch 99
Working on limb L1 branch 124
Working on limb L1 branch 127
Working on limb L1 branch 133
Working on limb L1 branch 90
Working on limb L1 branch 100
Working on limb L1 branch 138
Working on limb L1 branch 140
Working on limb L1 branch 141
Working on limb L1 branch 71
Working on limb L1 branch 91
Working on limb L1 branch 106
Working on limb L1 branch 113
Working on limb L1 branch 52
Working on limb L1 branch 70
Working on limb L1 branch 111
Working on limb L1 branch 116
Working on limb L1 branch 87
Working on limb L1 branch 104
Working on limb L1 branch 97
Working on limb L1 branch 114
Working on limb L1 branch 73
Working on limb L1 branch 74
Working on limb L1 branch 50
Working on limb L1 branch 105
Working on limb L1 branch 85
Working on limb L1 branch 92
Working on limb L1 branch 96
Working on limb L1 branch 98
Working on limb L1 branch 119
Working on limb L1 branch



---------Working on soma_idx = 0, soma_group_idx 0, endpt = [1348964.14024777  541728.93462084  817404.77605041]---------
Starting_edge inside branches_to_conept = [[1348964.14024777  541728.93462084  817404.77605041]
 [1351517.84565173  560608.21852905  821071.11405119]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [123]
printing out current edge:
[[1348964.14024777  541728.93462084  817404.77605041]
 [1351517.84565173  560608.21852905  821071.11405119]]
edge_endpoints_to_process was empty so exiting loop after 163 iterations
starting_node in concept map (that should match the starting edge) = 132
Total time for branches to concept conversion = 1.3947954177856445

Done generating concept network 



 Working on visualization type: mesh

 Working on visualization type: skeleton


In [86]:
import neuron_searching as ns
ns.query_neuron_by_labels(new_neuron_obj,matching_labels=["axon"])

{'L1': array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162])}

In [87]:
nviz.plot_axon(new_neuron_obj)


 Working on visualization type: mesh


# Try proofreading the neuron (using new rules for high fidelity)

In [75]:
pru.get_excitatory_high_fidelity_axon_pre_filters()

[{'filter_name': 'dendrite_on_axon_merges',
  'filter_function': <function proofreading_utils.filter_away_dendrite_on_axon_merges(neuron_obj, perform_deepcopy=True, limb_branch_dict_for_search=None, use_pre_existing_axon_labels=False, perform_axon_classification=False, dendritic_merge_on_axon_query=None, dendrite_merge_skeletal_length_min=20000, dendrite_merge_width_min=100, dendritie_spine_density_min=0.00015, plot_limb_branch_filter_away=False, plot_limb_branch_filter_with_disconnect_effect=False, return_error_info=False, plot_final_neuron=False, verbose=False)>,
  'filter_kwargs': {'use_pre_existing_axon_labels': True}}]

In [88]:
plot_limb_branch_filter_with_disconnect_effect = True
verbose = False
verbose_outline = True
o_neuron, filtering_info = pru.apply_proofreading_filters_to_neuron(input_neuron = neuron_obj,
                                            filter_list = pru.get_excitatory_high_fidelity_axon_pre_filters(),
                        plot_limb_branch_filter_with_disconnect_effect=plot_limb_branch_filter_with_disconnect_effect,
                                            plot_limb_branch_filter_away=False,
                                            plot_final_neuron=False,

                                            return_error_info=True,
                                             verbose=verbose,
                                            verbose_outline=verbose_outline
        )


--- Working on filter 0:
function = dendrite_on_axon_merges
function __name__ = filter_away_dendrite_on_axon_merges
function arguments = {'use_pre_existing_axon_labels': True}




Branches Requested to Remove (WITH disconnect effect)

 Working on visualization type: mesh





 ---- Total time for applying filter: 24.853794813156128 -----


In [89]:
filtering_info

{'dendrite_on_axon_merges_neuron': <neuron.Neuron at 0x7efcfbf4dc50>,
 'dendrite_on_axon_merges_time': 24.853686571121216,
 'dendrite_on_axon_merges_error_area': 633.8468374430994,
 'dendrite_on_axon_merges_error_length': 271.456668943723}

In [81]:
new_neuron_obj.axon_limb_branch_dict

{}

In [90]:
nviz.plot_axon(o_neuron)

[autoreload of proofreading_utils failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/usr/local/lib/python3.6/dist-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/usr/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/meshAfterParty/meshAfterParty/proofreading_utils.py", line 3765
    else:
 


 Working on visualization type: mesh


In [94]:
nviz.visualize_neuron_lite(neuron_obj)


 Working on visualization type: mesh


In [126]:
output_dict= pru.proofread_neuron(neuron_obj,
                            plot_limb_branch_filter_with_disconnect_effect=False,
                            plot_final_filtered_neuron=False,
                            verbose=True)

filtered_neuron = output_dict["filtered_neuron"]
cell_type_info = output_dict["cell_type_info"]
filtering_info = output_dict["filtering_info"]

---- Part A: NOT Attempting to split neuron --------

--- Working on Neuron 0 ---


 ------ Part B: Axon Classification ---- 


base_final_widths = [428.64984057 437.9965134 ]
overall_ais_width = 330.8527724540625
ais_width = 433.3231769814422
Axon Classification = 27.649645566940308


 ------ Part C: Inhibitory Excitatory Classification ---- 


spine_category = densely_spined
Did not pass final filters to continuing
Inhibitory Excitatory Classification = 10.288856029510498

 -- Cell Type Classification Results --
inh_exc_class=excitatory
spine_category=densely_spined
axon_angles={1: {0: 167.3683054842977}}
n_axons=1
n_apicals=1
neuron_spine_density=0.0006585676303633324
n_branches_processed=25
skeletal_length_processed=2195870.1855782047
n_branches_in_search_radius=51
skeletal_length_in_search_radius=2683849.2278394564


 ------ Part D: Neuron Filtering ---- 

 


 Using high_fidelity_axon_on_excitatory


---Step 1: Applying Dendrite on Axon Filtering
INSIDE THE NEW EXCITATORY FILTERS

  0%|          | 0/1 [00:00<?, ?it/s]

root_curr = [1348840.   541246.2  817276.4]
Time for preparing soma vertices and root: 0.0018048286437988281
invalidation_d = 2000
cc_vertex_thresh = 10


100%|██████████| 1/1 [00:04<00:00,  4.20s/it]

meshparty_segment_size = 100
Time for 1st pass MP skeletonization: 5.32108736038208
branches_touching_root = [17]
combining close nodes
combine_threshold = 1300
length of Graph = 26007
After combining close endpoints max(kept_branches_idx) = 173, len(kept_branches_idx) = 163
empty_indices % = 0.0
 conflict_indices % = 0.01873853562546661



AFTER face_lookup_resolved_test



Decomposing first pass: 16.856616258621216
Only Using MeshParty Skeletonization and Mesh Correspondence
Another print
Divinding into MP and MAP pieces: 1.8835067749023438e-05
Total time for MAP sublimb processing 5.245208740234375e-06
---- Working on MP Decomposition #0 ----
Using Quicker soma_to_piece_touching_vertices because no MAP and only one sublimb_mesh piece 
MP filtering soma verts: 7.152557373046875e-05
Fixing Possible Soma Extension Branch for Sublimb 0
Total time for mesh KDTree = 0.05797171592712402
sbv[0].reshape(-1,3) = [[1348840.   541246.2  817276.4]]
closest_sk_pt_coord BEFORE = [1348964.14024777  541728.93462084  817404.77605041]
current_skeleton.shape = (200, 2, 3)
node_for_stitch = 0: [1348964.14024777  541728.93462084  817404.77605041]
node_for_stitch AFTER = 0: [1348964.14024777  541728.93462084  817404.77605041]
possible_node_loc = [  0 194]
possible_node_loc AFTER = [  0 194]
curr_shortest_path = [0]
Current stitch point was a branch or endpoint
change_status 


Removed 8 skeletal branches



202426 202427
For marked faces: None
empty_indices % = 0.0004643649315555731
 conflict_indices % = 0.0



AFTER face_lookup_resolved_test



Upstream node was None so don't have to adjust
axon_limb_name= L1
Limb starting node = 41
Axon starting node = 41
axon_branches = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Using Axon Starting Info
Leftover Nodes After Axon Deletion = []
New Node names = []
Leftover Nodes Mapping = {}
concept_network_dict = {0: [<networkx_utils.GraphOrderedEdges object at 0x7efdfd68d4a8>]}
Working on limb L1 branch 117
Working on limb L1 branch 108
Working on limb L1 branch 119
Working on limb L1 branch 84
Working on limb L1 branch 109
Working on limb L1 branch 112
Working on limb L1 branch 118
Working on limb L1 branch 75
Working on limb L1 branch 85
Working on limb L1 branch 123
Working on limb L1 branch 125
Working on limb L1 branch 126
Working on limb L1 branch 56
Working on limb L1 branch 76
Working on limb L1 branch 91
Working on limb L1 branch 98
Working on limb L1 branch 37
Working on



---------Working on soma_idx = 0, soma_group_idx 0, endpt = [1348964.14024777  541728.93462084  817404.77605041]---------
Starting_edge inside branches_to_conept = [[1348964.14024777  541728.93462084  817404.77605041]
 [1351517.84565173  560608.21852905  821071.11405119]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [108]
printing out current edge:
[[1348964.14024777  541728.93462084  817404.77605041]
 [1351517.84565173  560608.21852905  821071.11405119]]
edge_endpoints_to_process was empty so exiting loop after 148 iterations
starting_node in concept map (that should match the starting edge) = 117
Total time for branches to concept conversion = 1.4812805652618408

Done generating concept network 




---- Step 3: Applying Excitatory Filters Post-processing -----

--- Working on filter 0:
function = axon_on_dendrite_merges
function __name__ = filter_away_axon_on_dendrite_merges
function arguments = {'use_pre_existing_axon_labels': T

----------------------- FINISHED Running Filter ------------------



 --Filter double_back_and_width_change Results --
local_results = {'double_back_and_width_change_neuron': <neuron.Neuron object at 0x7efdec8afdd8>, 'double_back_and_width_change_time': 34.199880838394165, 'double_back_and_width_change_error_area': 100.65707498638605, 'double_back_and_width_change_error_length': 150.63852762626743}

--- Working on filter 4:
function = high_degree_coordinates
function __name__ = filter_away_high_degree_coordinates
function arguments = {'axon_dependent': True, 'min_degree_to_find': 4}


----------------------- Running Filter ------------------
min_degree_to_find = 4
curr_high_degree_nodes for get_nodes_greater_or_equal_degree_k = []
high_degree_branch_groups = []

--- Working on Limb L0 ---
edges_to_create = []
edges_to_create = []
min_degree_to_find = 4
curr_high_degree_nodes for get_nodes_greater_or_equal_degree_k = []
high_degree_branch_groups = []

--- Working on Limb L1 ---
edges_t

In [127]:
nviz.visualize_neuron(filtered_neuron,
                     limb_branch_dict={filtered_neuron.axon_limb_name:"all"})


 Working on visualization type: mesh

 Working on visualization type: skeleton


# Development

In [125]:
o_neuron,filtering_info = pru.proofread_neuron_class_predetermined(neuron_obj=neuron_obj,
            inh_exc_class = "excitatory",
            plot_limb_branch_filter_with_disconnect_effect = True,
            verbose = False,
            verbose_outline = True,
            high_fidelity_axon_on_excitatory = True,
            plot_final_filtered_neuron = False,)



 Using high_fidelity_axon_on_excitatory


---Step 1: Applying Dendrite on Axon Filtering
INSIDE THE NEW EXCITATORY FILTERS: {'filter_name': 'crossovers', 'filter_function': <function filter_away_crossovers at 0x7efdeccc17b8>, 'filter_kwargs': {'axon_dependent': True, 'match_threshold': 50, 'require_two_pairs': False}}

--- Working on filter 0:
function = dendrite_on_axon_merges
function __name__ = filter_away_dendrite_on_axon_merges
function arguments = {'use_pre_existing_axon_labels': True}




Branches Requested to Remove (WITH disconnect effect)

 Working on visualization type: mesh





 ---- Total time for applying filter: 25.799861669540405 -----


---- Step 2: Applying High Fidelity Axon -----
Starting axon branch was the starting node so using border vertices and NOT computing upstream branch
upstream_node_to_axon_starting_branch = None


  0%|          | 0/1 [00:00<?, ?it/s]

root_curr = [1348840.   541246.2  817276.4]
Time for preparing soma vertices and root: 0.007697105407714844
invalidation_d = 2000
cc_vertex_thresh = 10


100%|██████████| 1/1 [00:04<00:00,  4.82s/it]

meshparty_segment_size = 100
Time for 1st pass MP skeletonization: 6.151233196258545
branches_touching_root = [17]
combining close nodes
combine_threshold = 1300
length of Graph = 26007
After combining close endpoints max(kept_branches_idx) = 173, len(kept_branches_idx) = 163
empty_indices % = 0.0
 conflict_indices % = 0.01873853562546661



AFTER face_lookup_resolved_test



Decomposing first pass: 16.228153228759766
Only Using MeshParty Skeletonization and Mesh Correspondence
Another print
Divinding into MP and MAP pieces: 9.131431579589844e-05
Total time for MAP sublimb processing 6.198883056640625e-06
---- Working on MP Decomposition #0 ----
Using Quicker soma_to_piece_touching_vertices because no MAP and only one sublimb_mesh piece 
MP filtering soma verts: 0.0003094673156738281
Fixing Possible Soma Extension Branch for Sublimb 0
Total time for mesh KDTree = 0.1169886589050293
sbv[0].reshape(-1,3) = [[1348840.   541246.2  817276.4]]
closest_sk_pt_coord BEFORE = [1348964.14024777  541728.93462084  817404.77605041]
current_skeleton.shape = (200, 2, 3)
node_for_stitch = 0: [1348964.14024777  541728.93462084  817404.77605041]
node_for_stitch AFTER = 0: [1348964.14024777  541728.93462084  817404.77605041]
possible_node_loc = [  0 194]
possible_node_loc AFTER = [  0 194]
curr_shortest_path = [0]
Current stitch point was a branch or endpoint
change_status fo


Removed 8 skeletal branches



202426 202427
For marked faces: None
empty_indices % = 0.0004890651938723589
 conflict_indices % = 0.0



AFTER face_lookup_resolved_test



Upstream node was None so don't have to adjust
concept_network_dict = {0: [<networkx_utils.GraphOrderedEdges object at 0x7efcd357b6d8>]}
Assigning the old width calculation because no valid new widths


----Working on seperate_graph 0----


---------Working on soma_idx = 0, soma_group_idx 0, endpt = [1348964.14024777  541728.93462084  817404.77605041]---------
Starting_edge inside branches_to_conept = [[1348964.14024777  541728.93462084  817404.77605041]
 [1351517.84565173  560608.21852905  821071.11405119]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [108]
printing out current edge:
[[1348964.14024777  541728.93462084  817404.77605041]
 [1351517.84565173  560608.21852905  821071.11405119]]
edge_endpoints_to_process was empty so exiting loop after 148 iterations
starting_node in concept map (that should match the starting edge) = 117
Total time for branches to concept conversion = 1.507692575454712

Done generating concept network 



--- Working on filter 1:
function = crossovers
function __name__ = filter_away_crossovers
function arguments = {'axon_dependent': True, 'match_threshold': 50, 'require_two_pairs': False}




Branches Requested to Remove (WITH disconnect effect)

 Working on visualization type: mesh



--- Working on filter 2:
function = low_branch_clusters
function __name__ = filter_away_low_branch_length_clusters
function arguments = {}



--- Working on filter 3:
function = double_back_and_width_change
function __name__ = filter_away_large_double_back_or_width_changes
function arguments = {'perform_double_back_errors': True, 'skip_double_back_errors_for_axon': False, 'width_jump_threshold': 250, 'running_width_jump_method': True, 'double_back_axon_like_threshold': 145, 'double_back_threshold': 120}




Branches Requested to Remove (WITH disconnect effect)

 Working on visualization type: mesh



--- Working on filter 4:
function = high_degree_coordinates
function __name__ = filter_away_high_degree_coordinates
function arguments = {'axon_dependent': True, 'min_degree_to_find': 4}


min_degree_to_find = 4
min_degree_to_find = 4
min_degree_to_find = 4
min_degree_to_find = 4
min_degree_to_find = 4
min_degree_to_find = 4
min_degree_to_find = 4



 ---- Total time for applying filter: 82.70706129074097 -----


# Analyzing how the crossover did

In [124]:
after_crossover_neuron = filtering_info["crossovers_neuron"]

axon_limb_name = after_crossover_neuron.axon_limb_name

high_degree_coords = nru.high_degree_branching_coordinates_on_limb(after_crossover_neuron[axon_limb_name],
                                             min_degree_to_find=4)

nviz.visualize_neuron(after_crossover_neuron,limb_branch_dict={axon_limb_name:"all"},
                     scatters=[high_degree_coords],
                     scatter_size=0.1)


 Working on visualization type: mesh

 Working on visualization type: skeleton


In [117]:
high_degree_coords = nru.high_degree_branching_coordinates_on_limb(after_crossover_neuron[axon_limb_name],
                                             min_degree_to_find=5)

nviz.visualize_neuron(after_crossover_neuron,limb_branch_dict={axon_limb_name:"all"},
                     scatters=[high_degree_coords],
                     scatter_size=0.2)


 Working on visualization type: mesh

 Working on visualization type: skeleton


In [118]:
high_degree_coords

array([[1334595.81146576,  658912.32150835,  847548.99412118],
       [1338068.99895845,  648534.46800445,  847560.49040373]])

In [109]:
nviz.visualize_limb_obj(after_crossover_neuron[0])

In [111]:
after_crossover_neuron.axon_limb_name

'L1'

In [110]:
nviz.visualize_limb_obj(after_crossover_neuron["L0"])