In [1]:
"""
Purpose: To show how to 
a) decompose a neuron with the analysis into a neuron object
b) compress the object into a smaller data representation for storage
c) decompress the object back into the original object (using the original mesh)
d) make sure the decompressed version matches the original

"""

'\nPurpose: To show how to \na) decompose a neuron with the analysis into a neuron object\nb) compress the object into a smaller data representation for storage\nc) decompress the object back into the original object (using the original mesh)\nd) make sure the decompressed version matches the original\n\n'

# Prospective Runtime

In [39]:
non_soma_meshes = 3000000
n_meshes = 100000
n_jobs = 300
average_run_time = 10 # in minutes
seconds_per_non_soma = 20
comp_time_hr = n_meshes*average_run_time/60 + non_soma_meshes*seconds_per_non_soma/3600
n_days = comp_time_hr/n_jobs/24
n_days

4.62962962962963

In [19]:
n_meshes = 100000
n_jobs = 300
average_run_time = 1.5
comp_time_hr = n_meshes*average_run_time/60
comp_time_hr/n_jobs/24

10.416666666666666

In [2]:
from os import sys
sys.path.append("../../meshAfterParty/meshAfterParty")

In [3]:
import neuron
import system_utils as su
from importlib import reload
import trimesh_utils as tu
import skeleton_utils as sk
from pathlib import Path
import trimesh
import neuron_utils as nru

# Step 1: Decomposition

In [4]:
segment_id = 12345
current_mesh_file = "/notebooks/neuron_mesh_tools/test_neurons/multi_soma_example.off"
description="2_soma_practice_decompress"

double_soma_neuron = tu.load_mesh_no_processing(current_mesh_file)
sk.graph_skeleton_and_mesh(other_meshes = [double_soma_neuron])

/usr/local/lib/python3.6/dist-packages/traittypes/traittypes.py:101: UserWarning: Given trait value dtype "float64" does not match required type "float64". A coerced copy has been created.
  np.dtype(self.dtype).name))


In [5]:
nru = reload(nru)
neuron = reload(neuron)
double_neuron = neuron.Neuron(
    mesh=double_soma_neuron,
    segment_id=segment_id,
    description=description
                         )

--- 0) Having to preprocess the Neuron becuase no preprocessed data
Please wait this could take a while.....


--- 0) Total time for preprocessing: 1018.624678850174




--- 1) Finished unpacking preprocessed materials: 8.58306884765625e-06
total_edges = [['S0', 'L0'], ['S0', 'L1'], ['S0', 'L2'], ['S0', 'L3'], ['S0', 'L5'], ['S0', 'L10'], ['S1', 'L1'], ['S1', 'L4'], ['S1', 'L6'], ['S1', 'L7'], ['S1', 'L8'], ['S1', 'L9']]
--- 2) Finished creating neuron connectivity graph: 0.0001385211944580078
Having to generate soma_meshes_face_idx because none in preprocessed data
--- 3a) Finshed generating soma_meshes_face_idx: 1.0994760990142822
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 374
xvfb-run -n 374 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_197813.off -o /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_197813_poisson.off -s /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/poisson_365590.mls


face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!


removed temporary input file: /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_197813.off
removed temporary output file: /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_197813_poisson.off
/notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/poisson_365590.mls is being deleted....
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 736
xvfb-run -n 736 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_919246.off -o /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_919246_poisson.off -s /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/poisson_645832.mls


face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!


removed temporary input file: /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_919246.off
removed temporary output file: /notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/neuron_919246_poisson.off
/notebooks/neuron_mesh_tools/meshAfterPartyDev/Poisson_temp/poisson_645832.mls is being deleted....
--- 3) Finshed generating soma objects and adding them to concept graph: 18.310173273086548
--- 4a) Finshed generating curr_limb_meshes_face_idx: 3.7815260887145996
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
There are loops to resolve and 'no_cycles' parameters set requires us to fix eliminate them
Using mesh_widths for resolving loops
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
There are loops to resolve and 'no_cyc

# Step 2: Compressing a Neuron

In [35]:
# Rerunning compression analysis on interneurons
import neuron_utils as nru
su = reload(su)
nru = reload(nru)
location=Path("../test_neurons/test_objects/")

compressed_file = nru.save_compressed_neuron(double_neuron,output_folder=location,return_file_path=True,export_mesh=True)

#export the mesh to the same place

Total time for soma meshes compression = 1.1999397277832031
Total time for insignificant_limbs,inside_pieces,non_soma_touching_meshes compression = 3.4358131885528564
Total time for limb_meshes compression = 4.803750514984131
    Starting Limb Correspondence Compression



Total time for new_limb_correspondence compression = 46.00211215019226
Total time for compression = 55.44415473937988
Saved object at /notebooks/neuron_mesh_tools/meshAfterPartyDev/../test_neurons/test_objects/12345_2_soma_practice_decompress.pbz2
File size is 3.489583 MB


---Finished outputing neuron at location: /notebooks/neuron_mesh_tools/meshAfterPartyDev/../test_neurons/test_objects/12345_2_soma_practice_decompress---


#  Step 3: Decompressing a Neuron

In [33]:
import trimesh_utils as tu
tu = reload(tu)
su = reload(su)
neuron = reload(neuron)
nru=reload(nru)

from tqdm.notebook import tqdm


recovered_neuron = nru.decompress_neuron(filepath=compressed_file,
                  original_mesh=compressed_file)

Passed faces original mesh check
Passed vertices original mesh check





------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 73 len(curr_limb_divided_skeletons) = 73
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.3659372329711914
Total time for mesh mapping: 0.5782899856567383
Total time for mesh mapping: 0.13809537887573242
Total time for mesh mapping: 0.16747426986694336
touching_pieces = [46]
Total time for mesh connectivity = 0.9026200771331787
Touching piece endpoints = [[756409.  947718.  874266. ]
 [757475.6 948519.  871904.1]]
inside inner loop len(curr_limb_divided_skeletons) = 73
closest_endpoint = [757475.6 948519.  871904.1]
Starting_edge inside branches_to_conept = [[756409.  947718.  874266. ]
 [757475.6 948519.  871904.1]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [48]
printing out current edge:
[[757475.6 948519.  871904.1]
 [756409.  947718.  874266. ]]
edge_endpoints_to_process was empty so exiting loop after 73 iterations
starti

Total time for filtering periphery meshes = 0.06638312339782715
Total time for mesh mapping: 0.14197874069213867
touching_pieces = [13]
Total time for mesh connectivity = 0.15184688568115234
Touching piece endpoints = [[865475.  982584.  861805. ]
 [865721.6 988630.6 860869.1]]
inside inner loop len(curr_limb_divided_skeletons) = 17
closest_endpoint = [865721.6 988630.6 860869.1]
Starting_edge inside branches_to_conept = [[865475.  982584.  861805. ]
 [865721.6 988630.6 860869.1]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [12]
printing out current edge:
[[865721.6 988630.6 860869.1]
 [865475.  982584.  861805. ]]
edge_endpoints_to_process was empty so exiting loop after 17 iterations
starting_node in concept map (that should match the starting edge) = 13
Total time for branches to concept conversion = 0.09132552146911621

recovered_touching_piece = [13]
After concept mapping size = 17
Local time for concept mapping = 0.357887268066

# Step 4: Checking that decompressed neuron object and origianl object were the same

In [34]:
recovered_neuron == double_neuron

True