In [ ]:
"""
Purpose: Clean implmentation that 
takes a fully processed neuron and is able to 
split the limbs that were accidentally included together

Pseudocode

"""

In [3]:
from os import sys
sys.path.append("/meshAfterParty/")
#sys.path.append("../../meshAfterParty/meshAfterParty")

In [4]:
from importlib import reload
import os
from pathlib import Path
os.getcwd()

import neuron_utils as nru
nru = reload(nru)
import neuron
neuron=reload(neuron)
import neuron_visualizations as nviz
import time
import system_utils as su

# Importing Test Neuron

In [5]:
current_file = "/notebooks/test_neurons/meshafterparty_processed/12345_double_soma_meshafterparty"
neuron_obj = nru.decompress_neuron(filepath=current_file,
                                  original_mesh=current_file,
                                  minimal_output=True)


Inside decompress neuron and decomposition_type = meshafterparty
Passed faces original mesh check
Passed vertices original mesh check



********************************** generate_limb_concept_networks_from_global_connectivity****************************


------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 68 len(curr_limb_divided_skeletons) = 68
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.3638491630554199
touching_pieces = [44]
Total time for mesh connectivity = 0.7869784832000732
Using touching_pieces[0] = 44
inside inner loop len(curr_limb_divided_skeletons) = 68
closest_endpoint WITH NEW KDTREE METHOD= [754770.2 950773.4 873485.9]
About to send touching_soma_vertices = [[758199.2 951673.5 875799.4]
 [756978.4 951254.  871233.8]
 [759524.8 951280.8 873206.6]
 [758907.  950977.6 871911.2]
 [759144.8 950937.4 872043.8]
 [759478.2 951371.6 873044.1]
 [758809.2 951824.5 875252.6]
 [758136.8 951401.1 875848.1]
 [757570.2 951200.8 876043. ]
 [759325.8 951924.6 874210.1]
 [759424.8 951622.7 873907.9]
 [754846.4 950863.9 872870.1]
 [754770.2 950773.4 873485.9]
 [759

Local time for concept mapping = 1.7330818176269531


------Working on limb 1 -------
inside loop len(curr_limb_divided_meshes) = 49 len(curr_limb_divided_skeletons) = 49
Merge limb detected
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.22109436988830566
touching_pieces = [11]
Total time for mesh connectivity = 0.19283318519592285
Using touching_pieces[0] = 11
inside inner loop len(curr_limb_divided_skeletons) = 49
closest_endpoint WITH NEW KDTREE METHOD= [763677.2 960913.9 879506.8]
About to send touching_soma_vertices = [[764369.4 961579.  877947.4]
 [763335.2 961687.8 879612.2]
 [763925.8 960916.3 879439.4]
 [763378.6 961830.4 878169.8]
 [764348.  960489.9 878697.4]
 [763189.8 961895.4 879268.1]
 [764502.8 960665.2 878480.4]
 [763201.2 961529.1 879621.8]
 [763385.6 961419.9 879647.8]
 [764359.6 961425.1 878059.9]
 [764093.4 960579.9 879224.1]
 [763293.6 961809.8 879253.9]
 [763290.2 961772.8 879492.6]
 [763181.  962043.1 879046.7]
 [764403.  960454.9 8

Total time for filtering periphery meshes = 0.11385822296142578
touching_pieces = [5]
Total time for mesh connectivity = 0.33837103843688965
Using touching_pieces[0] = 5
inside inner loop len(curr_limb_divided_skeletons) = 39
closest_endpoint WITH NEW KDTREE METHOD= [ 862103. 1002270.  879904.]
About to send touching_soma_vertices = [[865523.6 999041.2 866004.2]
 [864669.2 997565.4 867472.4]
 [865488.4 998225.1 866958.1]
 [863506.4 997662.8 866843.4]
 [866137.  998252.4 866470.2]
 [865453.2 997977.9 867053.9]
 [864429.2 997518.6 867434.7]
 [866863.  998992.9 865393.7]
 [865199.6 998034.2 867383.3]
 [863561.2 997473.6 867104.4]
 [866033.6 999128.2 865682.9]
 [865759.4 998132.1 866720.4]
 [866945.  998612.9 865674.1]
 [863560.2 997629.8 867095.6]
 [867097.6 998874.2 865659.1]
 [865883.6 998176.6 866616.4]
 [866690.4 998360.8 866153. ]
 [864810.8 997654.6 867551.6]
 [863735.6 997336.9 867139. ]
 [866705.2 998250.4 866050.2]
 [865045.2 998812.1 866446.1]
 [866201.2 999131.2 865597.8]
 [866

edge_endpoints_to_process was empty so exiting loop after 53 iterations
starting_node in concept map (that should match the starting edge) = 0
Total time for branches to concept conversion = 0.20102524757385254

Working on adding back the edges that were duplicates
Recovered touching vertices = {0: TrackedArray([[757928.4, 962502.2, 866083.1],
              [757431.2, 961958.1, 865624.8],
              [757241.2, 960809.8, 865940.9],
              [757409.6, 960733.9, 865987.2],
              [759607.8, 962760.3, 866627.8],
              [759926.4, 959992.1, 866323.6],
              [759242.6, 962667.4, 866284.2],
              [758284.6, 962591.1, 866085.4],
              [758735.2, 959915.7, 866344.1],
              [759006. , 962652.2, 866260.4],
              [757331.2, 960980.1, 865803.5],
              [759866.2, 962747.5, 866851.7],
              [757306.2, 961203.8, 865800.2],
              [757533.8, 962121.5, 865822.1],
              [759733.2, 959948. , 866322.7],
          

Local time for concept mapping = 0.7778017520904541


------Working on limb 5 -------
inside loop len(curr_limb_divided_meshes) = 11 len(curr_limb_divided_skeletons) = 11
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.06130480766296387
touching_pieces = [7]
Total time for mesh connectivity = 0.29636597633361816
Using touching_pieces[0] = 7
inside inner loop len(curr_limb_divided_skeletons) = 11
closest_endpoint WITH NEW KDTREE METHOD= [752584.6 964335.9 869329.8]
About to send touching_soma_vertices = [[752618.4 964281.4 869517. ]
 [750819.6 962859.9 869731.4]
 [751823.2 962800.2 868718.6]
 [753231.8 964522.2 868843.6]
 [750671.8 963090.7 869636.8]
 [751761.8 964135.9 870006.4]
 [752242.  963065.8 868199.2]
 [751957.6 962834.  868606.1]
 [752960.  964192.  868100. ]
 [752201.2 964167.2 869934.4]
 [751723.4 964079.1 870135.9]
 [750696.  963318.9 870114. ]
 [752639.4 963476.2 867820.1]
 [753131.  964304.4 868379.6]
 [752364.2 963106.6 868044.4]
 [750826.  96

Total time for filtering periphery meshes = 0.06783843040466309
touching_pieces = [1]
Total time for mesh connectivity = 0.2112894058227539
Using touching_pieces[0] = 1
inside inner loop len(curr_limb_divided_skeletons) = 21
closest_endpoint WITH NEW KDTREE METHOD= [867187. 993812. 851183.]
About to send touching_soma_vertices = [[866520.2 994194.9 851413.6]
 [866590.8 993467.2 851482.3]
 [866720.8 993395.2 851593.1]
 [867003.  994448.7 851361.9]
 [867435.4 993751.4 851440. ]
 [866814.2 993324.4 851636.4]
 [866880.2 993377.  851460.1]
 [866509.6 993902.  851326.9]
 [867343.6 993522.1 851571.4]
 [867232.2 994380.1 851377.3]
 [867451.8 993962.1 851439.8]
 [867401.8 993727.7 851663.9]
 [867388.2 994041.8 851495.8]
 [867133.1 993448.3 851721.9]
 [866572.5 993742.7 851234.4]
 [867344.1 994204.8 851431.9]
 [866617.1 993579.2 851340.3]
 [866778.7 994302.8 851286.6]
 [867056.5 993361.  851625.5]
 [867408.1 993916.  851669.5]]
Starting_edge inside branches_to_conept = [[867187. 993812. 851183.]

Total time for neuron instance creation = 25.099905967712402


In [83]:
import skeleton_utils as sk
from pykdtree.kdtree import KDTree
import trimesh_utils as tu
import numpy as np
import networkx_utils as xu
import compartment_utils as cu
import networkx as nx
import numpy_utils as nu
import copy
import general_utils as gu
import system_utils as su

In [8]:
current_neuron = neuron_obj
nru = reload(nru)
neuron = reload(neuron)
current_neuron = neuron.Neuron(current_neuron)

# Pre-Step 0: Prepare the containers to store the new data

In [79]:
def check_if_branch_needs_splitting(current_neuron,curr_limb,soma_idx,curr_soma_mesh,
                                    significant_skeleton_threshold=30000,
                                   print_flag=False):
    
    
    #1) get the starting node:
    curr_starting_branch_idx = curr_limb.get_starting_branch_by_soma(soma_idx)
    #a. Get the staring branch skeleton and find the closest skeleton point to the soma border
    curr_branch = curr_limb[curr_starting_branch_idx]
    curr_branch_sk = curr_branch.skeleton
    #b. find the closest skeleton point to the soma border
    curr_soma_border = curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
    unique_skeleton_nodes = np.unique(curr_branch_sk.reshape(-1,3),axis=0)
    
    curr_soma_border_kdtree = KDTree(curr_soma_border)
    distances,closest_node = curr_soma_border_kdtree.query(unique_skeleton_nodes)
    cut_coordinate = unique_skeleton_nodes[np.argmin(distances),:]
    
    #c. cut the limb skeleton at that point
    curr_limb_sk_graph = sk.convert_skeleton_to_graph(curr_limb.skeleton)

    node_to_cut = xu.get_nodes_with_attributes_dict(curr_limb_sk_graph,dict(coordinates=cut_coordinate))

    if len(node_to_cut) != 1:
        raise Exception("Node to cut was not of length 1")

    node_to_cut = node_to_cut[0]
    
    #c. Seperate the graph into 2 components, If there are 2 connected components after cut, are the connected components both significant
    curr_limb_sk_graph.remove_node(node_to_cut)

    seperated_components = list(nx.connected_components(curr_limb_sk_graph))

    if len(seperated_components) <= 1:
        return None
        #raise Exception(f"Continue to next limb because number of seperated_components = {len(seperated_components)}")

    #c1. Seperate the graph into subgraph based on components and output the skeletons from each
    seperated_skeletons = [sk.convert_graph_to_skeleton(curr_limb_sk_graph.subgraph(k)) for k in seperated_components]
    skeleton_lengths = np.array([sk.calculate_skeleton_distance(k) for k in seperated_skeletons])


    n_significant_skeletons = np.sum(skeleton_lengths>significant_skeleton_threshold)
    if print_flag:
        print(f"n_significant_skeletons={n_significant_skeletons}")
        print(f"skeleton_lengths = {skeleton_lengths}")

    if n_significant_skeletons < 2:
        return None
    else:
        return cut_coordinate
        #raise Exception(f"Continue to next limb because n_significant_skeletons = {n_significant_skeletons} with lengths {skeleton_lengths}")

In [86]:
def split_limb_on_soma(current_neuron,curr_limb,soma_idx,curr_soma_mesh,
                       cut_coordinate=None,
                      print_flag=False):
    #1) get the starting node:
    curr_starting_branch_idx = curr_limb.get_starting_branch_by_soma(soma_idx)
    #a. Get the staring branch skeleton and find the closest skeleton point to the soma border
    curr_branch = curr_limb[curr_starting_branch_idx]
    curr_branch_sk = curr_branch.skeleton
    
    if cut_coordinate is None:
        if print_flag:
            print("Having to recalculate the cut coordinate")
        
        #b. find the closest skeleton point to the soma border
        curr_soma_border = curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
        unique_skeleton_nodes = np.unique(curr_branch_sk.reshape(-1,3),axis=0)

        curr_soma_border_kdtree = KDTree(curr_soma_border)
        distances,closest_node = curr_soma_border_kdtree.query(unique_skeleton_nodes)
        cut_coordinate = unique_skeleton_nodes[np.argmin(distances),:]
    
    
    
    # --------------- Part A: Finding the new split skeletons ------------------------- #
    # Finding the node to cut on the BRANCH skeleton
    curr_branch_sk_graph = sk.convert_skeleton_to_graph(curr_branch_sk)

    if print_flag:
        print(f"cut_coordinate={cut_coordinate}")
    node_to_cut = xu.get_nodes_with_attributes_dict(curr_branch_sk_graph,dict(coordinates=cut_coordinate))
    if len(node_to_cut) != 1:
        raise Exception("Node to cut was not of length 1")

    node_to_cut = node_to_cut[0]
    
    G = curr_branch_sk_graph
    endpoint_nodes = xu.get_nodes_of_degree_k(G,1)
    endpoint_nodes_coord = xu.get_node_attributes(curr_branch_sk_graph,node_list=endpoint_nodes)
    paths_to_endpt = [nx.dijkstra_path(G,node_to_cut,k) for k in endpoint_nodes]
    path_lengths = np.array([len(k) for k in paths_to_endpt])
    closest_endpoint = np.argmin(path_lengths)
    farthest_endpoint = 1 - closest_endpoint
    closest_endpoint_len = path_lengths[closest_endpoint]

    if closest_endpoint_len <= 1:
        #need to readjust the node_to_cut and paths
        print("Having to readjust endpoint")
        node_to_cut = paths_to_endpt[farthest_endpoint][1]
        paths_to_endpt = [nx.dijkstra_path(G,node_to_cut,k) for k in endpoint_nodes]

    #generate the subnode in each graph
    paths_to_endpt[farthest_endpoint].remove(node_to_cut)

    subgraph_list = [G.subgraph(k) for k in paths_to_endpt]

    starting_endpoints = xu.get_node_attributes(curr_branch_sk_graph,node_list=[k[0] for k in paths_to_endpt])


    #export the skeletons of the subgraphs
    exported_skeletons = [sk.convert_graph_to_skeleton(s) for s in subgraph_list]
    endpoint_nodes_coord #will have the endpoints belonging to each split
    
    
    # --------------- Part B: Getting Initial Mesh Correspondence ------------------------- #
    """
    3) Do Mesh correspondnece to get new branch meshes for the split skeleton
    - where have to do face resolving as well
    4) Check that both of the meshes are touching the soma
    5) If one of them is not touching the soma
    --> do water growing algorithm until it is

    """

    div_st_branch_face_corr = []
    div_st_branch_width = []
    for sub_sk in exported_skeletons:
        curr_branch_face_correspondence, width_from_skeleton = cu.mesh_correspondence_adaptive_distance(sub_sk,
                                                  curr_branch.mesh,
                                                 skeleton_segment_width = 1000,
                                                 distance_by_mesh_center=True)
        div_st_branch_face_corr.append(curr_branch_face_correspondence)
        div_st_branch_width.append(width_from_skeleton)
    
    
    divided_submeshes,divided_submeshes_idx = cu.groups_of_labels_to_resolved_labels(current_mesh = curr_branch.mesh,
                                          face_correspondence_lists=div_st_branch_face_corr)
    
    
#     # ------------ Intermediate part where intentionally messing up --------------- #    
#     label_to_expand = 1

#     #0) Turn the mesh into a graph
#     total_mesh_graph = nx.from_edgelist(curr_branch.mesh.face_adjacency)

#     #1) Get the nodes that represent the border
#     border_vertices =  curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
#     border_faces = tu.vertices_coordinates_to_faces(curr_branch.mesh,border_vertices)

#     label_face_idx = divided_submeshes_idx[label_to_expand]

#     final_faces = label_face_idx.copy()

#     for i in range(0,40):
#         final_faces = np.unique(np.concatenate([xu.get_neighbors(total_mesh_graph,k) for k in final_faces]))

#     other_mesh_faces = np.setdiff1d(np.arange(0,len(curr_branch.mesh.faces)),final_faces)
    
#     divided_submeshes_idx = [other_mesh_faces,final_faces]
#     divided_submeshes = [curr_branch.mesh.submesh([k],append=True) for k in divided_submeshes_idx]
    
#     sk.graph_skeleton_and_mesh(other_meshes=list(divided_submeshes),
#                            other_meshes_colors=["black","red"],
#                           other_skeletons=exported_skeletons,
#                           other_skeletons_colors=["black","red"],)
    
    
    
    # ---------------- Part C: Checking that both pieces are touching the soma ------------- #
    touching_pieces,touching_pieces_verts = tu.mesh_pieces_connectivity(main_mesh=tu.combine_meshes([curr_branch.mesh,curr_soma_mesh]),
                           central_piece=curr_soma_mesh,
                           periphery_pieces=divided_submeshes,
                           merge_vertices=True,
                            return_vertices=True,
                           print_flag=False)
    if print_flag:
        print(f"touching_pieces = {touching_pieces}")
        
        
        
    # --------------- Part D: Doing Waterfilling Unitl Both Pieces are Touching Soma ------------- #
    if len(touching_pieces) == 0:
        raise Exception("There were none of the new meshes that were touching the soma")
    if len(touching_pieces) < 2:
        #find which piece was not touching
        label_to_expand = 1 - touching_pieces[0]
        print(f"new_mesh {label_to_expand} was not touching the mesh so need to expand until touches soma")

        #0) Turn the mesh into a graph
        total_mesh_graph = nx.from_edgelist(curr_branch.mesh.face_adjacency)

        #1) Get the nodes that represent the border
        border_vertices =  curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
        border_faces = set(tu.vertices_coordinates_to_faces(curr_branch.mesh,border_vertices))

        label_face_idx = divided_submeshes_idx[label_to_expand]

        final_faces = label_face_idx.copy()

        n_touching_soma = 0
        counter = 0
        while n_touching_soma < 10:
            final_faces = np.unique(np.concatenate([xu.get_neighbors(total_mesh_graph,k) for k in final_faces]))
            n_touching_soma = len(border_faces.intersection(set(final_faces)))
            counter+= 1


        other_mesh_faces = np.setdiff1d(np.arange(0,len(curr_branch.mesh.faces)),final_faces)

        


        print(f"Took {counter} iterations to expand the label back")

        divided_submeshes_idx[label_to_expand] = final_faces
        divided_submeshes_idx[touching_pieces[0]] = other_mesh_faces

        #Need to fix the labels one more time to make sure the expansion did not cut off one of the labels
        print(f"divided_submeshes_idx = {divided_submeshes_idx}")
        divided_submeshes,divided_submeshes_idx = cu.groups_of_labels_to_resolved_labels(curr_branch.mesh,divided_submeshes_idx)

        print(f"divided_submeshes_idx = {divided_submeshes_idx}")

        divided_submeshes = [curr_branch.mesh.submesh([k],append=True) for k in divided_submeshes_idx]

        #recalculate the border vertices and the list should be 2
        touching_pieces,touching_pieces_verts = tu.mesh_pieces_connectivity(main_mesh=tu.combine_meshes([curr_branch.mesh,curr_soma_mesh]),
                               central_piece=curr_soma_mesh,
                               periphery_pieces=divided_submeshes,
                               merge_vertices=True,
                                return_vertices=True,
                               print_flag=False)
        if len(touching_pieces) != 2:
            raise Exception(f"Number of touching pieces not equal to 2 even after correction: {touching_pieces}")

    soma_border_verts = touching_pieces_verts

#     sk.graph_skeleton_and_mesh(other_meshes=list(divided_submeshes),
#                                other_meshes_colors=["black","red"],
#                               other_skeletons=exported_skeletons,
#                               other_skeletons_colors=["black","red"],
#                               other_scatter=[endpoint_nodes_coord[0].reshape(-1,3),endpoint_nodes_coord[1].reshape(-1,3)],
#                                other_scatter_colors=["black","red"],
#                               scatter_size=1)


    
    # ----------------- Part E: Check that the mesh can't be split ----------------- #
    
    # check that the mesh can't be split
    for j,sub in enumerate(divided_submeshes):
        c_mesh,c_indic = tu.split(sub)
        if len(c_mesh) > 1:
            raise Exception(f"New Mesh {j} had {len(c_mesh)} pieces after split")

            
    # ----------------- Part F: Reorganize the Concept Network ----------------- #
    neighbors_to_starting_node = xu.get_neighbors(curr_limb.concept_network,curr_starting_branch_idx)
    """
    sk.graph_skeleton_and_mesh(other_meshes=[curr_limb[k].mesh for k in neighbors_to_starting_node + [curr_starting_branch_idx]],
                              other_meshes_colors="random")
    """
    
    match=dict([(k,[]) for k in neighbors_to_starting_node])
    for ex_neighbor in neighbors_to_starting_node:
        ex_neighbor_branch = curr_limb[ex_neighbor]
        for j,endpt in enumerate(endpoint_nodes_coord):
            if len(nu.matching_rows(ex_neighbor_branch.endpoints,endpt))>0:
                match[ex_neighbor].append(j)

    #make sure that there was only one match
    for k,v in match.items():
        if len(v) != 1:
            raise Exception(f"Neighbor {k} did not have one matching but instead had {v}")
            
   
    concept_network_copy = copy.deepcopy(curr_limb.concept_network)
    concept_network_copy.remove_node(curr_starting_branch_idx)
    concept_conn_comp = list(nx.connected_components(concept_network_copy))

    #divide up the connected components into the groups they belong to
    new_branch_groups = [[],[]]
    for c in concept_conn_comp:
        #find the matching neighbor in that
        matching_neighbor = c.intersection(set(neighbors_to_starting_node))
        if len(matching_neighbor) != 1:
            raise Exception(f"matching_neighbor was not size 1 : {matching_neighbor}")
        matching_neighbor = list(matching_neighbor)[0]
        new_branch_groups[match[matching_neighbor][0]].extend(list(c))

    #check that the lists are not empty
    for i,g in enumerate(new_branch_groups):
        if len(g) == 0:
            raise Exception(f"New branch group {i} was empty after dividing the rest of the nodes")

    if print_flag:
        print(f"new_branch_groups = {new_branch_groups}")
        
        
    
    # Visualize that correctly split
#     divided_neighbor_meshes = [tu.combine_meshes([curr_limb[k].mesh for k in curr_group]) for curr_group in new_branch_groups]
#     divided_neighbor_meshes_with_original = [tu.combine_meshes([k,v]) for k,v in zip(divided_neighbor_meshes,divided_submeshes)]
#     #sk.graph_skeleton_and_mesh(other_meshes=)
#     sk.graph_skeleton_and_mesh(other_meshes=divided_neighbor_meshes_with_original,
#                               other_meshes_colors=["black","red"],
#                               other_skeletons=exported_skeletons,
#                               other_skeletons_colors=["black","red"],
#                               other_scatter=[endpoint_nodes_coord[0].reshape(-1,3),endpoint_nodes_coord[1].reshape(-1,3)],
#                                other_scatter_colors=["black","red"],)

    
    # ----------------- Part G: Put Everything Back into a Limb Object ----------------- #
    new_limbs = []
    for curr_new_branch_idx in range(len(new_branch_groups)):
        print(f"\n--- Working on new limb {curr_new_branch_idx} -------")
        
        #new_limb_dict[curr_new_branch_idx]["soma_border_verts"] = soma_border_verts[curr_new_branch_idx]

        # a) Creating the new concept network
        curr_limb_divided_skeletons =  [curr_limb[k].skeleton for k in new_branch_groups[curr_new_branch_idx]] + [exported_skeletons[curr_new_branch_idx]]
        closest_endpoint = starting_endpoints[curr_new_branch_idx]
        endpoints = neuron.Branch(exported_skeletons[curr_new_branch_idx]).endpoints
        curr_limb_concept_network = nru.branches_to_concept_network(curr_limb_divided_skeletons,closest_endpoint,np.array(endpoints).reshape(-1,3),
                                            touching_soma_vertices= soma_border_verts[curr_new_branch_idx])

        #Run some checks on the new concept network developed
        curr_starting_branch_idx= nru.check_concept_network(curr_limb_concept_network,closest_endpoint = closest_endpoint,
                                  curr_limb_divided_skeletons=curr_limb_divided_skeletons,print_flag=True)[0]

        # b) Creating the new mesh

        """Old way: 
        remaining_meshes_faces_idx =  [curr_limb[k].mesh_face_idx for k in new_branch_groups[curr_new_branch_idx]]
        remaining_meshes_faces_idx.append(np.array(curr_branch.mesh_face_idx[divided_submeshes_idx[curr_new_branch_idx]]))
        """

        new_limb_branch_face_idx = []
        remaining_meshes_face_idx = []
        total_face_count = 0
        for k in new_branch_groups[curr_new_branch_idx]:
            curr_face_idx  = curr_limb[k].mesh_face_idx
            remaining_meshes_face_idx.append(curr_face_idx)
            new_limb_branch_face_idx.append(np.arange(total_face_count,total_face_count+len(curr_face_idx)))
            total_face_count += len(curr_face_idx)

        last_face_idx = np.array(curr_branch.mesh_face_idx[divided_submeshes_idx[curr_new_branch_idx]])
        remaining_meshes_face_idx.append(last_face_idx)
        new_limb_branch_face_idx.append(np.arange(total_face_count,total_face_count+len(last_face_idx)))


        final_remaining_faces = np.concatenate(remaining_meshes_face_idx)                         
        curr_new_limb_mesh = curr_limb.mesh.submesh([final_remaining_faces],append=True,repair=False)

        """
        Checking that it went well:
        reovered_mesh = curr_new_limb_mesh.submesh([new_limb_branch_face_idx[2]],append=True,repair=False)
        original_mesh = curr_limb[new_branch_groups[curr_new_branch_idx][2]].mesh
        reovered_mesh,original_mesh
        """

        curr_limb_correspondence = dict()
        for j,neighb in enumerate(new_branch_groups[curr_new_branch_idx]):
            #calculate the new mesh correspondence
            curr_limb_correspondence[j] = dict(branch_skeleton = curr_limb[neighb].skeleton,
                                              width_from_skeleton = curr_limb[neighb].width,
                                              branch_mesh=curr_limb[neighb].mesh,
                                              branch_face_idx=new_limb_branch_face_idx[j])
        #add on the new mesh
        curr_limb_correspondence[len(new_branch_groups[curr_new_branch_idx])] = dict(
                        branch_skeleton = exported_skeletons[curr_new_branch_idx],
                        width_from_skeleton = div_st_branch_width[curr_new_branch_idx],
                        branch_mesh=divided_submeshes[curr_new_branch_idx],
                        branch_face_idx=new_limb_branch_face_idx[-1])

        # curr_limb_concept_network_dicts = [dict(starting_endpoints=endpoints,
        #                                        starting_node=curr_starting_branch_idx,
        #                                        starting_soma=soma_idx,
        #                                        starting_coordinate=closest_endpoint)]
        curr_limb_concept_network_dicts = {soma_idx:curr_limb_concept_network}

        new_limb_obj = neuron.Limb(mesh = curr_new_limb_mesh,
                                   curr_limb_correspondence=curr_limb_correspondence,
                                   concept_network_dict=curr_limb_concept_network_dicts)
        new_limb_obj.all_concept_network_data = nru.compute_all_concept_network_data_from_limb(current_neuron,new_limb_obj)

        new_limbs.append(new_limb_obj)
        #new_limb_dict[curr_new_branch_idx]["curr_starting_branch_idx"] = new_limb_obj.current_starting_node
        
    return new_limbs

In [106]:
def recursive_limb_splitting(current_neuron,curr_limb,significant_skeleton_threshold=30000,
                            print_flag=False):
    """
    Purpose: To split the a limb as many times as needed if connected at the soma
    
    Pseudocode:
    1) Get all the somas that the limb is attached to (from all_concept_network_data)
    2) For each soma it is attached to, check if it needs to be split:
    
    If yes:
    a. Split the limb into its parts for that soma
    b. Compute the all_concept_network_data for all of the split limbs
    c. Start loop where send all of the limb objects through function and collect results
    d. concatenate results and return
    
    if No: 
    - continue to next soma
    
    if No and the last soma
    - return the limb object
    
    Arguments:
    1) Limb
    2) Soma
    
    Example: 
    ex_limb = current_neuron[2]
    split_limbs = recursive_limb_splitting(current_neuron,ex_limb)

    color_choices = ["red","black"]
    sk.graph_skeleton_and_mesh(other_meshes=[split_limbs[0].mesh,split_limbs[1].mesh],
                               other_meshes_colors=color_choices,
                               other_skeletons=[split_limbs[0].skeleton,split_limbs[1].skeleton],
                               other_skeletons_colors=color_choices)
    """

    #1) Get all the somas that the limb is attached to (from all_concept_network_data)
    total_somas_idx = curr_limb.touching_somas()
    total_soams_meshes = [current_neuron.concept_network.nodes[nru.soma_label(k)]["data"].mesh for k in total_somas_idx]
    
    if print_flag:
        print(f"total_somas_idx = {total_somas_idx}")
        print(f"total_soams_meshes = {total_soams_meshes}")
    
    #2) For each soma it is attached to, check if it needs to be split:
    for soma_idx,curr_soma_mesh in zip(total_somas_idx,total_soams_meshes):
        
        cut_coordinate = check_if_branch_needs_splitting(
                                   current_neuron,curr_limb,soma_idx,curr_soma_mesh,
                                   significant_skeleton_threshold=significant_skeleton_threshold,
                                   print_flag=print_flag)
        if print_flag:
            print(f"cut_coordinate = {cut_coordinate}")
        
        # If No then continue to next soma
        if cut_coordinate is None:
            continue
            
        #If yes:
        #a. Split the limb into its parts for that soma and
        #b. Compute the all_concept_network_data for all of the split limbs
        
        if print_flag:
            split_limb_objs = split_limb_on_soma(current_neuron,curr_limb,soma_idx,curr_soma_mesh,
                                                 cut_coordinate=cut_coordinate,
                                                print_flag=print_flag)
        else:
            with su.suppress_stdout_stderr():
                split_limb_objs = split_limb_on_soma(current_neuron,curr_limb,soma_idx,curr_soma_mesh,
                                                 cut_coordinate=cut_coordinate,
                                                print_flag=print_flag)
        
        if print_flag:
            print(f"split_limb_objs = {split_limb_objs}")
        
        total_split_limbs = []
        for split_limb in split_limb_objs:
            curr_results = recursive_limb_splitting(current_neuron,curr_limb=split_limb,
                                     significant_skeleton_threshold=significant_skeleton_threshold,
                                    print_flag=print_flag)
            total_split_limbs = total_split_limbs + curr_results
        return total_split_limbs
        
    #If Did not need to split any of then return the current limb
    if print_flag:
        print("Hit Recursive return point and returning limb")
    return [curr_limb]


# Part that will run limb splitting for all the limbs in the neuron 

In [114]:
neuron = reload(neuron)
current_neuron = neuron.Neuron(current_neuron)

Recieved another instance of Neuron class in init -- so just copying data


# How to run it with the Neuron Object Available

In [115]:
"""
will map the [limb_idx AS A NUMBER][branch_idx] to 
dict_keys(['branch_skeleton', 'width_from_skeleton', 'branch_mesh', 'branch_face_idx'])
"""
new_limb_correspondence = dict() 
"""
Maps Soma to who they are connected to
Ex: {0: [0, 1, 3, 4, 5, 9], 1: [1, 2, 6, 7, 8]}
"""
new_soma_to_piece_connectivity = dict([(k,[]) for k in current_neuron.get_soma_node_names(int_label=True)])

"""
Just a list that will hold all of the meshes
"""
new_limb_meshes = []

"""
a dictionary that maps the limb_idx to a dictionary mapping the soma_idx to the concept map
{0:{0:Graph},
 1:{0:Graph,1:Graph},
 2:{1:Graph}....}
 
** can easily get this from the limb property concept_network_data_by_soma
"""
new_limb_concept_networks = dict()



"""
Pseudocode: 
Iterate through each split limb
1) Get all of the split limbs from that one limb
For each limb :
-look at the current length of the new_limb_meshes to get the current index for limb
a) Add a new entry in the new_limb_correspondence by iterating over the branches
b) get the somas that touch the limb and add CURRENT INDEX them to the new_soma_to_piece_connectivity dictionary
c) Add the limb mesh to new_limb_meshes
d) Use the concept_network_data_by_soma attribute to get the concept_network dictionary and add to 
    new_limb_concept_networks
"""

for limb_idx in current_neuron.get_limb_node_names(return_int=True):
    print(f"\n----- Working on Limb {limb_idx}--------")
    print(type(limb_idx))
    curr_limb = current_neuron[limb_idx]
    split_limbs = recursive_limb_splitting(current_neuron,curr_limb)
    
    print(f"Found {len(split_limbs)} limbs after limb slit")
    
    for sp_limb in split_limbs:
        #-look at the current length of the new_limb_meshes to get the current index for limb
        new_limb_idx = len(new_limb_meshes)
        #a) Add a new entry in the new_limb_correspondence by iterating over the branches
        new_limb_correspondence[new_limb_idx] = dict()
        for curr_branch_idx in sp_limb.get_branch_names():
            curr_branch = sp_limb[curr_branch_idx]
            new_limb_correspondence[new_limb_idx] = dict(
                                                    branch_skeleton = curr_branch.skeleton,
                                                    width_from_skeleton=curr_branch.width,
                                                    branch_mesh=curr_branch.mesh,
                                                    branch_face_idx=curr_branch.mesh_face_idx)
        #b) get the somas that touch the limb and add CURRENT INDEX them to the new_soma_to_piece_connectivity dictionary
        touching_somas = sp_limb.touching_somas()
        for s in touching_somas:
            new_soma_to_piece_connectivity[s].append(new_limb_idx)
        
        #c) Add the limb mesh to new_limb_meshes
        new_limb_meshes.append(sp_limb.mesh)
        
        #d) Use the concept_network_data_by_soma attribute to get the concept_network dictionary and add to 
        #new_limb_concept_networks
        new_limb_concept_networks[new_limb_idx] = sp_limb.concept_network_data_by_soma
        
            


----- Working on Limb 0--------
<class 'int'>
Hit Recursive return point and returning limb
Found 1 limbs after limb slit

----- Working on Limb 1--------
<class 'int'>
Hit Recursive return point and returning limb
Found 1 limbs after limb slit

----- Working on Limb 2--------
<class 'int'>
Hit Recursive return point and returning limb
Hit Recursive return point and returning limb
Found 2 limbs after limb slit

----- Working on Limb 3--------
<class 'int'>
Hit Recursive return point and returning limb
Found 1 limbs after limb slit

----- Working on Limb 4--------
<class 'int'>
Hit Recursive return point and returning limb
Found 1 limbs after limb slit

----- Working on Limb 5--------
<class 'int'>
Hit Recursive return point and returning limb
Found 1 limbs after limb slit

----- Working on Limb 6--------
<class 'int'>
Hit Recursive return point and returning limb
Found 1 limbs after limb slit

----- Working on Limb 7--------
<class 'int'>
Hit Recursive return point and returning limb


# Create the preprocessed data and make a neuron out of it