In [ ]:
"""
Purpose: To Create a function that labels a limb/branches as
apical or not

Pseudocode:
For all of the limbs (that contact the soma above the x % of height of the soma)
1) Get all of the unique skeleton paths that are x distance away from starting coordinate
2) Measure the dot product of that skeleton endpoint and the starting point with the direction towards layer one
3) Only keep limbs that have at least one skeleton path that is close enough to the layer one direction

--- should have 0,1 or multiple branches survive

If have multiple (have option to find one or multiple)

a) If find multiple:
1) find the branch path along that optimal y direction skeleton path
2) measure the widths of these branch paths
3) Keep if above a certain width threshold

b) If only one:
1) Pick the one with the highest width

*** should have a MINIMUM WIDTH AND IF NONE MEET IT THEN 0 APICALS


"""




In [1]:
from os import sys
sys.path.append("/meshAfterParty/")
#sys.path.append("../../meshAfterParty/meshAfterParty")

In [2]:
from importlib import reload
import os
from pathlib import Path
os.getcwd()

import neuron_utils as nru
nru = reload(nru)
import neuron
neuron=reload(neuron)
import neuron_visualizations as nviz
import time
import system_utils as su

In [3]:
nru = reload(nru)
current_file = "/notebooks/test_neurons/meshafterparty_processed/12345_double_soma_meshafterparty"
neuron_obj = nru.decompress_neuron(filepath=current_file,
                                  original_mesh=current_file,
                                  minimal_output=False)


Inside decompress neuron and decomposition_type = meshafterparty
Passed faces original mesh check
Passed vertices original mesh check



********************************** generate_limb_concept_networks_from_global_connectivity****************************


------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 68 len(curr_limb_divided_skeletons) = 68
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.3609600067138672
touching_pieces = [44]
Total time for mesh connectivity = 0.7153425216674805
Using touching_pieces[0] = 44
inside inner loop len(curr_limb_divided_skeletons) = 68
closest_endpoint WITH NEW KDTREE METHOD= [754770.2 950773.4 873485.9]
About to send touching_soma_vertices = [[758199.2 951673.5 875799.4]
 [756978.4 951254.  871233.8]
 [759524.8 951280.8 873206.6]
 [758907.  950977.6 871911.2]
 [759144.8 950937.4 872043.8]
 [759478.2 951371.6 873044.1]
 [758809.2 951824.5 875252.6]
 [758136.8 951401.1 875848.1]
 [757570.2 951200.8 876043. ]
 [759325.8 951924.6 874210.1]
 [759424.8 951622.7 873907.9]
 [754846.4 950863.9 872870.1]
 [754770.2 950773.4 873485.9]
 [759

Local time for concept mapping = 1.637556791305542


------Working on limb 1 -------
inside loop len(curr_limb_divided_meshes) = 49 len(curr_limb_divided_skeletons) = 49
Merge limb detected
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.2210559844970703
touching_pieces = [11]
Total time for mesh connectivity = 0.19617533683776855
Using touching_pieces[0] = 11
inside inner loop len(curr_limb_divided_skeletons) = 49
closest_endpoint WITH NEW KDTREE METHOD= [763677.2 960913.9 879506.8]
About to send touching_soma_vertices = [[764369.4 961579.  877947.4]
 [763335.2 961687.8 879612.2]
 [763925.8 960916.3 879439.4]
 [763378.6 961830.4 878169.8]
 [764348.  960489.9 878697.4]
 [763189.8 961895.4 879268.1]
 [764502.8 960665.2 878480.4]
 [763201.2 961529.1 879621.8]
 [763385.6 961419.9 879647.8]
 [764359.6 961425.1 878059.9]
 [764093.4 960579.9 879224.1]
 [763293.6 961809.8 879253.9]
 [763290.2 961772.8 879492.6]
 [763181.  962043.1 879046.7]
 [764403.  960454.9 878

touching_pieces = [5]
Total time for mesh connectivity = 0.33587217330932617
Using touching_pieces[0] = 5
inside inner loop len(curr_limb_divided_skeletons) = 39
closest_endpoint WITH NEW KDTREE METHOD= [ 862103. 1002270.  879904.]
About to send touching_soma_vertices = [[865523.6 999041.2 866004.2]
 [864669.2 997565.4 867472.4]
 [865488.4 998225.1 866958.1]
 [863506.4 997662.8 866843.4]
 [866137.  998252.4 866470.2]
 [865453.2 997977.9 867053.9]
 [864429.2 997518.6 867434.7]
 [866863.  998992.9 865393.7]
 [865199.6 998034.2 867383.3]
 [863561.2 997473.6 867104.4]
 [866033.6 999128.2 865682.9]
 [865759.4 998132.1 866720.4]
 [866945.  998612.9 865674.1]
 [863560.2 997629.8 867095.6]
 [867097.6 998874.2 865659.1]
 [865883.6 998176.6 866616.4]
 [866690.4 998360.8 866153. ]
 [864810.8 997654.6 867551.6]
 [863735.6 997336.9 867139. ]
 [866705.2 998250.4 866050.2]
 [865045.2 998812.1 866446.1]
 [866201.2 999131.2 865597.8]
 [866947.6 998432.3 865845.1]
 [865130.6 997796.6 867426.5]
 [863470.

starting_node in concept map (that should match the starting edge) = 0
Total time for branches to concept conversion = 0.19541215896606445

Working on adding back the edges that were duplicates
Recovered touching vertices = {0: TrackedArray([[757928.4, 962502.2, 866083.1],
              [757431.2, 961958.1, 865624.8],
              [757241.2, 960809.8, 865940.9],
              [757409.6, 960733.9, 865987.2],
              [759607.8, 962760.3, 866627.8],
              [759926.4, 959992.1, 866323.6],
              [759242.6, 962667.4, 866284.2],
              [758284.6, 962591.1, 866085.4],
              [758735.2, 959915.7, 866344.1],
              [759006. , 962652.2, 866260.4],
              [757331.2, 960980.1, 865803.5],
              [759866.2, 962747.5, 866851.7],
              [757306.2, 961203.8, 865800.2],
              [757533.8, 962121.5, 865822.1],
              [759733.2, 959948. , 866322.7],
              [759543.2, 962752.3, 866723.1],
              [761295.4, 959925.6, 8

Local time for concept mapping = 0.7802255153656006


------Working on limb 5 -------
inside loop len(curr_limb_divided_meshes) = 11 len(curr_limb_divided_skeletons) = 11
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.061806440353393555
touching_pieces = [7]
Total time for mesh connectivity = 0.2940950393676758
Using touching_pieces[0] = 7
inside inner loop len(curr_limb_divided_skeletons) = 11
closest_endpoint WITH NEW KDTREE METHOD= [752584.6 964335.9 869329.8]
About to send touching_soma_vertices = [[752618.4 964281.4 869517. ]
 [750819.6 962859.9 869731.4]
 [751823.2 962800.2 868718.6]
 [753231.8 964522.2 868843.6]
 [750671.8 963090.7 869636.8]
 [751761.8 964135.9 870006.4]
 [752242.  963065.8 868199.2]
 [751957.6 962834.  868606.1]
 [752960.  964192.  868100. ]
 [752201.2 964167.2 869934.4]
 [751723.4 964079.1 870135.9]
 [750696.  963318.9 870114. ]
 [752639.4 963476.2 867820.1]
 [753131.  964304.4 868379.6]
 [752364.2 963106.6 868044.4]
 [750826.  96

touching_pieces = [1]
Total time for mesh connectivity = 0.21261858940124512
Using touching_pieces[0] = 1
inside inner loop len(curr_limb_divided_skeletons) = 21
closest_endpoint WITH NEW KDTREE METHOD= [867187. 993812. 851183.]
About to send touching_soma_vertices = [[866520.2 994194.9 851413.6]
 [866590.8 993467.2 851482.3]
 [866720.8 993395.2 851593.1]
 [867003.  994448.7 851361.9]
 [867435.4 993751.4 851440. ]
 [866814.2 993324.4 851636.4]
 [866880.2 993377.  851460.1]
 [866509.6 993902.  851326.9]
 [867343.6 993522.1 851571.4]
 [867232.2 994380.1 851377.3]
 [867451.8 993962.1 851439.8]
 [867401.8 993727.7 851663.9]
 [867388.2 994041.8 851495.8]
 [867133.1 993448.3 851721.9]
 [866572.5 993742.7 851234.4]
 [867344.1 994204.8 851431.9]
 [866617.1 993579.2 851340.3]
 [866778.7 994302.8 851286.6]
 [867056.5 993361.  851625.5]
 [867408.1 993916.  851669.5]]
Starting_edge inside branches_to_conept = [[867187. 993812. 851183.]
 [877071. 993135. 841685.]]
There were 1 duplication nodes fou

--- 3a) Finshed generating soma_meshes_face_idx: 1.1020915508270264
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 5422
xvfb-run -n 5422 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_988087.off -o /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_988087_poisson.off -s /notebooks/Platinum_Compartment/Apical/Poisson_temp/poisson_906514.mls


removed temporary input file: /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_988087.off
removed temporary output file: /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_988087_poisson.off
/notebooks/Platinum_Compartment/Apical/Poisson_temp/poisson_906514.mls is being deleted....
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 485
xvfb-run -n 485 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_655455.off -o /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_655455_poisson.off -s /notebooks/Platinum_Compartment/Apical/Poisson_temp/poisson_256954.mls


removed temporary input file: /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_655455.off
removed temporary output file: /notebooks/Platinum_Compartment/Apical/Poisson_temp/neuron_655455_poisson.off
/notebooks/Platinum_Compartment/Apical/Poisson_temp/poisson_256954.mls is being deleted....
--- 3) Finshed generating soma objects and adding them to concept graph: 18.140153884887695
--- 4a) Finshed generating curr_limb_meshes_face_idx: 3.5511398315429688
Inside the Limb constructor and concept_network_dict = {0: <networkx_utils.GraphOrderedEdges object at 0x7f300dadf9b0>}
concept_network_data = [{'starting_soma': 0, 'starting_node': 44, 'starting_endpoints': array([[754770.2, 950773.4, 873485.9],
       [756303. , 947334. , 874339. ]]), 'starting_coordinate': array([754770.2, 950773.4, 873485.9]), 'touching_soma_vertices': TrackedArray([[758199.2, 951673.5, 875799.4],
              [756978.4, 951254. , 871233.8],
              [759524.8, 951280.8, 873206.6],
              [75890

checking and resolving cycles
No cycles to fix
Inside the Limb constructor and concept_network_dict = {1: <networkx_utils.GraphOrderedEdges object at 0x7f3023c42358>}
concept_network_data = [{'starting_soma': 1, 'starting_node': 5, 'starting_endpoints': array([[ 862103., 1002270.,  879904.],
       [ 873682., 1032910.,  874304.]]), 'starting_coordinate': array([ 862103., 1002270.,  879904.]), 'touching_soma_vertices': TrackedArray([[865523.6, 999041.2, 866004.2],
              [864669.2, 997565.4, 867472.4],
              [865488.4, 998225.1, 866958.1],
              [863506.4, 997662.8, 866843.4],
              [866137. , 998252.4, 866470.2],
              [865453.2, 997977.9, 867053.9],
              [864429.2, 997518.6, 867434.7],
              [866863. , 998992.9, 865393.7],
              [865199.6, 998034.2, 867383.3],
              [863561.2, 997473.6, 867104.4],
              [866033.6, 999128.2, 865682.9],
              [865759.4, 998132.1, 866720.4],
              [866945. , 9

checking and resolving cycles
There are loops to resolve and 'no_cycles' parameters set requires us to fix eliminate them
Using mesh_widths for resolving loops
Inside the Limb constructor and concept_network_dict = {0: <networkx_utils.GraphOrderedEdges object at 0x7f3033e71ac8>}
concept_network_data = [{'starting_soma': 0, 'starting_node': 24, 'starting_endpoints': array([[748382. , 960577. , 880387. ],
       [750179.9, 961460.2, 879066.8]]), 'starting_coordinate': array([750179.9, 961460.2, 879066.8]), 'touching_soma_vertices': TrackedArray([[750899.2, 960779.2, 879791.8],
              [749568. , 959616. , 878860. ],
              [750936.8, 961249.3, 879241.2],
              [750732. , 961588.6, 879011.6],
              [749932.2, 961177.6, 878645.9],
              [749691. , 959599.1, 878750.5],
              [750683.2, 960326.9, 879914.5],
              [750666.2, 960107.2, 879884.8],
              [750816.4, 960543.8, 879870.8],
              [749434. , 959552. , 879127.8],
    

checking and resolving cycles
There are loops to resolve and 'no_cycles' parameters set requires us to fix eliminate them
Using mesh_widths for resolving loops
Inside the Limb constructor and concept_network_dict = {1: <networkx_utils.GraphOrderedEdges object at 0x7f3023c4ab00>}
concept_network_data = [{'starting_soma': 1, 'starting_node': 9, 'starting_endpoints': array([[850611., 997661., 835195.],
       [863014., 995271., 851325.]]), 'starting_coordinate': array([863014., 995271., 851325.]), 'touching_soma_vertices': TrackedArray([[863258.4, 994795.4, 851581.6],
              [862916.2, 994863.4, 851665.6],
              [862833.4, 995051.9, 851711.6],
              [863442.2, 995300.1, 851652.8],
              [863088.4, 994795.9, 851393.9],
              [863250. , 995375.4, 851838.9],
              [863393.4, 994948.1, 851497. ],
              [863056.3, 995379.6, 851889.9],
              [863104.3, 994755.2, 851653.2],
              [863371.7, 995357.5, 851744.3],
              

     Branch 11
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(2880, 3), faces.shape=(5685, 3))>
     Branch 12
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(2500, 3), faces.shape=(5012, 3))>
     Branch 13
     Branch 14
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(4392, 3), faces.shape=(8759, 3))>
     Branch 15
     Branch 16
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(3559, 3), faces.shape=(7173, 3))>
     Branch 17
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(5742, 3), faces.shape=(11494, 3))>
     Branch 18
     Branch 19
     Branch 20
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(2439, 3), faces.shape=(4854, 3))>
     Branch 21
     Branch 22
     Branch 23
     Branch 24
     Branch 25
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(878, 3), faces.shape=(1739, 3))>
     Branch 26
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(302, 3), faces.shape=(563, 3))>
     Branch 27
     Branch 28
     Branch 29
curr_branch.mesh = <trimesh.T

     Branch 30
     Branch 31
     Branch 32
     Branch 33
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(5371, 3), faces.shape=(10721, 3))>
Working on Limb 5:
     Branch 0
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(8641, 3), faces.shape=(17301, 3))>
     Branch 1
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(9223, 3), faces.shape=(18504, 3))>
     Branch 2
     Branch 3
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(55, 3), faces.shape=(104, 3))>
     Branch 4
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(8240, 3), faces.shape=(16523, 3))>
     Branch 5
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(9987, 3), faces.shape=(20023, 3))>
     Branch 6
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(3437, 3), faces.shape=(6802, 3))>
     Branch 7
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(2049, 3), faces.shape=(3994, 3))>
     Branch 8
curr_branch.mesh = <trimesh.Trimesh(vertices.shape=(2373, 3), faces.shape=(4658, 3))>
     Branch 9
curr_

In [ ]:
nviz.visualize_neuron(neuron_obj,
                      mesh_whole_neuron=True,
                     axis_box_off=False)

In [ ]:
"""
Conclusion for Apical: Heads in the y direction in the direction of y gettin gsmaller

"""

# Functions that coulld be useful to use:

# How to Split Starting Nodes Accidentally Grouped Together

In [ ]:
"""
Pseudocode:
For each limb

1) get the starting node:
a. Get the staring branch skeleton and find the closest skeleton point to the soma border
b. Get the limb skeleton, turn into graph and cut the graph at the skeleton point
c. Seperate the graph into 2 components, If there are 2 connected components after cut, are the connected components both significant

If No --> Move on to next limb

"""

In [4]:
import skeleton_utils as sk
from pykdtree.kdtree import KDTree
import trimesh_utils as tu
import numpy as np
import networkx_utils as xu
import compartment_utils as cu
import networkx as nx
import numpy_utils as nu

current_neuron = neuron_obj
distance_by_mesh_center = True
significant_skeleton_threshold = 30000

import general_utils as gu

In [5]:
neuron = reload(neuron)
current_neuron = neuron.Neuron(current_neuron)

Recieved another instance of Neuron class in init -- so just copying data


# Generating the Border if not already there

In [6]:
# import time

# start_time = time.time()
# tu = reload(tu)

# limb_to_soma_border_by_soma = dict()

# for soma_name in current_neuron.get_soma_node_names():
    
#     soma_idx = int(soma_name[1:])


#     curr_soma_mesh = current_neuron[nru.soma_label(soma_idx)].mesh
#     touching_limbs = current_neuron.get_limbs_touching_soma(soma_idx)
#     touching_limb_objs = [current_neuron[k] for k in touching_limbs]

#     touching_limbs_meshes = [k.mesh for k in touching_limb_objs]
#     touching_pieces,touching_vertices = tu.mesh_pieces_connectivity(main_mesh=current_neuron.mesh,
#                                             central_piece = curr_soma_mesh,
#                                             periphery_pieces = touching_limbs_meshes,
#                                                              return_vertices=True,
#                                                             return_central_faces=False,
#                                                                     print_flag=False
#                                                                                      )
#     limb_to_soma_border = dict([(k,v) for k,v in zip(np.array(touching_limbs)[touching_pieces],touching_vertices)])
#     limb_to_soma_border_by_soma[soma_idx] = limb_to_soma_border
# print(time.time() - start_time)

In [9]:
current_neuron.plot_soma_limb_concept_network()

In [24]:
curr_limb_idx = 2
soma_idx = 1
curr_soma_mesh = current_neuron.concept_network.nodes[nru.soma_label(soma_idx)]["data"].mesh
curr_limb = current_neuron[curr_limb_idx]

#1) get the starting node:
curr_starting_branch_idx = curr_limb.get_starting_branch_by_soma(soma_idx)
#a. Get the staring branch skeleton and find the closest skeleton point to the soma border
curr_branch = curr_limb[curr_starting_branch_idx]
curr_branch_sk = curr_branch.skeleton

#b. find the closest skeleton point to the soma border
curr_soma_border = curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
unique_skeleton_nodes = np.unique(curr_branch_sk.reshape(-1,3),axis=0)

curr_soma_border_kdtree = KDTree(curr_soma_border)
distances,closest_node = curr_soma_border_kdtree.query(unique_skeleton_nodes)
cut_coordinate = unique_skeleton_nodes[np.argmin(distances),:]

# # visualizing the cut coordinate
# sk.graph_skeleton_and_mesh(other_skeletons=[curr_limb.skeleton],
#                           other_scatter=[cut_coordinate.reshape(-1,3)],
#                           other_meshes=[curr_limb.mesh,current_neuron.concept_network.nodes[f"S{soma_idx}"]["data"].mesh],
#                           scatter_size=0.2)


#c. cut the limb skeleton at that point
curr_limb_sk_graph = sk.convert_skeleton_to_graph(curr_limb.skeleton)

node_to_cut = xu.get_nodes_with_attributes_dict(curr_limb_sk_graph,dict(coordinates=cut_coordinate))

if len(node_to_cut) != 1:
    raise Exception("Node to cut was not of length 1")
    
node_to_cut = node_to_cut[0]

#c. Seperate the graph into 2 components, If there are 2 connected components after cut, are the connected components both significant
curr_limb_sk_graph.remove_node(node_to_cut)

seperated_components = list(nx.connected_components(curr_limb_sk_graph))

if len(seperated_components) <= 1:
    raise Exception(f"Continue to next limb because number of seperated_components = {len(seperated_components)}")

#c1. Seperate the graph into subgraph based on components and output the skeletons from each
seperated_skeletons = [sk.convert_graph_to_skeleton(curr_limb_sk_graph.subgraph(k)) for k in seperated_components]
skeleton_lengths = np.array([sk.calculate_skeleton_distance(k) for k in seperated_skeletons])


n_significant_skeletons = np.sum(skeleton_lengths>significant_skeleton_threshold)
print(n_significant_skeletons)
print(skeleton_lengths)

if n_significant_skeletons < 2:
    raise Exception(f"Continue to next limb because n_significant_skeletons = {n_significant_skeletons} with lengths {skeleton_lengths}")

2
[903183.2968042  102050.59835136]


In [25]:
"""
If Yes
2) Slit the branch skeleton there, but give the split point to the shorter skeleton so only have to cut the edge
--> if split within 2 hops of the endpoint then make sure the split happens 2 hops away from endpoint
*** if limb skeleton is less than 4 skeleton points long then won't work

2b) Make sure the skeleton endpoints are divided into the two skeletons or else error

"""

"\nIf Yes\n2) Slit the branch skeleton there, but give the split point to the shorter skeleton so only have to cut the edge\n--> if split within 2 hops of the endpoint then make sure the split happens 2 hops away from endpoint\n*** if limb skeleton is less than 4 skeleton points long then won't work\n\n2b) Make sure the skeleton endpoints are divided into the two skeletons or else error\n\n"

In [26]:
# Finding the node to cut on the branch skeleton
curr_branch_sk_graph = sk.convert_skeleton_to_graph(curr_branch_sk)

node_to_cut = xu.get_nodes_with_attributes_dict(curr_branch_sk_graph,dict(coordinates=cut_coordinate))
if len(node_to_cut) != 1:
    raise Exception("Node to cut was not of length 1")
    
node_to_cut = node_to_cut[0]

"""
All the scenarios for where the cut could be:

1) Find which endpoint it is closer to (this is the one it will get stuck onto)
2) If it is the endpoint then back it up one
3) cut the edge on the path to the other endpoint
4) Divided into connected components
5) export the graphs of the connected components



Testing of the Algorithm that slits the paths: 
import networkx as nx
G = nx.from_edgelist([(1,2),(2,3),(3,4),(4,5)])
node_to_cut = 1

endpoint_nodes = xu.get_nodes_of_degree_k(G,1)
paths_to_endpt = [nx.dijkstra_path(G,node_to_cut,k) for k in endpoint_nodes]
path_lengths = np.array([len(k) for k in paths_to_endpt])
closest_endpoint = np.argmin(path_lengths)
farthest_endpoint = 1 - closest_endpoint
closest_endpoint_len = path_lengths[closest_endpoint]

if closest_endpoint_len <= 1:
    #need to readjust the node_to_cut and paths
    print("Having to readjust endpoint")
    node_to_cut = paths_to_endpt[farthest_endpoint][1]
    paths_to_endpt = [nx.dijkstra_path(G,node_to_cut,k) for k in endpoint_nodes]

#generate the subnode in each graph
paths_to_endpt[farthest_endpoint].remove(node_to_cut)

subgraph_list = [G.subgraph(k) for k in paths_to_endpt]


import matplotlib.pyplot as plt
for s in subgraph_list:
    nx.draw(s,with_labels=True)
    plt.show()
"""

G = curr_branch_sk_graph
endpoint_nodes = xu.get_nodes_of_degree_k(G,1)
endpoint_nodes_coord = xu.get_node_attributes(curr_branch_sk_graph,node_list=endpoint_nodes)
paths_to_endpt = [nx.dijkstra_path(G,node_to_cut,k) for k in endpoint_nodes]
path_lengths = np.array([len(k) for k in paths_to_endpt])
closest_endpoint = np.argmin(path_lengths)
farthest_endpoint = 1 - closest_endpoint
closest_endpoint_len = path_lengths[closest_endpoint]

if closest_endpoint_len <= 1:
    #need to readjust the node_to_cut and paths
    print("Having to readjust endpoint")
    node_to_cut = paths_to_endpt[farthest_endpoint][1]
    paths_to_endpt = [nx.dijkstra_path(G,node_to_cut,k) for k in endpoint_nodes]

#generate the subnode in each graph
paths_to_endpt[farthest_endpoint].remove(node_to_cut)

subgraph_list = [G.subgraph(k) for k in paths_to_endpt]

starting_endpoints = xu.get_node_attributes(curr_branch_sk_graph,node_list=[k[0] for k in paths_to_endpt])


#export the skeletons of the subgraphs
exported_skeletons = [sk.convert_graph_to_skeleton(s) for s in subgraph_list]
endpoint_nodes_coord #will have the endpoints belonging to each split



"""
Checking that got the right output:

sk.graph_skeleton_and_mesh(other_meshes=[curr_branch.mesh],
                           other_meshes_colors=["red","black"],
                          other_skeletons=exported_skeletons,
                          other_skeletons_colors=["red","black"],
                          other_scatter=[endpoint_nodes_coord[0].reshape(-1,3),endpoint_nodes_coord[1].reshape(-1,3),
                                          starting_endpoints[0].reshape(-1,3),starting_endpoints[1].reshape(-1,3)],
                           other_scatter_colors=["red","black","red","black"],
                          )

[k.shape for k in exported_skeletons]
"""



'\nChecking that got the right output:\n\nsk.graph_skeleton_and_mesh(other_meshes=[curr_branch.mesh],\n                           other_meshes_colors=["red","black"],\n                          other_skeletons=exported_skeletons,\n                          other_skeletons_colors=["red","black"],\n                          other_scatter=[endpoint_nodes_coord[0].reshape(-1,3),endpoint_nodes_coord[1].reshape(-1,3),\n                                          starting_endpoints[0].reshape(-1,3),starting_endpoints[1].reshape(-1,3)],\n                           other_scatter_colors=["red","black","red","black"],\n                          )\n\n[k.shape for k in exported_skeletons]\n'

In [27]:
"""
3) Do Mesh correspondnece to get new branch meshes for the split skeleton
- where have to do face resolving as well
4) Check that both of the meshes are touching the soma
5) If one of them is not touching the soma
--> do water growing algorithm until it is

"""

div_st_branch_face_corr = []
div_st_branch_width = []
for sub_sk in exported_skeletons:
    curr_branch_face_correspondence, width_from_skeleton = cu.mesh_correspondence_adaptive_distance(sub_sk,
                                              curr_branch.mesh,
                                             skeleton_segment_width = 1000,
                                             distance_by_mesh_center=distance_by_mesh_center)
    div_st_branch_face_corr.append(curr_branch_face_correspondence)
    div_st_branch_width.append(width_from_skeleton)
    
#now need to resolve the 
    

INSIDE GET SKELETAL DISTANCE distance_by_mesh_center = True



INSIDE GET SKELETAL DISTANCE distance_by_mesh_center = True



INSIDE GET SKELETAL DISTANCE distance_by_mesh_center = True



INSIDE GET SKELETAL DISTANCE distance_by_mesh_center = True


In [28]:

"""
OLD WAY BEFORE PUT INTO A FUNCTION

no_missing_labels = [0,1]
#set up the face dictionary
face_lookup = dict([(j,[]) for j in range(0,len(curr_branch.mesh.faces))])


for j,curr_faces_corresponded in enumerate(div_st_branch_face_corr):
    for c in curr_faces_corresponded:
        face_lookup[c].append(j)
        
original_labels = gu.get_unique_values_dict_of_lists(face_lookup)
print(f"max(original_labels),len(original_labels) = {(max(original_labels),len(original_labels))}")


if len(original_labels) != len(no_missing_labels):
    raise Exception(f"len(original_labels) != len(no_missing_labels) for original_labels = {len(original_labels)},no_missing_labels = {len(no_missing_labels)}")

if max(original_labels) + 1 > len(original_labels):
    raise Exception("There are some missing labels in the initial labeling")



#here is where can call the function that resolves the face labels
face_coloring_copy = cu.resolve_empty_conflicting_face_labels(
                 curr_limb_mesh = curr_branch.mesh,
                 face_lookup=face_lookup,
                 no_missing_labels = list(original_labels)
)

divided_submeshes,divided_submeshes_idx = tu.split_mesh_into_face_groups(curr_branch.mesh,face_coloring_copy)
divided_submeshes = list(divided_submeshes.values())"""

cu = reload(cu)
divided_submeshes,divided_submeshes_idx = cu.groups_of_labels_to_resolved_labels(current_mesh = curr_branch.mesh,
                                      face_correspondence_lists=div_st_branch_face_corr)


"""
Checking that the subdivision did well:

# checking the division

sk.graph_skeleton_and_mesh(other_meshes=list(divided_submeshes),
                           other_meshes_colors=["black","red"],
                          other_skeletons=exported_skeletons,
                          other_skeletons_colors=["black","red"],)


"""


max(original_labels),len(original_labels) = (1, 2)
empty_indices % = 0.07742102537545313
 conflict_indices % = 0.0


'\nChecking that the subdivision did well:\n\n# checking the division\n\nsk.graph_skeleton_and_mesh(other_meshes=list(divided_submeshes),\n                           other_meshes_colors=["black","red"],\n                          other_skeletons=exported_skeletons,\n                          other_skeletons_colors=["black","red"],)\n\n\n'

# --- Make sure that both new meshes are touching the soma , if not then resolve

# ----- This is where intentionally make it not touching -----

In [29]:
"""
The example waterfilling algorithm

Pseudocode: 
0) Turn the mesh into a graph
*****************
1) Get the nodes that represent the border
How to do this:
- have the vertices that are at the border

a. Track vertices to faces
b. If know the face number then that is the node number

******************
1) Get all faces (nodes) of the mesh to be expanded

For each iteration: 
2) Get the neighbors of all the faces, concatenate and make unique
3) Make them the new face labels
4) check to see if multiple border nodes in that face group
--> If not then continue to next iteration

"""
label_to_expand = 1
tu = reload(tu)

#0) Turn the mesh into a graph
total_mesh_graph = nx.from_edgelist(curr_branch.mesh.face_adjacency)

#1) Get the nodes that represent the border
border_vertices =  curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
border_faces = tu.vertices_coordinates_to_faces(curr_branch.mesh,border_vertices)

label_face_idx = divided_submeshes_idx[label_to_expand]

final_faces = label_face_idx.copy()

for i in range(0,40):
    final_faces = np.unique(np.concatenate([xu.get_neighbors(total_mesh_graph,k) for k in final_faces]))

other_mesh_faces = np.setdiff1d(np.arange(0,len(curr_branch.mesh.faces)),final_faces)

In [30]:
divided_submeshes_idx = [other_mesh_faces,final_faces]
divided_submeshes = [curr_branch.mesh.submesh([k],append=True) for k in divided_submeshes_idx]

In [31]:
sk.graph_skeleton_and_mesh(other_meshes=list(divided_submeshes),
                           other_meshes_colors=["black","red"],
                          other_skeletons=exported_skeletons,
                          other_skeletons_colors=["black","red"],)

# ---- End of Intentionally Making it Not touching ---- 

In [32]:
# doing the check

touching_pieces,touching_pieces_verts = tu.mesh_pieces_connectivity(main_mesh=tu.combine_meshes([curr_branch.mesh,curr_soma_mesh]),
                           central_piece=curr_soma_mesh,
                           periphery_pieces=divided_submeshes,
                           merge_vertices=True,
                            return_vertices=True,
                           print_flag=False)
touching_pieces
    

[1]

# --- Now doing waterfill expansion until touching

In [33]:
touching_pieces

[1]

In [34]:
if len(touching_pieces) == 0:
    raise Exception("There were none of the new meshes that were touching the soma")
if len(touching_pieces) < 2:
    #find which piece was not touching
    label_to_expand = 1 - touching_pieces[0]
    print(f"new_mesh {label_to_expand} was not touching the mesh so need to expand until touches soma")
    
    #0) Turn the mesh into a graph
    total_mesh_graph = nx.from_edgelist(curr_branch.mesh.face_adjacency)

    #1) Get the nodes that represent the border
    border_vertices =  curr_limb.get_concept_network_data_by_soma(soma_idx)["touching_soma_vertices"]
    border_faces = set(tu.vertices_coordinates_to_faces(curr_branch.mesh,border_vertices))

    label_face_idx = divided_submeshes_idx[label_to_expand]

    final_faces = label_face_idx.copy()

    n_touching_soma = 0
    counter = 0
    while n_touching_soma < 10:
        final_faces = np.unique(np.concatenate([xu.get_neighbors(total_mesh_graph,k) for k in final_faces]))
        n_touching_soma = len(border_faces.intersection(set(final_faces)))
        counter+= 1
        
    
    other_mesh_faces = np.setdiff1d(np.arange(0,len(curr_branch.mesh.faces)),final_faces)
    
    


    print(f"Took {counter} iterations to expand the label back")
    
    divided_submeshes_idx[label_to_expand] = final_faces
    divided_submeshes_idx[touching_pieces[0]] = other_mesh_faces
    
    #Need to fix the labels one more time to make sure the expansion did not cut off one of the labels
    print(f"divided_submeshes_idx = {divided_submeshes_idx}")
    divided_submeshes,divided_submeshes_idx = cu.groups_of_labels_to_resolved_labels(curr_branch.mesh,divided_submeshes_idx)
    
    print(f"divided_submeshes_idx = {divided_submeshes_idx}")
    
    divided_submeshes = [curr_branch.mesh.submesh([k],append=True) for k in divided_submeshes_idx]
    
    #recalculate the border vertices and the list should be 2
    touching_pieces,touching_pieces_verts = tu.mesh_pieces_connectivity(main_mesh=tu.combine_meshes([curr_branch.mesh,curr_soma_mesh]),
                           central_piece=curr_soma_mesh,
                           periphery_pieces=divided_submeshes,
                           merge_vertices=True,
                            return_vertices=True,
                           print_flag=False)
    if len(touching_pieces) != 2:
        raise Exception(f"Number of touching pieces not equal to 2 even after correction: {touching_pieces}")

soma_border_verts = touching_pieces_verts

sk.graph_skeleton_and_mesh(other_meshes=list(divided_submeshes),
                           other_meshes_colors=["black","red"],
                          other_skeletons=exported_skeletons,
                          other_skeletons_colors=["black","red"],
                          other_scatter=[endpoint_nodes_coord[0].reshape(-1,3),endpoint_nodes_coord[1].reshape(-1,3)],
                           other_scatter_colors=["black","red"],
                          scatter_size=1)


new_mesh 0 was not touching the mesh so need to expand until touches soma
Took 21 iterations to expand the label back
divided_submeshes_idx = [array([   0,    1,    2, ..., 6221, 6222, 6223]), array([  15,   17,   22, ..., 7721, 7722, 7723])]
max(original_labels),len(original_labels) = (1, 2)
empty_indices % = 0.0
 conflict_indices % = 0.0



divided_submeshes_idx = [array([   0,    1,    2, ..., 6221, 6222, 6223]), array([  15,   17,   22, ..., 7721, 7722, 7723])]


In [35]:
# check that the mesh can't be split
for j,sub in enumerate(divided_submeshes):
    c_mesh,c_indic = tu.split(sub)
    if len(c_mesh) > 1:
        raise Exception(f"New Mesh {j} had {len(c_mesh)} pieces after split")

# Now need to reorganize the concept network

In [36]:
"""
6) Reorganize all branches and concept networks into two seperate limbs
Key is to find which connections belong to which new starting branch

a. Get all the neighboring nodes to the original starting branch
b. Sort the neighbors into group A or B depending on which endpoint their branches match
c. Take the concept network and delete the starting branch
d. Take the connected components and divide into group A or B depending on which 
neighbor node they have in them
e. Send A and B to the concept network formation function
"""

'\n6) Reorganize all branches and concept networks into two seperate limbs\nKey is to find which connections belong to which new starting branch\n\na. Get all the neighboring nodes to the original starting branch\nb. Sort the neighbors into group A or B depending on which endpoint their branches match\nc. Take the concept network and delete the starting branch\nd. Take the connected components and divide into group A or B depending on which \nneighbor node they have in them\ne. Send A and B to the concept network formation function\n'

In [37]:
neighbors_to_starting_node = xu.get_neighbors(curr_limb.concept_network,curr_starting_branch_idx)

"""
sk.graph_skeleton_and_mesh(other_meshes=[curr_limb[k].mesh for k in neighbors_to_starting_node + [curr_starting_branch_idx]],
                          other_meshes_colors="random")
"""
#find out which 

'\nsk.graph_skeleton_and_mesh(other_meshes=[curr_limb[k].mesh for k in neighbors_to_starting_node + [curr_starting_branch_idx]],\n                          other_meshes_colors="random")\n'

In [38]:
match=dict([(k,[]) for k in neighbors_to_starting_node])
for ex_neighbor in neighbors_to_starting_node:
    ex_neighbor_branch = curr_limb[ex_neighbor]
    for j,endpt in enumerate(endpoint_nodes_coord):
        if len(nu.matching_rows(ex_neighbor_branch.endpoints,endpt))>0:
            match[ex_neighbor].append(j)
            
#make sure that there was only one match
for k,v in match.items():
    if len(v) != 1:
        raise Exception(f"Neighbor {k} did not have one matching but instead had {v}")

In [39]:
import copy
concept_network_copy = copy.deepcopy(curr_limb.concept_network)
concept_network_copy.remove_node(curr_starting_branch_idx)
concept_conn_comp = list(nx.connected_components(concept_network_copy))

#divide up the connected components into the groups they belong to
new_branch_groups = [[],[]]
for c in concept_conn_comp:
    #find the matching neighbor in that
    matching_neighbor = c.intersection(set(neighbors_to_starting_node))
    if len(matching_neighbor) != 1:
        raise Exception(f"matching_neighbor was not size 1 : {matching_neighbor}")
    matching_neighbor = list(matching_neighbor)[0]
    new_branch_groups[match[matching_neighbor][0]].extend(list(c))

#check that the lists are not empty
for i,g in enumerate(new_branch_groups):
    if len(g) == 0:
        raise Exception(f"New branch group {i} was empty after dividing the rest of the nodes")

new_branch_groups

[[0,
  1,
  2,
  3,
  4,
  6,
  7,
  8,
  9,
  10,
  11,
  14,
  16,
  17,
  18,
  19,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38],
 [12, 13, 15, 20, 21, 22]]

# ----- Visualize and make sure the limb was divided correctly -----

In [40]:
divided_neighbor_meshes = [tu.combine_meshes([curr_limb[k].mesh for k in curr_group]) for curr_group in new_branch_groups]
divided_neighbor_meshes_with_original = [tu.combine_meshes([k,v]) for k,v in zip(divided_neighbor_meshes,divided_submeshes)]
#sk.graph_skeleton_and_mesh(other_meshes=)
sk.graph_skeleton_and_mesh(other_meshes=divided_neighbor_meshes_with_original,
                          other_meshes_colors=["black","red"],
                          other_skeletons=exported_skeletons,
                          other_skeletons_colors=["black","red"],
                          other_scatter=[endpoint_nodes_coord[0].reshape(-1,3),endpoint_nodes_coord[1].reshape(-1,3)],
                           other_scatter_colors=["black","red"],)

# ---- Lets put everything we have together into a new concept network (to make up a limb) ----

In [41]:
"""
Inventoring what we have


"""
new_branch_groups #how the existing concept_network should be divided up...
exported_skeletons #the divided up skeletons
starting_endpoints #the endpoints for each of the new meshes
divided_submeshes,divided_submeshes_idx #The mesh information (in reference to the branch and not the entire limb)
soma_idx #The soma it is touching
curr_soma_mesh
div_st_branch_width #the widths associated with them


# what we need for it to run the limb seperation
soma_border_verts #The soma border for these
curr_starting_branch_idx


5

# * * Final Step Before Recursion: Creating the New Limb Objects * *

In [42]:
curr_limb.concept_network.nodes[1]

{'endpoints': array([[ 851224., 1010100.,  885410.],
        [ 863960., 1005150.,  884678.]]),
 'data': <neuron.Branch at 0x7f3019b1ab70>}

# Creating the New concept network and New Mesh

In [43]:
new_limb_dict = dict()
for curr_new_branch_idx in range(len(new_branch_groups)):
    print(f"\n--- Working on new limb {curr_new_branch_idx} -------")
    new_limb_dict[curr_new_branch_idx] = dict()
    #new_limb_dict[curr_new_branch_idx]["soma_border_verts"] = soma_border_verts[curr_new_branch_idx]
    
    # a) Creating the new concept network
    curr_limb_divided_skeletons =  [curr_limb[k].skeleton for k in new_branch_groups[curr_new_branch_idx]] + [exported_skeletons[curr_new_branch_idx]]
    closest_endpoint = starting_endpoints[curr_new_branch_idx]
    endpoints = neuron.Branch(exported_skeletons[curr_new_branch_idx]).endpoints
    curr_limb_concept_network = nru.branches_to_concept_network(curr_limb_divided_skeletons,closest_endpoint,np.array(endpoints).reshape(-1,3),
                                        touching_soma_vertices= soma_border_verts[curr_new_branch_idx])

    #Run some checks on the new concept network developed
    curr_starting_branch_idx= nru.check_concept_network(curr_limb_concept_network,closest_endpoint = closest_endpoint,
                              curr_limb_divided_skeletons=curr_limb_divided_skeletons,print_flag=True)[0]
    
    # b) Creating the new mesh

    """Old way: 
    remaining_meshes_faces_idx =  [curr_limb[k].mesh_face_idx for k in new_branch_groups[curr_new_branch_idx]]
    remaining_meshes_faces_idx.append(np.array(curr_branch.mesh_face_idx[divided_submeshes_idx[curr_new_branch_idx]]))
    """

    new_limb_branch_face_idx = []
    remaining_meshes_face_idx = []
    total_face_count = 0
    for k in new_branch_groups[curr_new_branch_idx]:
        curr_face_idx  = curr_limb[k].mesh_face_idx
        remaining_meshes_face_idx.append(curr_face_idx)
        new_limb_branch_face_idx.append(np.arange(total_face_count,total_face_count+len(curr_face_idx)))
        total_face_count += len(curr_face_idx)

    last_face_idx = np.array(curr_branch.mesh_face_idx[divided_submeshes_idx[curr_new_branch_idx]])
    remaining_meshes_face_idx.append(last_face_idx)
    new_limb_branch_face_idx.append(np.arange(total_face_count,total_face_count+len(last_face_idx)))


    final_remaining_faces = np.concatenate(remaining_meshes_face_idx)                         
    curr_new_limb_mesh = curr_limb.mesh.submesh([final_remaining_faces],append=True,repair=False)

    """
    Checking that it went well:
    reovered_mesh = curr_new_limb_mesh.submesh([new_limb_branch_face_idx[2]],append=True,repair=False)
    original_mesh = curr_limb[new_branch_groups[curr_new_branch_idx][2]].mesh
    reovered_mesh,original_mesh
    """
    
    curr_limb_correspondence = dict()
    for j,neighb in enumerate(new_branch_groups[curr_new_branch_idx]):
        #calculate the new mesh correspondence
        curr_limb_correspondence[j] = dict(branch_skeleton = curr_limb[neighb].skeleton,
                                          width_from_skeleton = curr_limb[neighb].width,
                                          branch_mesh=curr_limb[neighb].mesh,
                                          branch_face_idx=new_limb_branch_face_idx[j])
    #add on the new mesh
    curr_limb_correspondence[len(new_branch_groups[curr_new_branch_idx])] = dict(
                    branch_skeleton = exported_skeletons[curr_new_branch_idx],
                    width_from_skeleton = div_st_branch_width[curr_new_branch_idx],
                    branch_mesh=divided_submeshes[curr_new_branch_idx],
                    branch_face_idx=new_limb_branch_face_idx[-1])

    # curr_limb_concept_network_dicts = [dict(starting_endpoints=endpoints,
    #                                        starting_node=curr_starting_branch_idx,
    #                                        starting_soma=soma_idx,
    #                                        starting_coordinate=closest_endpoint)]
    curr_limb_concept_network_dicts = {soma_idx:curr_limb_concept_network}
    
    new_limb_obj = neuron.Limb(mesh = curr_new_limb_mesh,
                               curr_limb_correspondence=curr_limb_correspondence,
                               concept_network_dict=curr_limb_concept_network_dicts)
    new_limb_obj.all_concept_network_data = nru.compute_all_concept_network_data_from_limb(current_neuron,new_limb_obj)

    new_limb_dict[curr_new_branch_idx]["limb_obj"] = new_limb_obj
    #new_limb_dict[curr_new_branch_idx]["curr_starting_branch_idx"] = new_limb_obj.current_starting_node


--- Working on new limb 0 -------
Starting_edge inside branches_to_conept = [[ 862103. 1002270.  879904.]
 [ 865839.  998688.  866230.]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [9]
printing out current edge:
[[ 865839.  998688.  866230.]
 [ 862103. 1002270.  879904.]]
edge_endpoints_to_process was empty so exiting loop after 33 iterations
starting_node in concept map (that should match the starting edge) = 32
Total time for branches to concept conversion = 0.22139859199523926

recovered_touching_piece = [32]
After concept mapping size = 33
Inside the Limb constructor and concept_network_dict = {1: <networkx_utils.GraphOrderedEdges object at 0x7f301af8b240>}
concept_network_data = [{'starting_soma': 1, 'starting_node': 32, 'starting_endpoints': array([[ 862103., 1002270.,  879904.],
       [ 865839.,  998688.,  866230.]]), 'starting_coordinate': array([865839., 998688., 866230.]), 'touching_soma_vertices': TrackedArray([[864669.2

In [45]:
new_limb_dict[0]["limb_obj"].current_touching_soma_vertices

TrackedArray([[864669.2, 997565.4, 867472.4],
              [863506.4, 997662.8, 866843.4],
              [864429.2, 997518.6, 867434.7],
              [863561.2, 997473.6, 867104.4],
              [863560.2, 997629.8, 867095.6],
              [864810.8, 997654.6, 867551.6],
              [863735.6, 997336.9, 867139. ],
              [863470.6, 997799.4, 866945.5],
              [863475.2, 997999.1, 866973. ],
              [863710.8, 998360.9, 866966.2],
              [864174.7, 997473.4, 867347.9],
              [863472.7, 997835. , 866748.8],
              [863956.3, 997274. , 867219.2],
              [863657.1, 998146.9, 866955.6],
              [863789.1, 998553.6, 866964.2],
              [864082.7, 997387.9, 867266.4],
              [864030.7, 998681.9, 866849.5],
              [863810.1, 997425.7, 867180.3],
              [863889.9, 998605.2, 866758.2]])

# Ready to put into recursive function !!!

# what do I actually use the neuron object for

In [ ]:
"""
total_soams_meshes
getting limb by index
getting all of the limb names
getting soma node name (which can just be enumerating the soma meshes)

So if could just package the preprocessed data up into limbs could run it through the new pipeline

"""

# Visualizing Our Results

In [ ]:
current_neuron.preprocessed_data["soma_to_piece_connectivity"]

In [ ]:
sk.graph_skeleton_and_mesh(other_meshes=[new_limb_dict[0]["limb_obj"].mesh,new_limb_dict[1]["limb_obj"].mesh,
                                         new_limb_dict[0]["limb_obj"][new_limb_dict[0]["curr_starting_branch_idx"]].mesh,
                                        new_limb_dict[1]["limb_obj"][new_limb_dict[1]["curr_starting_branch_idx"]].mesh],
                           
                          other_meshes_colors=["red","yellow","brown","black"],
                           mesh_alpha=1,
                          other_skeletons=[new_limb_dict[0]["limb_obj"].skeleton,new_limb_dict[1]["limb_obj"].skeleton],
                           other_skeletons_colors=["red","black"],
                           other_scatter=[new_limb_dict[0]["soma_border_verts"].reshape(-1,3),
                                          new_limb_dict[1]["soma_border_verts"].reshape(-1,3)],
                           other_scatter_colors=["red","black"],
                           scatter_size=0.1
                           
                          )

# Function that will go find all concept network starting info from: mesh, soma meshes and skeleton

In [ ]:
"""
1) Find out which branch pieces are touhing the soma if any
2) If multiple touching then pick one that has the most touching pieces
3) Find the endpoints of that skeleton
4) Get the closest endpoint to the touching vertices


"""
nru = reload(nru)

In [ ]:
nru.compute_all_concept_network_data_from_limb(current_neuron,ex_limb,soma_restriction=[1])

# Development of the Concept Network Function

In [ ]:
ex_limb.all_concept_network_data

In [ ]:
# Example of what we are starting with 
ex_limb = current_neuron[1]
ex_limb
soma_meshes, _, _ = current_neuron.get_somas()
soma_meshes


In [ ]:
soma_restriction = None#[1]

if soma_restriction is None:
    soma_restriction_names = current_neuron.get_soma_node_names()
else:
    soma_restriction_names = [nru.soma_label(k) for k in soma_restriction]
    
soma_restriction_names_ints = [int(k[1:]) for k in soma_restriction_names]
soma_restriction_names_ints

soma_mesh_list = [current_neuron.concept_network.nodes[k]["data"].mesh for k in soma_restriction_names]
soma_mesh_list

In [ ]:
derived_concept_network_data

In [ ]:
ex_limb.all_concept_network_data

In [ ]:
neuron = reload(neuron)
ex_limb = neuron.Limb(ex_limb)
from pykdtree.kdtree import KDTree

soma_restriction = [1]

In [ ]:
curr_limb_divided_meshes = [ex_limb[k].mesh for k in ex_limb.get_branch_names()]
curr_limb_divided_skeletons = [ex_limb[k].skeleton for k in ex_limb.get_branch_names()]


if soma_restriction is None:
    soma_restriction_names = current_neuron.get_soma_node_names()
else:
    soma_restriction_names = [nru.soma_label(k) for k in soma_restriction]
    
soma_restriction_names_ints = [int(k[1:]) for k in soma_restriction_names]
soma_mesh_list = [current_neuron.concept_network.nodes[k]["data"].mesh for k in soma_restriction_names]


derived_concept_network_data = []
for soma_idx,soma_mesh in zip(soma_restriction_names_ints,soma_mesh_list):
    periph_filter_time = time.time()
    
    original_idxs = np.arange(0,len(curr_limb_divided_meshes))
    

    distances_periphery_to_soma = np.array([tu.closest_distance_between_meshes(soma_mesh,k) for k in curr_limb_divided_meshes])
    periphery_distance_threshold = 2000
    
    original_idxs = original_idxs[distances_periphery_to_soma<periphery_distance_threshold]
    filtered_periphery_meshes = np.array(curr_limb_divided_meshes)[distances_periphery_to_soma<periphery_distance_threshold]
            
        
    touching_pieces,touching_vertices,central_piece_faces = tu.mesh_pieces_connectivity(main_mesh=current_neuron.mesh,
                                central_piece = soma_mesh,
                                periphery_pieces = filtered_periphery_meshes,
                                                 return_vertices=True,
                                                return_central_faces=True
                                                                         )
    print(f"Total time for mesh connectivity = {time.time() - periph_filter_time}")
    #print(f"touching_pieces = {original_idxs[touching_pieces[0]]}")
    if len(touching_pieces) > 0:
        touching_pieces = original_idxs[touching_pieces]
        print(f"touching_pieces = {touching_pieces}")
        
        
        if len(touching_pieces) >= 2:
            print("**More than one touching point to soma, touching_pieces = {touching_pieces}**")
            # picking the piece with the most shared vertices
            len_touch_vertices = [len(k) for k in touching_vertices]
            winning_piece_idx = np.argmax(len_touch_vertices)
            print(f"winning_piece_idx = {winning_piece_idx}")
            touching_pieces = [touching_pieces[winning_piece_idx]]
            print(f"Winning touching piece = {touching_pieces}")
            touching_pieces_soma_vertices = touching_vertices[winning_piece_idx]
        else:
            touching_pieces_soma_vertices = touching_vertices[0]
        if len(touching_pieces) < 1:
            raise Exception("No touching pieces")
            
        #3) With the one that is touching the soma, find the enpoints of the skeleton
        print(f"Using touching_pieces[0] = {touching_pieces[0]}")
        touching_branch = neuron.Branch(curr_limb_divided_skeletons[touching_pieces[0]])
        endpoints = touching_branch.endpoints
        
        """  # -----------  9/1 -------------- #
        New method for finding 
        1) Build a KDTree of the winning touching piece soma boundary vertices
        2) query the endpoints against the vertices
        3) pick the endpoint that has the closest match
        """
        ex_branch_KDTree = KDTree(touching_pieces_soma_vertices)
        distances,closest_nodes = ex_branch_KDTree.query(endpoints)
        closest_endpoint = endpoints[np.argmin(distances)]
        
        derived_concept_network_data.append(dict(starting_soma=soma_idx,
                                                starting_node=touching_pieces[0],
                                                 starting_endpoints=endpoints,
                                                 starting_coordinate=closest_endpoint,
                                                touching_soma_vertices=touching_pieces_soma_vertices)
                                           )) 
    

# Development for the Neuron Object Formation

In [ ]:
# # a) Creating the new concept network
# curr_limb_divided_skeletons =  [curr_limb[k].skeleton for k in new_branch_groups[curr_new_branch_idx]] + [exported_skeletons[curr_new_branch_idx]]
# closest_endpoint = starting_endpoints[curr_new_branch_idx]
# endpoints = neuron.Branch(exported_skeletons[curr_new_branch_idx]).endpoints
# curr_limb_concept_network = nru.branches_to_concept_network(curr_limb_divided_skeletons,closest_endpoint,np.array(endpoints).reshape(-1,3))

# #Run some checks on the new concept network developed
# curr_starting_branch_idx= nru.check_concept_network(curr_limb_concept_network,closest_endpoint = closest_endpoint,
#                           curr_limb_divided_skeletons=curr_limb_divided_skeletons,print_flag=True)[0]
# # How could check it had all of the data

# curr_limb_label="Normal"

In [ ]:
# # b) Creating the new mesh

# """Old way: 
# remaining_meshes_faces_idx =  [curr_limb[k].mesh_face_idx for k in new_branch_groups[curr_new_branch_idx]]
# remaining_meshes_faces_idx.append(np.array(curr_branch.mesh_face_idx[divided_submeshes_idx[curr_new_branch_idx]]))
# """

# new_limb_branch_face_idx = []
# remaining_meshes_face_idx = []
# total_face_count = 0
# for k in new_branch_groups[curr_new_branch_idx]:
#     curr_face_idx  = curr_limb[k].mesh_face_idx
#     remaining_meshes_face_idx.append(curr_face_idx)
#     new_limb_branch_face_idx.append(np.arange(total_face_count,total_face_count+len(curr_face_idx)))
#     total_face_count += len(curr_face_idx)
    
# last_face_idx = np.array(curr_branch.mesh_face_idx[divided_submeshes_idx[curr_new_branch_idx]])
# remaining_meshes_face_idx.append(last_face_idx)
# new_limb_branch_face_idx.append(np.arange(total_face_count,total_face_count+len(last_face_idx)))
    

# final_remaining_faces = np.concatenate(remaining_meshes_faces_idx)                         
# curr_new_limb_mesh = curr_limb.mesh.submesh([final_remaining_faces],append=True,repair=False)

# """
# Checking that it went well:
# reovered_mesh = curr_new_limb_mesh.submesh([new_limb_branch_face_idx[2]],append=True,repair=False)
# original_mesh = curr_limb[new_branch_groups[curr_new_branch_idx][2]].mesh
# reovered_mesh,original_mesh
# """

# Create New Limb Objects from the generated guys

In [ ]:
# curr_limb_correspondence = dict()
# for j,neighb in enumerate(new_branch_groups[curr_new_branch_idx]):
#     #calculate the new mesh correspondence
#     curr_limb_correspondence[j] = dict(branch_skeleton = curr_limb[neighb].skeleton,
#                                       width_from_skeleton = curr_limb[neighb].width,
#                                       branch_mesh=curr_limb[neighb].mesh,
#                                       branch_face_idx=new_limb_branch_face_idx[j])
# #add on the new mesh
# curr_limb_correspondence[len(new_branch_groups[curr_new_branch_idx])] = dict(
#                 branch_skeleton = exported_skeletons[curr_new_branch_idx],
#                 width_from_skeleton = div_st_branch_width[curr_new_branch_idx],
#                 branch_mesh=divided_submeshes[curr_new_branch_idx],
#                 branch_face_idx=new_limb_branch_face_idx[-1])

# # curr_limb_concept_network_dicts = [dict(starting_endpoints=endpoints,
# #                                        starting_node=curr_starting_branch_idx,
# #                                        starting_soma=soma_idx,
# #                                        starting_coordinate=closest_endpoint)]
# curr_limb_concept_network_dicts = {soma_idx:curr_limb_concept_network}

# new_limb_obj = neuron.Limb(mesh = curr_new_limb_mesh,
#                            curr_limb_correspondence=curr_limb_correspondence,
#                            concept_network_dict=curr_limb_concept_network_dicts)

# nx.draw(new_limb_obj.concept_network,with_labels=True)
# new_limb_obj.current_starting_node,new_limb_obj.current_starting_endpoints

# ------- Create the concept networks ------ 

In [ ]:
# Just need to feed into preprocessed data

In [ ]:
"""
Things need to adjust:
1) make new limb correspondence
2) Make new soma to piece connectivity (soma_idx_connectivity)
the current_neuron is just the main mesh


How to store as go through all limb meshes: 

-- Iterate through limbs first
--- Then iterate through somas


a) If no need to split found:
Just add the limb_correspondence and limb_idx to the connectivity like normal

b) If split found need (and let it go until no more splits can be found):
- Create new limb correspondence entries and add them to the list
(Will need to regenerate all of the branch_face_idx)
- Add those limbs to the connectivity

"""

In [ ]:
current_neuron.preprocessed_data["soma_meshes"]
current_neuron.preprocessed_data["soma_to_piece_connectivity"]

In [ ]:
current_neuron.preprocessed_data["limb_correspondence"][0][0].keys()

In [ ]:
current_neuron.preprocessed_data["limb_correspondence"].keys()

In [ ]:
# limb_idx_to_branch_meshes_dict = dict()
# limb_idx_to_branch_skeletons_dict = dict()
# for k in limb_correspondence.keys():
#     limb_idx_to_branch_meshes_dict[k] = [limb_correspondence[k][j]["branch_mesh"] for j in limb_correspondence[k].keys()]
#     limb_idx_to_branch_skeletons_dict[k] = [limb_correspondence[k][j]["branch_skeleton"] for j in limb_correspondence[k].keys()]      

# #getting the soma dictionaries
# soma_idx_to_mesh_dict = dict()
# for k,v in enumerate(current_mesh_data[0]["soma_meshes"]):
#     soma_idx_to_mesh_dict[k] = v

# soma_idx_connectivity = current_mesh_data[0]["soma_to_piece_connectivity"]



# limb_concept_networks,limb_labels = generate_limb_concept_networks_from_global_connectivity(
#     limb_correspondence = limb_correspondence,
#     #limb_idx_to_branch_meshes_dict = limb_idx_to_branch_meshes_dict,
#     #limb_idx_to_branch_skeletons_dict = limb_idx_to_branch_skeletons_dict,

#     soma_meshes=current_mesh_data[0]["soma_meshes"],
#     soma_idx_connectivity=current_mesh_data[0]["soma_to_piece_connectivity"],
#     #soma_idx_to_mesh_dict = soma_idx_to_mesh_dict,
#     #soma_idx_connectivity = soma_idx_connectivity,

#     current_neuron=current_neuron.mesh,
#     return_limb_labels=True
#     )

# Funciton that will generate concept network for a single limb

In [ ]:
"""
Pseudocode: Want to generate the concept network for just one limb if know it's connectivity to the mesh

What want to give it:
1) branches, branch_idxs, widths, meshes
2) Somas and the connection points


"""


In [ ]:
nx.draw(concept_network_copy,with_labels=True)

In [ ]:
new_concept_nx_0 = concept_network_copy.subgraph(new_branch_groups[0])
nx.draw(new_concept_nx_0,with_labels=True)
#add in the extra node


In [ ]:
limb_idx = 2
curr_limb_divided_meshes # a dictionary 

In [ ]:


local_concept_time = time.time()
print(f"\n\n------Working on limb {limb_idx} -------")



# Find Where Limbs Contact The Soma

In [ ]:
"""
Pseudocode:

1) Get all of the limbs that touch a certain soma
2) Get the starting_branch for each
3) Send the soma and all the starting branches to the touching function to get back the vertices
4) Calculate the y range of the somas,
5) Test to see which limbs have y vertices that go above a certain y threshold and those that stay below it
- only keep those that go below (MAKE THIS A PARAMETER)

"""

In [ ]:
neuron = reload(neuron)
current_neuron = neuron.Neuron(neuron_obj)


In [ ]:
#1) Get all of the limbs that touch a certain soma
soma_idx = 1
touching_limbs = current_neuron.get_limbs_touching_soma(soma_idx)
touching_limb_starting_branches = [current_neuron[t].get_starting_branch_by_soma(soma_idx) for t in touching_limbs]
starting_branch_dict = dict([(l,[b]) for l,b in zip(touching_limbs,touching_limb_starting_branches)])
starting_branch_dict

In [ ]:
current_neuron[8][9].skeleton.shape

In [ ]:
returned_color_dict = nviz.visualize_neuron(current_neuron,
                      visualize_type=["mesh","skeleton"],
                     limb_branch_dict=dict(L2=[5]),
                     mesh_color_alpha=1,
                     mesh_whole_neuron=True,return_color_dict=True)

In [ ]:
import matplotlib_utils as mu
mu.plot_color_dict(returned_color_dict)