In [ ]:
"""
Purpose: To get the width calculation after subtracting out the spines

"""

In [1]:
from os import sys
#sys.path.append("../../meshAfterParty/")
sys.path.append("../../meshAfterParty/meshAfterParty")
from importlib import reload
import os
from pathlib import Path
os.getcwd()

import neuron_utils as nru
nru = reload(nru)
import neuron
neuron=reload(neuron)



In [2]:
import neuron_utils as nru
uncompressed_neuron = nru.decompress_neuron(
    filepath="../test_neurons/test_objects/12345_2_soma_practice_decompress.pbz2",
    original_mesh = "../test_neurons/test_objects/12345_2_soma_practice_decompress.off"
)
uncompressed_neuron

Passed faces original mesh check
Passed vertices original mesh check





------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 73 len(curr_limb_divided_skeletons) = 73
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.3591432571411133
touching_pieces = [46]
Total time for mesh connectivity = 0.9057753086090088
Touching piece endpoints = [[756409.  947718.  874266. ]
 [757475.6 948519.  871904.1]]
inside inner loop len(curr_limb_divided_skeletons) = 73
closest_endpoint = [757475.6 948519.  871904.1]
Starting_edge inside branches_to_conept = [[756409.  947718.  874266. ]
 [757475.6 948519.  871904.1]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [48]
printing out current edge:
[[757475.6 948519.  871904.1]
 [756409.  947718.  874266. ]]
edge_endpoints_to_process was empty so exiting loop after 73 iterations
starting_node in concept map (that should match the starting edge) = 46
Total time for branches to concept conversion = 0.3294205665588379

recovered_to

At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [12]
printing out current edge:
[[865721.6 988630.6 860869.1]
 [865475.  982584.  861805. ]]
edge_endpoints_to_process was empty so exiting loop after 17 iterations
starting_node in concept map (that should match the starting edge) = 13
Total time for branches to concept conversion = 0.08718442916870117

recovered_touching_piece = [13]
After concept mapping size = 17
Local time for concept mapping = 0.34638166427612305


------Working on limb 7 -------
inside loop len(curr_limb_divided_meshes) = 25 len(curr_limb_divided_skeletons) = 25
--- Working on soma_idx: 1----
Total time for filtering periphery meshes = 0.07268190383911133
touching_pieces = [1]
Total time for mesh connectivity = 0.23517489433288574
Touching piece endpoints = [[866766.5 993457.3 851380.2]
 [876847.  993084.  841661. ]]
inside inner loop len(curr_limb_divided_skeletons) = 25
closest_endpoint = [866766.5 993457.3 851380.

In [3]:
uncompressed_neuron.calculate_spines()

smoothness_threshold = 0.08
Working on limb L0 branch 46



Working on limb L0 branch 28



Working on limb L0 branch 47



Working on limb L0 branch 21



Working on limb L0 branch 53



Working on limb L0 branch 56



Working on limb L0 branch 20



Working on limb L0 branch 57



Working on limb L0 branch 59



Working on limb L0 branch 70



Working on limb L0 branch 71



Working on limb L0 branch 17



Working on limb L0 branch 18



Working on limb L0 branch 52



Working on limb L0 branch 60



Working on limb L0 branch 13



Working on limb L0 branch 15



Working on limb L0 branch 51



Working on limb L0 branch 58



Working on limb L0 branch 39



Working on limb L0 branch 61



Working on limb L0 branch 12



Working on limb L0 branch 16



Working on limb L0 branch 25



Working on limb L0 branch 49



Working on limb L0 branch 63



Working on limb L0 branch 9



Working on limb L0 branch 19



Working on limb L0 branch 48



Working on limb L0 branch 54



Working on limb L0 branch 55



Working on limb L0 branch 65



Working on limb L0 branch 8



Working on limb L0 branch 42



Working on limb L0 branch 50



Working on limb L0 branch 45



Working on limb L0 branch 62



Working on limb L0 branch 5



Working on limb L0 branch 40



Working on limb L0 branch 43



Working on limb L0 branch 66



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L0 branch 67



Working on limb L0 branch 3



Working on limb L0 branch 41



Working on limb L0 branch 44



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L0 branch 69



Working on limb L0 branch 2



Working on limb L0 branch 22



Working on limb L0 branch 38



Working on limb L0 branch 0



Working on limb L0 branch 34



Working on limb L0 branch 36



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L0 branch 32



Working on limb L0 branch 33



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L0 branch 23



Working on limb L0 branch 72



Working on limb L0 branch 30



Working on limb L0 branch 29



Working on limb L0 branch 31



Working on limb L1 branch 11



Working on limb L1 branch 14



Working on limb L1 branch 15



Working on limb L1 branch 20



Working on limb L1 branch 30



Working on limb L1 branch 23



Working on limb L1 branch 17



Working on limb L1 branch 52



Working on limb L1 branch 12



Working on limb L1 branch 31



Working on limb L1 branch 32



Working on limb L1 branch 13



Working on limb L1 branch 35



Working on limb L1 branch 36



Working on limb L1 branch 34



Working on limb L1 branch 37



Working on limb L1 branch 28



Working on limb L1 branch 33



Working on limb L1 branch 38



Working on limb L1 branch 39



Working on limb L1 branch 27



Working on limb L1 branch 51



Working on limb L1 branch 10



Working on limb L1 branch 40



Working on limb L1 branch 42



Working on limb L1 branch 24



Working on limb L1 branch 44



Working on limb L1 branch 45



Working on limb L1 branch 9



Working on limb L1 branch 19



Working on limb L1 branch 46



Working on limb L1 branch 48



Working on limb L1 branch 7



Working on limb L1 branch 4



Working on limb L1 branch 50



Working on limb L1 branch 2



Working on limb L1 branch 3



Working on limb L1 branch 5



Working on limb L1 branch 0



Working on limb L2 branch 0



Working on limb L2 branch 1



Working on limb L2 branch 2



Working on limb L2 branch 10



Working on limb L2 branch 11



Working on limb L2 branch 5



Working on limb L2 branch 6



Working on limb L2 branch 16



Working on limb L2 branch 7



Working on limb L2 branch 48



Working on limb L2 branch 8



Working on limb L2 branch 14



Working on limb L2 branch 21



Working on limb L2 branch 24



Working on limb L2 branch 18



Working on limb L2 branch 22



Working on limb L2 branch 25



Working on limb L2 branch 34



Working on limb L2 branch 19



Working on limb L2 branch 20



Working on limb L2 branch 26



Working on limb L2 branch 32



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L2 branch 33



Working on limb L2 branch 29



Working on limb L2 branch 30



Working on limb L2 branch 39



Working on limb L2 branch 43



Working on limb L2 branch 44



Working on limb L2 branch 41



Working on limb L2 branch 45



Working on limb L2 branch 46



Working on limb L2 branch 40



Working on limb L2 branch 42.0



Working on limb L3 branch 25



Working on limb L3 branch 2



Working on limb L3 branch 24



Working on limb L3 branch 12



Working on limb L3 branch 20



Working on limb L3 branch 0



Working on limb L3 branch 7



Working on limb L3 branch 35



Working on limb L3 branch 3



Working on limb L3 branch 5



Working on limb L3 branch 19



Working on limb L3 branch 1



Working on limb L3 branch 23



Working on limb L3 branch 11



Working on limb L3 branch 14



Working on limb L3 branch 18



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L3 branch 37



Working on limb L3 branch 13



Working on limb L3 branch 26



Working on limb L3 branch 27



Working on limb L3 branch 29



Working on limb L3 branch 30



Working on limb L3 branch 31



Working on limb L3 branch 34



Working on limb L5 branch 12



Working on limb L5 branch 11



Working on limb L5 branch 13



Working on limb L5 branch 8



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L5 branch 10



Working on limb L5 branch 14



Working on limb L5 branch 15



Working on limb L5 branch 3



Working on limb L5 branch 7



Working on limb L5 branch 0



Working on limb L5 branch 5



Working on limb L5 branch 1



Working on limb L5 branch 4



Working on limb L10 branch 0



Working on limb L4 branch 4



Working on limb L4 branch 0



Working on limb L4 branch 5



Working on limb L4 branch 7



Working on limb L4 branch 8



Working on limb L4 branch 11



Working on limb L4 branch 9



Working on limb L4 branch 10



Working on limb L4 branch 13



Working on limb L4 branch 16



Working on limb L4 branch 18



Working on limb L4 branch 20



Working on limb L4 branch 32



Working on limb L4 branch 19



Working on limb L4 branch 21



Working on limb L4 branch 2



Working on limb L4 branch 33



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L4 branch 28



Working on limb L4 branch 3



Working on limb L4 branch 24



Working on limb L6 branch 13



Working on limb L6 branch 16



Working on limb L6 branch 11



There was only one mesh found from the spine process and mesh split, returning empty array
Working on limb L6 branch 9



Working on limb L6 branch 10



Working on limb L6 branch 2



Working on limb L6 branch 12



Working on limb L6 branch 7



Working on limb L6 branch 15



Working on limb L6 branch 3



Working on limb L6 branch 5



Working on limb L6 branch 4



Working on limb L6 branch 1



Working on limb L7 branch 1



Working on limb L7 branch 2



Working on limb L7 branch 3



Working on limb L7 branch 0



Working on limb L7 branch 4



Working on limb L7 branch 7



Working on limb L7 branch 8



Working on limb L7 branch 6



Working on limb L7 branch 10



Working on limb L7 branch 12



Working on limb L7 branch 13



Working on limb L7 branch 11



Working on limb L7 branch 17



Working on limb L7 branch 24



Working on limb L7 branch 22



Working on limb L7 branch 20.0



Working on limb L8 branch 9



Working on limb L8 branch 5



Working on limb L8 branch 8



Working on limb L8 branch 4



Working on limb L8 branch 10



Working on limb L8 branch 1



Working on limb L8 branch 3



Working on limb L8 branch 7



Working on limb L9 branch 1



Working on limb L9 branch 2



There was only one mesh found from the spine process and mesh split, returning empty array


In [ ]:
# Calculating the new width
uncompressed_neuron.calculate_width_without_spines()

In [ ]:
uncompressed_neuron.concept_network.nodes["L0"]["data"].concept_network.nodes[0]["data"].width_new

In [ ]:
import system_utils as su
su.save_object(uncompressed_neuron,"../test_neurons/test_objects/12345_2_soma_practice_decompress.pkl")

In [ ]:
import neuron_visualizations as nviz
nviz=reload(nviz)

nviz.plot_spines(uncompressed_neuron)


# Developing New width calculation

In [ ]:
"""
Pseudocode for final algorithm:
1) remove all spines
2) get the skeleton corresponding to the mesh
3) resize the skeleton to a certain size
4) For each segment find the ring slice
- project the ring slice out, the normal plane of hte skeletal segment
5) compute the mesh cetner: 
- each face midpoint take the weighted average by weighting hte surface area
6) Computed the weighted average distance of each face midpoint from the 
projection of the mesh center (weighted by the surface area of the point)

- if no mesh then just give that segment the previous width concluded

"""

In [ ]:
import numpy as np
import trimesh_utils as tu
import networkx_utils as xu
import skeleton_utils as sk
from skeleton_utils import *

limb_idx = "L0"
branch_idx = 0


In [ ]:
ex_branch = uncompressed_neuron.concept_network.nodes[limb_idx]["data"].concept_network.nodes[branch_idx]["data"]
ex_branch_mesh = ex_branch.mesh
ex_branch_sk = ex_branch.skeleton
sk.graph_skeleton_and_mesh(other_meshes=[ex_branch_mesh])

# Trying the width with one branch

In [ ]:
"""
Pseudocode: 
The width previously calculated previously was the new distance_threshold
calculated from the skeletal distance function

What this does is: 
1) filter away first and last segment (because those are usually extra big)
2) takes the median value of them all and then filters away any values that are 
larger than 1.5 times the median 


total_threshold = np.max(filtered_measurements) + 2*np.max(filtered_measurements_std)


3) use the total distance threshold as the new distance threshold to use for the
get_skeletal_distance function (the distance threshold is used as the width)


New process: 
0) filter the mesh of spines
1) Divide the branch into a certain length (1000 or 500), this will be each segment
2) Run the get_skeletal_distance function for this segment (and get zeros)
3) this will return one distance measurement per segment
4) for those that are 0, replace with the current average

"""




In [ ]:
import width_utils as wu
wu = reload(wu)
wu.calculate_width_by_segment(ex_branch,print_flag=False)

In [ ]:
# filter out the meshes
tu = reload(tu)
ex_branch_no_spines_mesh = tu.original_mesh_faces_map(ex_branch.mesh,
                            tu.combine_meshes(ex_branch.spines),
                           matching=False,
                           print_flag=True,
                           match_threshold = 0.001,
                                                    return_mesh=True)

sk.graph_skeleton_and_mesh(other_meshes=[ex_branch_no_spines_mesh,ex_branch_mesh],
                          other_meshes_colors=["black","red"])


# Functioni that will apply to all the branches 

In [ ]:
neuron = reload(neuron)
uncompressed_neuron = neuron.Neuron(uncompressed_neuron)

In [ ]:
import copy
ex_branch = uncompressed_neuron.concept_network.nodes[limb_idx]["data"].concept_network.nodes[branch_idx]["data"]

In [ ]:
uncompressed_neuron.calculate_width_without_spines()

In [ ]:
sk.graph_skeleton_and_mesh(other_meshes=[curr_branch_obj.mesh])

# Now do some functions to help with searching

In [ ]:
import neuron_searching as ns

In [ ]:
limb_idx = "L0"
branch_idx = 9
tu = reload(tu)
import numpy_utils as nu
nu = reload(nu)

ex_branch = uncompressed_neuron.concept_network.nodes[limb_idx]["data"].concept_network.nodes[branch_idx]["data"]
print(n_spines(ex_branch),no_spine_width(ex_branch))

ex_branch_no_spines_mesh = tu.original_mesh_faces_map(ex_branch.mesh,
                           ex_branch.spines,
                           matching=False,
                           print_flag=True,
                           match_threshold = 0.001,
                                                    return_mesh=True)

sk.graph_skeleton_and_mesh(other_meshes=[ex_branch_no_spines_mesh,ex_branch.mesh],
                          other_meshes_colors=["black","red"])

In [ ]:
"""
Good query for 

"n_spines < 5 and no_spine_width < 400"

"""

In [ ]:
ns = reload(ns)
current_functions_list = [
    "spines_per_skeletal_length",
    "no_spine_width",
    "n_spines",
    "n_faces_branch"
]

limb_branch_dict = ns.query_neuron(uncompressed_neuron,
                                   query="n_spines < 5 and no_spine_width < 400",
               functions_list=current_functions_list)

import neuron_visualizations as nviz
nviz = reload(nviz)


nviz.visualize_neuron(uncompressed_neuron,
                      visualize_type=["mesh"],
                     limb_branch_dict=limb_branch_dict,
                      mesh_color="red",
                      mesh_color_alpha=1,
                     mesh_whole_neuron=True)

In [ ]:
uncompressed_neuron.plot_soma_limb_concept_network()

In [ ]:
len(uncompressed_neuron.concept_network.nodes["L6"]["data"].mesh.faces), len(uncompressed_neuron.concept_network.nodes["L8"]["data"].mesh.faces)

In [ ]:
# What to need to do now is 
limb_branch_dict=dict(L6=[])#,L8=[])

import neuron_visualizations as nviz
nviz = reload(nviz)

mesh_colors = ["red","yellow","black","brown"]
nviz.visualize_neuron(uncompressed_neuron,
                      visualize_type=["mesh"],
                      mesh_resolution="limb",
                     limb_branch_dict=limb_branch_dict,
                      mesh_color="red",
                      mesh_color_alpha=1,
                     mesh_whole_neuron=True)


# Issue some of the non-connected meshes are the ones that are add on axons

In [ ]:
nviz = reload(nviz)

# What to need to do now is 
limb_branch_dict=dict(L6=[])#,L8=[])

import neuron_visualizations as nviz
nviz = reload(nviz)

#mesh_colors = ["red","yellow","black","brown"]
nviz.visualize_neuron(uncompressed_neuron,
                      limb_branch_dict=dict(),
                      visualize_type=["mesh"],
                          inside_pieces = True,
                            
                            insignificant_limbs = True,
                            
                            non_soma_touching_meshes = True, #whether to graph the inside pieces
                      mesh_color_alpha=1,
                     mesh_whole_neuron=True)


# if have significant non-axons mesh upstream then change back to non-axon

In [ ]:
#Making sure the function_kwargs works
import neuron_searching as ns
ns = reload(ns)
current_functions_list = [
    "spines_per_skeletal_length",
    "no_spine_width",
    "n_spines",
    "n_faces_branch",
    
]

limb_branch_dict = ns.query_neuron(uncompressed_neuron,
                                   query="n_spines < 5 and no_spine_width < 400",
               functions_list=current_functions_list)

current_functions_list = ["test_limb"]
limb_branch_dict = ns.query_neuron(uncompressed_neuron,
                                   query="test_limb==5",
                                   function_kwargs=dict(limb_branch_dict =limb_branch_dict),
                       functions_list=current_functions_list)