In [ ]:
"""
Go from start node to end node

then have an [already checked] edge

"""

In [1]:
"""
Purpose: To implement a proofreading rule that eliminates axon messes

Psuedocode: 
1) Get the concept graph of the axon 
2) Eliminate all of the nodes that are too long skeletal length
3) Divide the remaining axon into connected components
- if too many nodes are in the connected component then it is
an axon mess and should delete all those nodes




"""

'\nPurpose: To implement a proofreading rule that eliminates axon messes\n\nPsuedocode: \n1) Get the concept graph of the axon \n2) Eliminate all of the nodes that are too long skeletal length\n3) Divide the remaining axon into connected components\n- if too many nodes are in the connected component then it is\nan axon mess and should delete all those nodes\n\n\n\n\n'

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from os import sys
sys.path.append("/meshAfterParty/")

In [4]:
from importlib import reload

import neuron_utils as nru

import neuron

import neuron_visualizations as nviz

import time

import datajoint_utils as du

import numpy as np

import proofreading_utils as pru

import preprocessing_vp2 as pre

# -- For the axon classification --

import neuron_searching as ns

import skeleton_utils as sk

import numpy_utils as nu

import networkx_utils as xu

import system_utils as su

import classification_utils as clu
import proofreading_utils as pru

INFO - 2021-02-02 05:31:24,247 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-02-02 05:31:24,248 - settings - Setting database.user to celiib
INFO - 2021-02-02 05:31:24,249 - settings - Setting database.password to newceliipass
INFO - 2021-02-02 05:31:24,253 - settings - Setting stores to {'minnie65': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65', 'stage': '/mnt/dj-stor01/platinum/minnie65'}, 'meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/meshes'}, 'decimated_meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes'}, 'skeletons': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/skeletons'}}
INFO - 2021-02-02 05:31:24,254 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-02 05:31:24,267 - connection - Connect

Connecting celiib@at-database.ad.bcm.edu:3306


INFO - 2021-02-02 05:31:24,550 - settings - Setting enable_python_native_blobs to True


In [5]:
minnie,schema = du.configure_minnie_vm()

INFO - 2021-02-02 05:31:24,648 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-02 05:31:24,940 - settings - Setting enable_python_native_blobs to True


# Getting the Neuron

In [6]:
#segment_id = 864691134884741370 #worked
segment_id = 864691135578531524

In [7]:
neuron_table = (minnie.Decomposition() & dict(segment_id=segment_id))
neuron_table

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    multiplicity   decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time      
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+
86469113557853 0              0.25           30.00     0              0         1              =BLOB=     557809         1112649     0              0              0              0              1           9           155            46             5045037.172526 1176339.645103 24440.919      281.686        250.856        482.737        392.449        3329         0.000659856386 21.47741935483 3780991.291    98             0.000880456934 33.969         395098036850.1 68482266.10663 78314.19736642 104495.8865127 4031612620.920 40934.5497    
 (Total: 1)

In [8]:
neuron_obj = (minnie.Decomposition() & dict(segment_id=segment_id)).fetch1("decomposition")

Decompressing Neuron in minimal output mode...please wait


In [9]:
neuron_obj.calculate_spines()

query = median_mesh_center > 115 and n_faces_branch>100
smoothness_threshold = 0.12
The median_mesh_center was requested and HAS already been calculated
segment_name before cgal = L0_0



segment_name before cgal = L0_1



segment_name before cgal = L0_2



segment_name before cgal = L0_3



segment_name before cgal = L0_4



segment_name before cgal = L0_5



segment_name before cgal = L0_6



segment_name before cgal = L0_7



segment_name before cgal = L0_8



segment_name before cgal = L0_9



segment_name before cgal = L0_10



segment_name before cgal = L0_11



segment_name before cgal = L0_12



segment_name before cgal = L0_13



segment_name before cgal = L0_14



segment_name before cgal = L0_15



segment_name before cgal = L0_16



segment_name before cgal = L0_17



segment_name before cgal = L0_18



segment_name before cgal = L0_19



segment_name before cgal = L0_20



segment_name before cgal = L0_21



segment_name before cgal = L0_22



segment_name before cgal = L0_23



segment_name before cgal = L0_24



segment_name before cgal = L0_25



segment_name before cgal = L0_26



segment_name before cgal = L0_27



segment_name before cgal = L0_28



segment_name before cgal = L1_0



segment_name before cgal = L1_3



segment_name before cgal = L1_5



segment_name before cgal = L1_12



segment_name before cgal = L1_13



segment_name before cgal = L1_14



segment_name before cgal = L1_15



segment_name before cgal = L1_16



segment_name before cgal = L1_17



segment_name before cgal = L1_18



segment_name before cgal = L1_19



segment_name before cgal = L1_20



segment_name before cgal = L1_21



segment_name before cgal = L1_22



segment_name before cgal = L1_23



segment_name before cgal = L1_24



segment_name before cgal = L1_25



segment_name before cgal = L2_27



segment_name before cgal = L2_34



segment_name before cgal = L2_36



segment_name before cgal = L2_37



segment_name before cgal = L2_38



segment_name before cgal = L2_40



segment_name before cgal = L2_42



segment_name before cgal = L2_43



segment_name before cgal = L2_44



segment_name before cgal = L2_45



segment_name before cgal = L3_0



segment_name before cgal = L3_1



segment_name before cgal = L3_2



segment_name before cgal = L3_3



segment_name before cgal = L3_4



segment_name before cgal = L3_5



segment_name before cgal = L3_6



segment_name before cgal = L3_7



segment_name before cgal = L3_8



segment_name before cgal = L3_9



segment_name before cgal = L3_10



segment_name before cgal = L3_11



segment_name before cgal = L4_0



segment_name before cgal = L4_1



segment_name before cgal = L4_2



segment_name before cgal = L4_4



segment_name before cgal = L4_5



segment_name before cgal = L4_6



segment_name before cgal = L4_8



segment_name before cgal = L4_9



segment_name before cgal = L4_10



segment_name before cgal = L4_11



segment_name before cgal = L4_12



segment_name before cgal = L4_13



segment_name before cgal = L4_14



segment_name before cgal = L5_0



segment_name before cgal = L5_1



segment_name before cgal = L5_2



segment_name before cgal = L5_3



segment_name before cgal = L5_4



segment_name before cgal = L5_5



segment_name before cgal = L5_6



segment_name before cgal = L5_7



segment_name before cgal = L5_8



segment_name before cgal = L6_0



segment_name before cgal = L6_1



segment_name before cgal = L6_2



segment_name before cgal = L6_4



segment_name before cgal = L6_10



segment_name before cgal = L7_0



segment_name before cgal = L7_1



segment_name before cgal = L7_2



segment_name before cgal = L7_3



segment_name before cgal = L7_4



segment_name before cgal = L8_0


In [11]:
nviz.plot_objects(neuron_obj.mesh)

# Checking the Axon Mess

In [13]:
ret_group = nru.low_branch_length_clusters(neuron_obj,
                         max_skeletal_length = 10000,
                        use_axon_like_restriction=False)
ret_group

{}

In [12]:
neuron_sin_hairball = pru.filter_away_low_branch_length_clusters(neuron_obj,
                                           max_skeletal_length=10000,
                                           plot_limb_branch_filter_away=False,
                                           plot_limb_branch_filter_with_disconnect_effect=False,
                                          plot_final_neuron=True)

limb_branch_dict was empty so returning original neuron


# High degree crossings development

In [15]:
nru.high_degree_branching_coordinates(neuron_sin_hairball)

[]

# Developing the path function

In [ ]:
ret_col = nviz.visualize_neuron(neuron_obj,
                      limb_branch_dict=dict(L0='all'),
                      return_color_dict=True)

In [ ]:
ex_path = [20,21,23,10]
nviz.visualize_neuron_path(neuron_obj,
                          limb_idx=0,
                          path=ex_path)

In [ ]:
nviz.plot_limb_concept_network_2D(neuron_obj,
                                 node_colors=ret_col)

# Creating the function that will generate the limb branch dict after the edges to be cut are applied

In [16]:
clu.axon_classification(neuron_sin_hairball)


Part 1: Axon like branchese 
{'L1': array([ 1,  2,  4,  6,  7,  8,  9, 10, 11]), 'L2': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34,
       35, 39, 41]), 'L4': array([3, 5, 7]), 'L6': array([ 3,  5,  6,  7,  8,  9, 11]), 'L8': array([0])}
Limb L0 soma angle: 12.61 
Limb L1 soma angle: 133.5 
Limb L2 soma angle: 107.93 
Limb L3 soma angle: 90.48 
Limb L4 soma angle: 78.84 
Limb L5 soma angle: 96.99 
Limb L6 soma angle: 144.18 
Limb L7 soma angle: 49.72 
Limb L8 soma angle: 149.37 

Part 2: possible_axon_limbs = [1, 2, 3, 4, 5, 6, 8]

Phase 2: Working on Limb L1
nodes_to_eliminate = []

Phase 2: Working on Limb L2
nodes_to_eliminate = []

Phase 2: Working on Limb L3
nodes_to_eliminate = []

Phase 2: Working on Limb L4
nodes_to_eliminate = []

Phase 2: Working on Limb L5
nodes_to_eliminate = []

Phase 2: Working on Limb L6
nodes_to_eliminate = []

Phase 2: Working on Limb L8
nodes_to_e

({'L8': array([0.])},
 {'L1': array([ 1,  2,  4,  6,  7,  8,  9, 10, 11]),
  'L2': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34,
         35, 39, 41]),
  'L4': array([3, 7]),
  'L6': array([ 3,  5,  6,  7,  8,  9, 11])})

In [44]:
output = pru.filter_away_axon_on_dendrite_merges(neuron_sin_hairball,
                                                 use_pre_existing_axon_error_labels=True,
                                                 plot_limb_branch_filter_with_disconnect_effect=True,
                                                 plot_final_neuron=False,
                                                 return_error_info=True
                                                )



Branches Requested to Remove (WITH disconnect effect)

 Working on visualization type: mesh




----Working on seperate_graph 0----


---------Working on soma_idx = 0, soma_group_idx 0, endpt = [794973. 559231. 766624.]---------
Starting_edge inside branches_to_conept = [[794973. 559231. 766624.]
 [797610. 563634. 771048.]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [6]
printing out current edge:
[[794973. 559231. 766624.]
 [797610. 563634. 771048.]]
edge_endpoints_to_process was empty so exiting loop after 17 iterations
starting_node in concept map (that should match the starting edge) = 7
Total time for branches to concept conversion = 0.415255069732666

Done generating concept network 




----Working on seperate_graph 0----


---------Working on soma_idx = 0, soma_group_idx 0, endpt = [784017. 555413. 757286.]---------
Starting_edge inside branches_to_conept = [[779914. 559042. 754241.]
 [784017. 555413. 757286.]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [9]
printin

In [47]:
neuron_without_axon_merge,total_area_axon,total_sk_distance_axon = output

In [70]:
neuron_width,total_area_width,total_sk_distance_width = pru.filter_away_large_double_back_or_width_changes(neuron_without_axon_merge,
                                           return_error_info=True,
                                           plot_limb_branch_filter_with_disconnect_effect=True,
                                           plot_limb_branch_filter_away=False,
                                           plot_final_neuron=False,
                                           )
neuron_width

limb_branch_dict was empty so returning original neuron


In [46]:
nviz.visualize_neuron_lite(output[0])


 Working on visualization type: mesh


# Development

In [ ]:
limb_branch_dict_double_back_width = nru.limb_branch_after_limb_edge_removal(neuron_obj=neuron_sin_hairball,
                                       limb_edge_dict=limb_edge_dict,
                                       verbose=True)
limb_branch_dict_double_back_width

In [ ]:
db_cuts,w_cuts = edges_to_cut_by_width_change_and_doubling_back(
    limb_obj=neuron_sin_hairball[0],
double_back_threshold=15)

In [ ]:
nru.limb_branch_after_limb_edge_removal(neuron_sin_hairball,
                                       limb_edge_dict=x)

# Creating the Function that will filter the neuron based on new edges

In [ ]:
#2) Calculate the limb branch dict to be removed


#2b) Plot the limb branch dicts to be removed
if plot_limb_branch_filter_with_disconnect_effect:
        print("\n\nBranches Requested to Remove (WITH disconnect effect)")
        nviz.plot_limb_branch_dict(neuron_obj,
                             removed_limb_branch_dict)

#3) Calculate the total skeleton length and error faces area for what will be removed
if return_error_info:
    total_area = nru.sum_feature_over_limb_branch_dict(neuron_obj,
                                       limb_branch_dict=removed_limb_branch_dict,
                                       feature="area")

total_sk_distance = nru.sum_feature_over_limb_branch_dict(neuron_obj,
                                       limb_branch_dict=removed_limb_branch_dict,
                                       feature="skeletal_length")/1000

if verbose:
    print(f"total_sk_distance = {total_sk_distance}, total_area = {total_area}")
        


In [ ]:
import copy
#neuron_saved = copy.deepcopy(neuron_sin_hairball)

In [ ]:
neuron_sin_hairball=copy.deepcopy(neuron_saved)

In [ ]:
db_cuts,w_cuts = edges_to_cut_by_width_change_and_doubling_back(
    limb_obj=neuron_sin_hairball[0],
double_back_threshold=15)

db_cuts,w_cuts

In [ ]:
all_edges_to_delete = db_cuts + w_cuts
print(f"all_edges_to_delete = {all_edges_to_delete}")


nru.branches_on_limb_edges_cut_and_created(
    limb_obj = neuron_sin_hairball[0],
    edges_to_delete=all_edges_to_delete,
    edges_to_create=None,
    return_removed_branches = False,
    verbose=True)   


In [ ]:
x = dict(L0=dict(edges_to_delete=[np.array([20,16]),np.array([15,22])]))

leftover_limb_branch_dict = nru.limb_branch_after_limb_edge_removal(neuron_sin_hairball,
                                       limb_edge_dict=x)

In [ ]:
leftover_limb_branch_dict

In [ ]:
nviz.visualize_neuron(neuron_sin_hairball,
                     limb_branch_dict=nru.limb_branch_setdiff([nru.neuron_limb_branch_dict(neuron_sin_hairball),leftover_limb_branch_dict]))

In [ ]:
nviz.visualize_neuron(neuron_sin_hairball,
                     limb_branch_dict=leftover_limb_branch_dict)

In [ ]:
limb_branch_after_limb_edge_removal

In [ ]:
#the delete branches fro limb works by the disconnected networks as well

"""
what the other functions do is apply the cuts to the neuron using 
1) split_suggestions_to_concept_networks

"""
new_concept_networks = pru.split_suggestions_to_concept_networks(neuron_obj,limb_results,
                                                                    apply_changes_to_limbs=True)

#just need to split the concept network and we have what we need to send to split_neuron_limb_by_seperated_networks

split_neuron_limb_by_seperated_network

In [ ]:
"""
Conclusion: Follow exact same pattern as node deletions except have options for edge deletions

"""