In [1]:
"""
Go from start node to end node

then have an [already checked] edge

"""

'\nGo from start node to end node\n\nthen have an [already checked] edge\n\n'

In [2]:
"""
Purpose: To implement a proofreading rule that eliminates axon messes

Psuedocode: 
1) Get the concept graph of the axon 
2) Eliminate all of the nodes that are too long skeletal length
3) Divide the remaining axon into connected components
- if too many nodes are in the connected component then it is
an axon mess and should delete all those nodes




"""

'\nPurpose: To implement a proofreading rule that eliminates axon messes\n\nPsuedocode: \n1) Get the concept graph of the axon \n2) Eliminate all of the nodes that are too long skeletal length\n3) Divide the remaining axon into connected components\n- if too many nodes are in the connected component then it is\nan axon mess and should delete all those nodes\n\n\n\n\n'

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
from os import sys
sys.path.append("/meshAfterParty/")

In [5]:
from importlib import reload

import neuron_utils as nru

import neuron

import neuron_visualizations as nviz

import time

import datajoint_utils as du

import numpy as np

import proofreading_utils as pru

import preprocessing_vp2 as pre

# -- For the axon classification --

import neuron_searching as ns

import skeleton_utils as sk

import numpy_utils as nu

import networkx_utils as xu

import system_utils as su

import classification_utils as clu
import proofreading_utils as pru

INFO - 2021-02-02 05:34:51,739 - settings - Setting database.host to at-database.ad.bcm.edu
INFO - 2021-02-02 05:34:51,740 - settings - Setting database.user to celiib
INFO - 2021-02-02 05:34:51,740 - settings - Setting database.password to newceliipass
INFO - 2021-02-02 05:34:51,742 - settings - Setting stores to {'minnie65': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65', 'stage': '/mnt/dj-stor01/platinum/minnie65'}, 'meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/meshes'}, 'decimated_meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes'}, 'skeletons': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/skeletons'}}
INFO - 2021-02-02 05:34:51,743 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-02 05:34:51,753 - connection - Connect

Connecting celiib@at-database.ad.bcm.edu:3306


INFO - 2021-02-02 05:34:51,994 - settings - Setting enable_python_native_blobs to True


In [6]:
minnie,schema = du.configure_minnie_vm()

INFO - 2021-02-02 05:34:52,082 - settings - Setting enable_python_native_blobs to True
INFO - 2021-02-02 05:34:52,354 - settings - Setting enable_python_native_blobs to True


# Getting the Neuron

In [7]:
#segment_id = 864691134884741370 #worked
segment_id = 864691135428521008

In [8]:
neuron_table = (minnie.Decomposition() & dict(segment_id=segment_id))
neuron_table

*segment_id    *decimation_ve *decimation_ra *ver      *process_versi *index    multiplicity   decomposit n_vertices     n_faces     n_not_processe n_error_limbs  n_same_soma_mu n_multi_soma_t n_somas     n_limbs     n_branches     max_limb_n_bra skeletal_lengt max_limb_skele median_branch_ width_median   width_no_spine width_90_perc  width_no_spine n_spines     spine_density  spines_per_bra skeletal_lengt n_spine_eligib spine_density_ spines_per_bra total_spine_vo spine_volume_m spine_volume_d spine_volume_d spine_volume_p run_time    
+------------+ +------------+ +------------+ +-------+ +------------+ +-------+ +------------+ +--------+ +------------+ +---------+ +------------+ +------------+ +------------+ +------------+ +---------+ +---------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +----------+
86469113542852 0              0.25           30.00     0              0         1              =BLOB=     328724         662582      0              1              1              0              1           10          279            98             8747970.255598 3465195.356379 20348.273      68.848         68.848         130.723        130.723        2            2.286244627683 0.007168458781 191077.376     25             1.046696391727 0.08           189757354.2401 94878677.12005 21.69158658474 993.0916899346 7590294.169604 840.0445    
 (Total: 1)

In [9]:
neuron_obj = (minnie.Decomposition() & dict(segment_id=segment_id)).fetch1("decomposition")

Decompressing Neuron in minimal output mode...please wait


In [10]:
neuron_obj.calculate_spines()

query = median_mesh_center > 115 and n_faces_branch>100
smoothness_threshold = 0.12
The median_mesh_center was requested and HAS already been calculated
segment_name before cgal = L0_2



segment_name before cgal = L0_40



segment_name before cgal = L0_41



segment_name before cgal = L0_42



segment_name before cgal = L0_44



There was only one mesh found from the spine process and mesh split, returning empty array
segment_name before cgal = L0_46



There was only one mesh found from the spine process and mesh split, returning empty array
segment_name before cgal = L0_47



segment_name before cgal = L0_48



segment_name before cgal = L0_49



segment_name before cgal = L0_53



segment_name before cgal = L0_55



segment_name before cgal = L1_14



segment_name before cgal = L1_20



segment_name before cgal = L1_25



segment_name before cgal = L1_26



segment_name before cgal = L1_30



segment_name before cgal = L1_36



segment_name before cgal = L1_47



segment_name before cgal = L1_56



segment_name before cgal = L1_57



segment_name before cgal = L1_87



segment_name before cgal = L1_89



segment_name before cgal = L2_7



There was only one mesh found from the spine process and mesh split, returning empty array
segment_name before cgal = L2_14



segment_name before cgal = L2_15



segment_name before cgal = L2_18



segment_name before cgal = L3_2



segment_name before cgal = L3_12



segment_name before cgal = L4_3



segment_name before cgal = L4_5



segment_name before cgal = L4_10



segment_name before cgal = L4_23



segment_name before cgal = L5_3



There was only one mesh found from the spine process and mesh split, returning empty array
segment_name before cgal = L6_8



segment_name before cgal = L6_9



segment_name before cgal = L6_10


In [ ]:
# Splitting the Neuron and Finding Axon Mess

In [13]:
nviz.visualize_neuron(neuron_obj,
                      limb_branch_dict="all")


 Working on visualization type: mesh

 Working on visualization type: skeleton


In [21]:
neuron_obj_split = pru.split_neuron(neuron_obj)
neuron_obj_s = neuron_obj_split[0]


 --------- START OF GET BEST EDGE --------- 
curr_limb.deleted_edges=[]
consider_path_neighbors_for_removal is set so segments_to_consider = [ 2  4  5  7  8  9 10 11 12 13 14 15 16 17 20 21]
***inside resolve crossover!!!!****
match_branches = [[11, 14], [13, 17]]
curr_limb.deleted_edges 5 =[]
nx.number_connected_components(G) before = 1
G.edges() = [(3, 5), (5, 9), (9, 16), (16, 8), (8, 7), (11, 6)]
G.nodes() = [3, 5, 9, 16, 8, 7, 11, 6]
nx.number_connected_components(G) after = 2
Using the resolve crossover delete edges because will help seperate the path
curr_limb_copy.deleted_edges = [[7, 11], [7, 13], [7, 14], [7, 17], [11, 13], [11, 17], [13, 14], [14, 17]]
curr_limb_copy.created_edges = [[11, 14], [13, 17]]
total_soma_paths_to_cut = []
-----------counter = 0------------


------ Working on Soma 0 -------
limb_neighbors = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
limb_neighbors BEFORE error limbs removed = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
limb_neighbors AFTER error limbs removed = [ 

In [41]:
clu.axon_classification(neuron_obj_s)


Part 1: Axon like branchese 
{'L0': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]), 'L1': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89]), 'L10': array([0, 1, 2, 3]), 'L2': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17,
       18, 19, 2

candidate_nodes = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
non_axon_branches_on_subgraph = []
endnodes_to_test BEFORE FILTER = [7058 7685 7964 8704 8721]
endnodes_to_test = [7058 7685 7964 8704 8721]
Skeleton paths distances = [24992.27493446 24945.86578747 24968.5890053  24902.4619074
 24918.91384888]
Filtered indexes = [0 1 2 3 4]
len(filtered_skeletons) = 5
sk_angles = [128.25658664 166.16736036 167.06173528 167.06173528 167.06173528]
Adding the following branches as true axons: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68.

({'L0': array([14, 15, 16, 17, 18, 19, 20, 21, 26, 27, 28, 29, 33, 45, 49, 52, 53,
         55, 56, 57, 58, 59, 63, 64, 65, 67, 68, 74, 75, 78, 79, 80, 81, 84,
         86, 87, 89, 90, 91, 92, 93, 46, 47]),
  'L1': array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
         26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
         39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
         52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
         65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
         78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89.]),
  'L2': array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])},
 {'L0': array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 22, 23, 24, 25,
         30, 31, 32, 34, 35, 36, 37, 38, 39, 43

# Applying the Train Tracks Filtering

In [47]:
neuron_no_cross, a1,a2 = pru.filter_away_crossovers(neuron_obj_s,
                          return_error_info=True,
                            plot_limb_branch_filter_with_disconnect_effect=True,)



Branches Requested to Remove (WITH disconnect effect)

 Working on visualization type: mesh




----Working on seperate_graph 0----


---------Working on soma_idx = 0, soma_group_idx 0, endpt = [1356567.66666667  942436.73333333 1010273.92307692]---------
Starting_edge inside branches_to_conept = [[1356567.66666667  942436.73333333 1010273.92307692]
 [1356905.20345718  942366.09881324 1009628.29939062]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [37]
printing out current edge:
[[1356567.66666667  942436.73333333 1010273.92307692]
 [1356905.20345718  942366.09881324 1009628.29939062]]
edge_endpoints_to_process was empty so exiting loop after 96 iterations
starting_node in concept map (that should match the starting edge) = 44
Total time for branches to concept conversion = 2.7300522327423096

Done generating concept network 




----Working on seperate_graph 0----


---------Working on soma_idx = 0, soma_group_idx 0, endpt = [1357990.75  946368.3  1013884.  ]---------
Starting_edge inside branches_to_conept = [[1357990.75    

# Developing of the Train Tracks

In [46]:




pru.edges_to_create_and_delete_crossover(
                                        limb_obj = neuron_obj_s[0],
                                        high_degree_offset = 2500,#1500,
                                        comparison_distance = 2000,
                                        match_threshold = 35,
                                        axon_dependent = True,
                                        verbose = True,
                                        )

crossover_coordinates = [[1289926.70939453  948421.74209672  955153.81769911]
 [1351580.33230957  942857.51457549  982386.37746099]
 [1354384.72070685  951542.05790286 1006809.57917466]
 [1453985.2970117   955705.53901568 1032160.92144517]
 [1527560.7399743   951566.77896826  884152.44172519]]
Only found 1 successful matches so skipping
Only found 1 successful matches so skipping
Skipping coordinate 2 ([1354384.72070685  951542.05790286 1006809.57917466]) because branch 41 was not an axon-like or axon piece 
Found matching train tracks for coordinate 3 = [1453985.2970117   955705.53901568 1032160.92144517]
Only found 0 successful matches so skipping


([[75, 79], [74, 80]], [[74, 75], [74, 79], [75, 80], [79, 80]])

# Want to find all of the high degree nodes

In [16]:
scatter_points = nru.high_degree_branching_coordinates(neuron_obj,
                                     min_degree_to_find=5,
                                     exactly_equal=False)

In [18]:
nviz.visualize_neuron(neuron_obj,
                      visualize_type=["skeleton","mesh"],
                     limb_branch_dict="all",
                     scatters=scatter_points,
                     scatter_size=0.1)


 Working on visualization type: skeleton

 Working on visualization type: mesh


In [19]:
railroad_intersections = nru.high_degree_branching_coordinates(neuron_obj,
                                     min_degree_to_find=4,
                                     exactly_equal=True)

In [20]:
nviz.visualize_neuron(neuron_obj,
                      visualize_type=["mesh"],
                      mesh_whole_neuron=True,
                     scatters=railroad_intersections,
                     scatter_size=0.25)


 Working on visualization type: mesh
