In [1]:
"""
Purpose: To try and run the neuron preprocessing pipeline
but use the meshparty option

Pseudocode: 
1) Load one of the meshes to try and preprocess
2) Use the preprocessing pipeline with meshparty selected
3) visualize

"""

'\nPurpose: To try and run the neuron preprocessing pipeline\nbut use the meshparty option\n\nPseudocode: \n1) Load one of the meshes to try and preprocess\n2) Use the preprocessing pipeline with meshparty selected\n3) visualize\n\n'

In [2]:
from os import sys
sys.path.append("/meshAfterParty/")
from importlib import reload
import os
from pathlib import Path
import time

In [3]:
import neuron_utils as nru
nru = reload(nru)
import neuron
neuron=reload(neuron)

import system_utils as su
import numpy as np

# Load the Neuron mesh

In [4]:
import trimesh_utils as tu
mesh_file_path = Path("/notebooks/test_neurons/multi_soma_example.off")
mesh_file_path.exists()
current_neuron_mesh = tu.load_mesh_no_processing(str(mesh_file_path.absolute()))

In [5]:
# picking a random segment id
segment_id = 12345
description = "double_soma"

# Doing the Actual processing of the Neuron

In [15]:
import skeleton_utils as sk
sk = reload(sk)

In [19]:
import soma_extraction_utils as sm
somas = sm.extract_soma_center(segment_id,
                                                 current_neuron_mesh.vertices,
                                                 current_neuron_mesh.faces)

Current Arguments Using (adjusted for decimation):
 large_mesh_threshold= 15000.0 
large_mesh_threshold_inner = 10000.0 
soma_size_threshold = 1250.0 
soma_size_threshold_max = 12000.0
outer_decimation_ratio = 0.25
inner_decimation_ratio = 0.25
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 2525
xvfb-run -n 2525 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neuron_12345.off -o /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neuron_12345_decimated.off -s /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/decimation_meshlab_25975772.mls
Total found significant pieces before Poisson = [<trimesh.Trimesh(vertices.shape=(139795, 3), faces.shape=(284336, 3))>]
----- working on large mesh #0: <trimesh.Trimesh(vertices.shape=(139795, 3), faces.shape=(284336, 3))>
pre_largest_mesh_path = /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neur

Total found significant pieces AFTER Poisson = [<trimesh.Trimesh(vertices.shape=(151133, 3), faces.shape=(302274, 3))>, <trimesh.Trimesh(vertices.shape=(42554, 3), faces.shape=(85104, 3))>]
----- working on mesh after poisson #0: <trimesh.Trimesh(vertices.shape=(151133, 3), faces.shape=(302274, 3))>
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 5272
xvfb-run -n 5272 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neuron_12345_decimated_largest_piece_poisson_largest_inner.off -o /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neuron_12345_decimated_largest_piece_poisson_largest_inner_decimated.off -s /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/decimation_meshlab_2589493.mls
done exporting decimated mesh: neuron_12345_decimated_largest_piece_poisson_largest_inner.off
1) Starting: Mesh importing and Pymesh fix
loading mesh from vertices and triangl

removed temporary input file: /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_767069.off
removed temporary output file: /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_767069_poisson.off
/notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/poisson_483354.mls is being deleted....
Inside sphere validater: ratio_val = 2.7559125454571776
----- working on mesh after poisson #1: <trimesh.Trimesh(vertices.shape=(42554, 3), faces.shape=(85104, 3))>
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 4590
xvfb-run -n 4590 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neuron_12345_decimated_largest_piece_poisson_largest_inner.off -o /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/12345/neuron_12345_decimated_largest_piece_poisson_largest_inner_decimated.off -s /notebooks/Platinum_Skeletonization_

In [35]:
import time
meshparty_time = time.time()

import meshparty_skeletonize as m_sk
m_sk = reload(m_sk)

nru = reload(nru)
neuron = reload(neuron)
double_neuron_processed = neuron.Neuron(
    mesh=current_neuron_mesh,
    segment_id=segment_id,
    description=description,
    preprocessing_decomposition_type="meshparty",
    suppress_preprocessing_print=False,
    somas = somas
    
)

print(f"Total time for processing: {time.time() - meshparty_time}")

--- 0) Having to preprocess the Neuron becuase no preprocessed data
Please wait this could take a while.....





****** Phase A ***************





Soma List = [<trimesh.Trimesh(vertices.shape=(3065, 3), faces.shape=(6001, 3))>, <trimesh.Trimesh(vertices.shape=(2124, 3), faces.shape=(4205, 3))>]
soma_mesh_list_centers = [array([756862.7897553 , 959093.87004894, 874202.02264274]), array([864007.66209981, 994520.88554614, 859495.97886064])]
# total split meshes = 79
There were 78 pieces found after size threshold
# of non soma touching seperate meshes = 58
# of inside pieces = 20
# of soma containing seperate meshes = 1
meshes with somas = {0: [0, 1]}


----Working on soma-containing mesh piece {z}----

inside Soma subtraction
mesh pieces in subtact soma BEFORE the filtering inside pieces = [<trimesh.Trimesh(vertices.shape=(153985, 3), faces.shape=(308998, 3))>, <trimesh.Trimesh(vertices.shape=(87699, 3), faces.shape=(176253, 3))>, <trimesh.Trimesh(vertices.shape=(57751, 3), faces.shap

  0%|          | 0/1 [00:00<?, ?it/s]

Total time for mesh_pieces_connectivity= 11.65623688697815
# of insignificant_limbs = 0 with trimesh : []
Using DECOMPOSITION TYPE: meshparty
------------Working on limb #0-------------
Root for limb 0 = [758199.2 951673.5 875799.4]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1



100%|██████████| 1/1 [00:03<00:00,  3.52s/it]


Total time for meshParty skeletonization = 4.8553643226623535

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.06760311126708984

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (60, 61)
empty_indices % = 0.0
 conflict_indices % = 0.01309393588308015


  0%|          | 0/1 [00:00<?, ?it/s]


Total time for meshParty mesh correspondence = 5.559762477874756

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.0054759979248046875

branch segment sizes = {0: (443, 2, 3), 1: (24, 2, 3), 2: (183, 2, 3), 3: (85, 2, 3), 4: (44, 2, 3), 5: (85, 2, 3), 6: (127, 2, 3), 7: (32, 2, 3), 8: (42, 2, 3), 9: (26, 2, 3), 10: (35, 2, 3), 11: (54, 2, 3), 12: (65, 2, 3), 13: (218, 2, 3), 14: (230, 2, 3), 15: (143, 2, 3), 16: (170, 2, 3), 17: (50, 2, 3), 18: (111, 2, 3), 19: (60, 2, 3), 20: (429, 2, 3), 21: (102, 2, 3), 22: (2, 2, 3), 23: (20, 2, 3), 24: (6, 2, 3), 25: (82, 2, 3), 26: (218, 2, 3), 27: (29, 2, 3), 28: (74, 2, 3), 29: (18, 2, 3), 30: (337, 2, 3), 31: (47, 2, 3), 32: (40, 2, 3), 33: (15, 2, 3), 34: (180, 2, 3), 35: (271, 2, 3), 36: (234, 2, 3), 37: (65, 2, 3), 38: (102, 2, 3), 39: (54, 2, 3), 40: (137, 2, 3), 41: (60, 2, 3), 42: (70, 2, 3), 43: (147, 2, 3), 44: (201, 2, 3), 45: (53, 2, 3), 46: (141, 2, 3), 47: (144, 2, 3), 48: (163, 2, 3), 49: (57, 2, 3), 50: (


100%|██████████| 1/1 [00:01<00:00,  1.54s/it]


Total time for meshParty skeletonization = 2.3217058181762695

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.045412540435791016

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (44, 45)
empty_indices % = 0.0
 conflict_indices % = 0.010961515548671513


  0%|          | 0/57750 [00:00<?, ?it/s]


Total time for meshParty mesh correspondence = 3.277130365371704

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.003504037857055664

branch segment sizes = {0: (421, 2, 3), 1: (173, 2, 3), 2: (471, 2, 3), 3: (57, 2, 3), 4: (134, 2, 3), 5: (186, 2, 3), 6: (9, 2, 3), 7: (92, 2, 3), 8: (34, 2, 3), 9: (66, 2, 3), 10: (18, 2, 3), 11: (60, 2, 3), 12: (92, 2, 3), 13: (156, 2, 3), 14: (102, 2, 3), 15: (13, 2, 3), 16: (155, 2, 3), 17: (126, 2, 3), 18: (8, 2, 3), 19: (82, 2, 3), 20: (30, 2, 3), 21: (1, 2, 3), 22: (3, 2, 3), 23: (86, 2, 3), 24: (166, 2, 3), 25: (259, 2, 3), 26: (30, 2, 3), 27: (116, 2, 3), 28: (85, 2, 3), 29: (288, 2, 3), 30: (33, 2, 3), 31: (577, 2, 3), 32: (128, 2, 3), 33: (14, 2, 3), 34: (83, 2, 3), 35: (139, 2, 3), 36: (98, 2, 3), 37: (34, 2, 3), 38: (156, 2, 3), 39: (50, 2, 3), 40: (43, 2, 3), 41: (353, 2, 3), 42: (362, 2, 3), 43: (64, 2, 3), 44: (46, 2, 3)}
------------Working on limb #2-------------
Root for limb 2 = [865523.6 999041.2 866004.2]



100%|██████████| 1/1 [00:00<00:00,  1.01it/s]


Total time for meshParty skeletonization = 1.5558662414550781

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.046518564224243164

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (38, 39)
empty_indices % = 0.0
 conflict_indices % = 0.010172799419684108



Total time for meshParty mesh correspondence = 2.055528402328491

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.004297971725463867

branch segment sizes = {0: (141, 2, 3), 1: (15, 2, 3), 2: (36, 2, 3), 3: (457, 2, 3), 4: (258, 2, 3), 5: (152, 2, 3), 6: (14, 2, 3), 7: (14, 2, 3), 8: (12, 2, 3), 9: (77, 2, 3), 10: (189, 2, 3), 11: (10, 2, 3), 12: (111, 2, 3), 13: (95, 2, 3), 14: (76, 2, 3), 15: (185, 2, 3), 16: (78, 2, 3), 17: (3, 2, 3), 18: (762, 2, 3), 19: (326, 2, 3), 20: (55, 2, 3), 21: (66, 2, 3), 22: (111, 2, 3), 23: (4, 2, 3), 24: (83, 2, 3), 25: (56, 2, 3), 26: (36, 2, 3), 27: (64, 2, 3), 28: (183, 2, 3), 29: (79, 2, 3), 30: (37, 2, 3), 31: (77, 2, 3), 32: (328, 2, 3), 33: (40, 2, 3), 34: (55, 2, 3), 35: (284, 2, 3), 36: (31, 2, 3), 37: (280, 2, 3), 38: (127, 2, 3)}
------------Working on limb #3-------------
Root for limb 3 = [757928.4 962502.2 866083.1]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1


100%|██████████| 1/1 [00:00<00:00,  1.05it/s]


Total time for meshParty skeletonization = 1.5027730464935303

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.04194808006286621

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (47, 48)
empty_indices % = 0.0
 conflict_indices % = 0.019339713085464276



Total time for meshParty mesh correspondence = 2.399609088897705

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.005278587341308594

branch segment sizes = {0: (207, 2, 3), 1: (7, 2, 3), 2: (8, 2, 3), 3: (337, 2, 3), 4: (76, 2, 3), 5: (13, 2, 3), 6: (3, 2, 3), 7: (74, 2, 3), 8: (157, 2, 3), 9: (54, 2, 3), 10: (2, 2, 3), 11: (5, 2, 3), 12: (19, 2, 3), 13: (14, 2, 3), 14: (91, 2, 3), 15: (79, 2, 3), 16: (4, 2, 3), 17: (40, 2, 3), 18: (120, 2, 3), 19: (14, 2, 3), 20: (89, 2, 3), 21: (40, 2, 3), 22: (4, 2, 3), 23: (155, 2, 3), 24: (53, 2, 3), 25: (9, 2, 3), 26: (2, 2, 3), 27: (193, 2, 3), 28: (53, 2, 3), 29: (321, 2, 3), 30: (162, 2, 3), 31: (39, 2, 3), 32: (243, 2, 3), 33: (5, 2, 3), 34: (77, 2, 3), 35: (30, 2, 3), 36: (49, 2, 3), 37: (102, 2, 3), 38: (41, 2, 3), 39: (84, 2, 3), 40: (11, 2, 3), 41: (127, 2, 3), 42: (41, 2, 3), 43: (312, 2, 3), 44: (31, 2, 3), 45: (142, 2, 3), 46: (60, 2, 3), 47: (150, 2, 3)}
------------Working on limb #4-------------
Root for l

100%|██████████| 1/1 [00:00<00:00,  1.37it/s]


Total time for meshParty skeletonization = 1.2404303550720215

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.03472399711608887

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (33, 34)
empty_indices % = 0.0
 conflict_indices % = 0.01249545949872866


  0%|          | 0/51855 [00:00<?, ?it/s]


Total time for meshParty mesh correspondence = 2.014843463897705

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.0040476322174072266

branch segment sizes = {0: (87, 2, 3), 1: (15, 2, 3), 2: (5, 2, 3), 3: (2, 2, 3), 4: (62, 2, 3), 5: (5, 2, 3), 6: (41, 2, 3), 7: (35, 2, 3), 8: (131, 2, 3), 9: (24, 2, 3), 10: (46, 2, 3), 11: (120, 2, 3), 12: (36, 2, 3), 13: (50, 2, 3), 14: (116, 2, 3), 15: (115, 2, 3), 16: (39, 2, 3), 17: (40, 2, 3), 18: (64, 2, 3), 19: (12, 2, 3), 20: (165, 2, 3), 21: (482, 2, 3), 22: (31, 2, 3), 23: (304, 2, 3), 24: (119, 2, 3), 25: (13, 2, 3), 26: (107, 2, 3), 27: (266, 2, 3), 28: (312, 2, 3), 29: (38, 2, 3), 30: (101, 2, 3), 31: (86, 2, 3), 32: (243, 2, 3), 33: (402, 2, 3)}
------------Working on limb #5-------------
Root for limb 5 = [752618.4 964281.4 869517. ]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1



100%|██████████| 1/1 [00:00<00:00,  3.39it/s]


Total time for meshParty skeletonization = 0.7417123317718506

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.014194965362548828

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (6, 7)
empty_indices % = 0.0
 conflict_indices % = 0.0036417795714422984


  0%|          | 0/29316 [00:00<?, ?it/s]


Total time for meshParty mesh correspondence = 1.6302413940429688

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.0011951923370361328

branch segment sizes = {0: (774, 2, 3), 1: (127, 2, 3), 2: (65, 2, 3), 3: (78, 2, 3), 4: (90, 2, 3), 5: (353, 2, 3), 6: (792, 2, 3)}
------------Working on limb #6-------------
Root for limb 6 = [865118.6 988464.8 861143.9]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1



100%|██████████| 1/1 [00:00<00:00,  3.95it/s]


Total time for meshParty skeletonization = 0.5411090850830078

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.01511240005493164

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (16, 17)
empty_indices % = 0.0
 conflict_indices % = 0.010618565472645282


  0%|          | 0/29166 [00:00<?, ?it/s]


Total time for meshParty mesh correspondence = 1.10630464553833

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.002536773681640625

branch segment sizes = {0: (142, 2, 3), 1: (168, 2, 3), 2: (34, 2, 3), 3: (24, 2, 3), 4: (12, 2, 3), 5: (1, 2, 3), 6: (31, 2, 3), 7: (50, 2, 3), 8: (326, 2, 3), 9: (58, 2, 3), 10: (118, 2, 3), 11: (211, 2, 3), 12: (128, 2, 3), 13: (142, 2, 3), 14: (482, 2, 3), 15: (53, 2, 3), 16: (164, 2, 3)}
------------Working on limb #7-------------
Root for limb 7 = [866520.2 994194.9 851413.6]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1



100%|██████████| 1/1 [00:00<00:00,  3.76it/s]


Total time for meshParty skeletonization = 0.549884557723999

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.017827510833740234

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (18, 19)
empty_indices % = 0.0
 conflict_indices % = 0.010755258126195029


  0%|          | 0/14724 [00:00<?, ?it/s]


Total time for meshParty mesh correspondence = 1.104395866394043

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.0032701492309570312

branch segment sizes = {0: (62, 2, 3), 1: (196, 2, 3), 2: (68, 2, 3), 3: (82, 2, 3), 4: (42, 2, 3), 5: (141, 2, 3), 6: (6, 2, 3), 7: (320, 2, 3), 8: (28, 2, 3), 9: (239, 2, 3), 10: (83, 2, 3), 11: (4, 2, 3), 12: (149, 2, 3), 13: (94, 2, 3), 14: (94, 2, 3), 15: (167, 2, 3), 16: (309, 2, 3), 17: (34, 2, 3), 18: (35, 2, 3)}
------------Working on limb #8-------------
Root for limb 8 = [863258.4 994795.4 851581.6]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1


100%|██████████| 1/1 [00:00<00:00, 10.63it/s]


Total time for meshParty skeletonization = 0.2651026248931885

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.010241270065307617

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (10, 11)
empty_indices % = 0.0
 conflict_indices % = 0.009358740455436177


100%|██████████| 1/1 [00:00<00:00, 108.63it/s]


Total time for meshParty mesh correspondence = 0.5140562057495117

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.0014128684997558594

branch segment sizes = {0: (69, 2, 3), 1: (431, 2, 3), 2: (15, 2, 3), 3: (117, 2, 3), 4: (127, 2, 3), 5: (52, 2, 3), 6: (295, 2, 3), 7: (39, 2, 3), 8: (6, 2, 3), 9: (43, 2, 3), 10: (56, 2, 3)}
------------Working on limb #9-------------
Root for limb 9 = [759735.2 964457.4 877252.6]

Step 1: Starting Skeletonization
smooth_neighborhood = 1
smooth_neighborhood = 1
Total time for meshParty skeletonization = 0.033466339111328125

Step 2: Decomposing Branches
Total time for meshParty decomposition = 0.0012547969818115234

Step 3: Mesh correspondence
max(original_labels),len(original_labels) = (0, 1)
empty_indices % = 0.0
 conflict_indices % = 0.0



Total time for meshParty mesh correspondence = 0.08910036087036133

Step 4: Retrieving Widths
Total time for meshParty Retrieving Widths = 0.0003199577331542969

branch segment sizes = {0: (65, 2, 3)}





****** Phase C ***************







------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 61 len(curr_limb_divided_skeletons) = 61
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 0.6333177089691162
touching_pieces = [4]
Total time for mesh connectivity = 0.8727929592132568
Touching piece endpoints = [[754818.09674815 945265.28459266 874984.43059141]
 [758656.5463299  950259.33381173 872013.37980394]]
inside inner loop len(curr_limb_divided_skeletons) = 61
closest_endpoint = [758656.5463299  950259.33381173 872013.37980394]
Starting_edge inside branches_to_conept = [[754818.09674815 945265.28459266 874984.43059141]
 [758656.5463299  950259.33381173 872013.37980394]]
At the start, starting_node (in terms of the skeleton, that shouldn'

touching_pieces = [2]
Total time for mesh connectivity = 0.35342955589294434
Touching piece endpoints = [[746565.14189411 969566.8857893  861509.36319248]
 [752721.52407524 964384.60481626 869347.08507125]]
inside inner loop len(curr_limb_divided_skeletons) = 7
closest_endpoint = [752721.52407524 964384.60481626 869347.08507125]
Starting_edge inside branches_to_conept = [[746565.14189411 969566.8857893  861509.36319248]
 [752721.52407524 964384.60481626 869347.08507125]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [4]
printing out current edge:
[[752721.52407524 964384.60481626 869347.08507125]
 [746565.14189411 969566.8857893  861509.36319248]]
edge_endpoints_to_process was empty so exiting loop after 7 iterations
starting_node in concept map (that should match the starting edge) = 2
Total time for branches to concept conversion = 0.17215776443481445

recovered_touching_piece = [2]
After concept mapping size = 7
Local time for conce

removed temporary input file: /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_350920.off
removed temporary output file: /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_350920_poisson.off
/notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/poisson_362287.mls is being deleted....
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 3308
xvfb-run -n 3308 -s "-screen 0 800x600x24" meshlabserver $@  -i /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_157227.off -o /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_157227_poisson.off -s /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/poisson_664364.mls


removed temporary input file: /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_157227.off
removed temporary output file: /notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/neuron_157227_poisson.off
/notebooks/Platinum_Skeletonization_meshparty/meshparty_testing/Poisson_temp/poisson_664364.mls is being deleted....
--- 3) Finshed generating soma objects and adding them to concept graph: 19.093827724456787
--- 4a) Finshed generating curr_limb_meshes_face_idx: 4.432070970535278
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
Concept graph size was 1 or less so r

# Visualize the Processed Neuron

In [38]:
import neuron_visualizations as nviz
nviz.visualize_neuron(double_neuron_processed,
                     visualize_type=["mesh","skeleton","network"],
                     limb_branch_dict=dict(L1=["all"]),
                      node_size=0.3,
                      arrow_size=0.3
                     )


 Working on visualization type: mesh

 Working on visualization type: skeleton

 Working on visualization type: network


# debugging the skeletonization

In [22]:
limb_idx = 2

curr_limb_mesh_file = f"limb_{limb_idx}_mesh.off"
curr_limb_skeleton_file = f"limb_{limb_idx}_sk_meshparty_obj.pkl"

import system_utils as su
sk_meshparty_obj = su.load_object(curr_limb_skeleton_file)

import trimesh_utils as tu
curr_limb_mesh = tu.load_mesh_no_processing(curr_limb_mesh_file)

In [27]:
import meshparty_skeletonize as m_sk
m_sk = reload(m_sk)
segments, segment_maps = m_sk.compute_segments(sk_meshparty_obj)

for s in segments:
    print(len(s))

142
16
37
458
259
153
15
15
13
78
190
11
112
96
77
186
79
4
763
327
56
67
112
5
84
57
37
65
184
80
38
78
329
41
56
285
32
281
128
